import React,{createContext,useCallback,useContext,useEffect,useMemo,useState} from "react";

type User={id:string;email:string;username:string;firstName:string;lastName:string;role:string;primaryEmailAddress?:{emailAddress:string;verification?:{status:string}}};
type AuthState={isLoaded:boolean;isSignedIn:boolean;user:User|null;refresh:()=>Promise<void>;signOut:()=>Promise<void>};
const AuthContext=createContext<AuthState|null>(null);
async function request(path:string,init:RequestInit={}){const response=await fetch(path,{credentials:"same-origin",headers:{Accept:"application/json",...(init.body?{"Content-Type":"application/json"}:{}),...(init.headers||{})},...init});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Authentication request failed");return data;}
export function ClerkProvider({children}:{children:React.ReactNode;publishableKey?:string;proxyUrl?:string;appearance?:unknown;signInUrl?:string;signUpUrl?:string;localization?:unknown;routerPush?:(to:string)=>void;routerReplace?:(to:string)=>void}){const[user,setUser]=useState<User|null>(null);const[isLoaded,setLoaded]=useState(false);const refresh=useCallback(async()=>{const data=await request("/api/auth/session");setUser(data.signedIn?data.user:null);setLoaded(true);},[]);useEffect(()=>{void refresh()},[refresh]);const signOut=useCallback(async()=>{await request("/api/auth/sign-out",{method:"POST"});setUser(null);window.dispatchEvent(new CustomEvent("lunavo-auth-changed"));},[]);const value=useMemo(()=>({isLoaded,isSignedIn:Boolean(user),user,refresh,signOut}),[isLoaded,user,refresh,signOut]);return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>}
export function useAuth(){const ctx=useContext(AuthContext);if(!ctx)throw new Error("useAuth must be used inside ClerkProvider");return{isLoaded:ctx.isLoaded,isSignedIn:ctx.isSignedIn,userId:ctx.user?.id??null,getToken:async()=>null,signOut:ctx.signOut};}
export function useUser(){const ctx=useContext(AuthContext);if(!ctx)throw new Error("useUser must be used inside ClerkProvider");return{isLoaded:ctx.isLoaded,isSignedIn:ctx.isSignedIn,user:ctx.user};}
export function useClerk(){const ctx=useContext(AuthContext);if(!ctx)throw new Error("useClerk must be used inside ClerkProvider");return{signOut:ctx.signOut,addListener:(listener:(event:{user:User|null})=>void)=>{const handler=()=>listener({user:ctx.user});window.addEventListener("lunavo-auth-changed",handler);return()=>window.removeEventListener("lunavo-auth-changed",handler);}};}
export function Show({when,children}:{when:"signed-in"|"signed-out";children:React.ReactNode}){const{isLoaded,isSignedIn}=useAuth();if(!isLoaded)return null;return when==="signed-in"?(isSignedIn?children:null):(!isSignedIn?children:null);}
function AuthCard({title,submit,children,fields}:{title:string;submit:string;fields:{firstName?:string;lastName?:string;username?:string};children:(state:{email:string;password:string;error:string;busy:boolean;setEmail:React.Dispatch<React.SetStateAction<string>>;setPassword:React.Dispatch<React.SetStateAction<string>>})=>React.ReactNode}){const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);const submitForm=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{await request(submit==="Create account"?"/api/auth/sign-up":"/api/auth/sign-in",{method:"POST",body:JSON.stringify({email,password,...fields})});window.dispatchEvent(new CustomEvent("lunavo-auth-changed"));window.location.assign("/dashboard");}catch(err){setError(err instanceof Error?err.message:"Authentication failed");}finally{setBusy(false);}};return <form onSubmit={submitForm} className="w-full max-w-[440px] rounded-2xl border border-[#d9d2c4] bg-[#fbfaf6] p-6 shadow-[0_18px_38px_rgba(31,43,56,.07)]"><h1 className="mb-5 text-2xl font-extrabold text-[#182333]">{title}</h1>{children({email,password,setEmail,setPassword,error,busy})}</form>;}
export function SignIn(){return <AuthCard title="Welcome back" submit="Sign in" fields={{}}>{({email,password,setEmail,setPassword,error,busy})=><><label className="block text-sm font-bold">Email<input required autoComplete="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-[#d9d2c4] bg-[#f7f4ed] px-3"/></label><label className="mt-4 block text-sm font-bold">Password<input required autoComplete="current-password" type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-[#d9d2c4] bg-[#f7f4ed] px-3"/></label>{error&&<p className="mt-4 text-sm text-[#943b35]">{error}</p>}<button disabled={busy} className="mt-6 h-11 w-full rounded-xl bg-[#182333] text-sm font-extrabold text-white">{busy?"Signing in…":"Sign in"}</button></>}</AuthCard>;}
export function SignUp({initialValues}:{initialValues?:{firstName?:string;lastName?:string;username?:string}}){const fields={firstName:initialValues?.firstName??"",lastName:initialValues?.lastName??"",username:initialValues?.username??""};return <AuthCard title="Create your Lunavo account" submit="Create account" fields={fields}>{({email,password,setEmail,setPassword,error,busy})=><><p className="mb-4 rounded-xl bg-[#f7f4ed] px-3 py-3 text-sm text-[#697687]">Creating an account for <strong>{fields.firstName} {fields.lastName}</strong> · @{fields.username}</p><label className="block text-sm font-bold">Email<input required autoComplete="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-[#d9d2c4] bg-[#f7f4ed] px-3"/></label><label className="mt-4 block text-sm font-bold">Password<input required minLength={8} autoComplete="new-password" type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-[#d9d2c4] bg-[#f7f4ed] px-3"/></label>{error&&<p className="mt-4 text-sm text-[#943b35]">{error}</p>}<button disabled={busy} className="mt-6 h-11 w-full rounded-xl bg-[#182333] text-sm font-extrabold text-white">{busy?"Creating account…":"Create account"}</button></>}</AuthCard>;}
export function useSignIn(){const[identifier,setIdentifier]=useState("");const[code,setCode]=useState("");return{isLoaded:true,signIn:{create:async(input:{strategy:string;identifier:string})=>{setIdentifier(input.identifier);return request("/api/auth/reset/request",{method:"POST",body:JSON.stringify({email:input.identifier})});},attemptFirstFactor:async(input:{strategy:string;code:string})=>{setCode(input.code);const result=await request("/api/auth/reset/verify",{method:"POST",body:JSON.stringify({email:identifier,code:input.code})});if(!result.valid)throw new Error("Invalid or expired verification code");return result;},resetPassword:async(input:{password:string;signOutOfOtherSessions?:boolean})=>{await request("/api/auth/reset/complete",{method:"POST",body:JSON.stringify({email:identifier,code,password:input.password})});return{status:"complete",createdSessionId:"local"};}},setActive:async()=>undefined};}
