import { type ReactNode, useEffect, useMemo, useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { useClerk, useUser } from '@clerk/react';
import { getGetCurrentWorkspaceQueryKey, getListAccessibleWorkspacesQueryKey, getListMerchantsQueryKey, getSelectedWorkspaceId, setSelectedWorkspaceId, useGetCurrentWorkspace, useListAccessibleWorkspaces, useListMerchants } from '@workspace/api-client-react';
import { ArrowLeft, BarChart3, Bell, BookOpen, BrainCircuit, Building2, ChevronDown, ChevronRight, CircleHelp, CreditCard, FileText, Gavel, Globe2, ImagePlus, KeyRound, Landmark, LayoutDashboard, LineChart, LogOut, Menu, Megaphone, PackageCheck, PanelLeftClose, PanelLeftOpen, Route, Search, Settings2, ShoppingCart, Store, Users, UsersRound, Warehouse, WalletCards, X } from 'lucide-react';
import { Link, useLocation } from 'wouter';
import { ErrorState, LoadingState, Logo } from '@/components/primitives';
import { HelpBot } from '@/components/help-bot';
import { initials } from '@/lib/format';

export { Logo };
const ADMIN_EMAIL = 'ifeoluwaolowu4@gmail.com';
const merchantGroups = [
  { label: 'Home', items: [{ href: '/dashboard', label: 'Overview', icon: LayoutDashboard }, { href: '/analytics', label: 'Analytics', icon: LineChart }, { href: '/guide', label: 'Learn & Guide', icon: BookOpen }] },
  { label: 'Sell', items: [{ href: '/store', label: 'Storefront', icon: Store }, { href: '/commerce-suite', label: 'Commerce Suite', icon: ShoppingCart }, { href: '/orders', label: 'Orders', icon: PackageCheck }, { href: '/customers', label: 'Customers', icon: UsersRound }, { href: '/invoices', label: 'Invoices', icon: FileText }, { href: '/pos', label: 'POS', icon: ShoppingCart }] },
  { label: 'Growth', items: [{ href: '/marketing', label: 'Marketing', icon: Megaphone }, { href: '/ad-studio', label: 'Ad Studio', icon: Megaphone }, { href: '/ai', label: 'AI Control Room', icon: BrainCircuit }, { href: '/general-store', label: 'General Store', icon: Globe2 }, { href: '/marketplace/manage', label: 'Marketplace', icon: Globe2 }, { href: '/auctions/manage', label: 'Auctions', icon: Gavel }] },
  { label: 'Operations', items: [{ href: '/inventory', label: 'Inventory', icon: Warehouse }, { href: '/suppliers', label: 'Suppliers', icon: Store }, { href: '/dropshipping', label: 'Fulfillment', icon: Route }, { href: '/finance', label: 'Finance', icon: WalletCards }, { href: '/withdrawals', label: 'Withdrawals', icon: WalletCards }, { href: '/ts-pay', label: 'TS Pay', icon: Landmark }] },
  { label: 'Account', items: [{ href: '/team', label: 'Team & Locations', icon: Users }, { href: '/media', label: 'Media Library', icon: ImagePlus }, { href: '/activity', label: 'Activity', icon: Bell }, { href: '/billing', label: 'Billing', icon: CreditCard }, { href: '/settings', label: 'Settings', icon: Settings2 }] },
];
const adminGroups = [{ label: 'Administration', items: [{ href: '/admin', label: 'Overview', icon: BarChart3 }, { href: '/admin/merchants', label: 'Merchants', icon: Users }, { href: '/admin/withdrawals', label: 'Withdrawals', icon: WalletCards }, { href: '/admin/integrations', label: 'Integrations', icon: KeyRound }] }];

export function AppShell({ children, admin = false }: { children: ReactNode; admin?: boolean }) {
  const [location, setLocation] = useLocation(); const [mobileOpen, setMobileOpen] = useState(false); const [collapsed, setCollapsed] = useState(false);
  const [expanded, setExpanded] = useState<Record<string, boolean>>({ Home: true, Sell: true, Growth: true, Operations: true, Account: false, Administration: true });
  const { user, isLoaded } = useUser(); const { signOut } = useClerk(); const queryClient = useQueryClient();
  const [selectedWorkspace, setSelectedWorkspace] = useState<string | null>(() => getSelectedWorkspaceId());
  const isMasterAdmin = user?.primaryEmailAddress?.emailAddress?.toLowerCase() === ADMIN_EMAIL && user.primaryEmailAddress.verification?.status === 'verified';
  const adminMerchants = useListMerchants({ query: { queryKey: getListMerchantsQueryKey(), enabled: admin && isLoaded && !!user, retry: false, staleTime: 60_000 } });
  const workspaces = useListAccessibleWorkspaces({ query: { queryKey: getListAccessibleWorkspacesQueryKey(), enabled: !admin && !isMasterAdmin && isLoaded && !!user, retry: false, staleTime: 60_000 } });
  const currentWorkspace = useGetCurrentWorkspace({ query: { queryKey: getGetCurrentWorkspaceQueryKey(), enabled: !admin && isLoaded && !!user && ((isMasterAdmin && Boolean(selectedWorkspace)) || (!isMasterAdmin && workspaces.isFetched && (Boolean(selectedWorkspace) || workspaces.data?.length === 0))), retry: false, staleTime: 60_000 } });
  const isAdminPreview = isMasterAdmin && !admin && Boolean(selectedWorkspace); const groups = admin ? adminGroups : merchantGroups;
  useEffect(() => { if (!isLoaded) return; setSelectedWorkspaceId(undefined, user?.id ?? null); setSelectedWorkspace(getSelectedWorkspaceId()); queryClient.clear(); }, [isLoaded, user?.id, queryClient]);
  useEffect(() => { if (admin || isMasterAdmin || !workspaces.data?.length) return; const available = new Set(workspaces.data.map(w => String(w.id))); const next = selectedWorkspace && available.has(selectedWorkspace) ? selectedWorkspace : String(workspaces.data[0]!.id); if (next !== selectedWorkspace) { setSelectedWorkspace(next); setSelectedWorkspaceId(next); queryClient.clear(); } }, [admin, isMasterAdmin, queryClient, selectedWorkspace, workspaces.data]);
  useEffect(() => { if (currentWorkspace.data?.id == null) return; const next = String(currentWorkspace.data.id); if (next !== selectedWorkspace) { setSelectedWorkspace(next); setSelectedWorkspaceId(next); } }, [currentWorkspace.data?.id, selectedWorkspace]);
  const displayName = admin ? 'Lunavo Operations' : currentWorkspace.data?.storeName || user?.fullName || 'Your workspace';
  const active = useMemo(() => groups.flatMap(g => g.items).sort((a,b) => b.href.length-a.href.length).find(item => location === item.href || location.startsWith(`${item.href}/`)), [groups, location]);
  const switchWorkspace = (id: number) => { if (id === currentWorkspace.data?.id) return; setSelectedWorkspace(String(id)); setSelectedWorkspaceId(id); queryClient.clear(); setLocation('/dashboard'); };
  const switchToMerchant = (id: number) => { setSelectedWorkspace(String(id)); setSelectedWorkspaceId(id); queryClient.clear(); setLocation('/dashboard'); };
  const returnToAdmin = () => { setSelectedWorkspace(null); setSelectedWorkspaceId(null); queryClient.clear(); setLocation('/admin'); };
  const switchToCustomer = () => { window.localStorage.setItem('lunavo-role', 'customer'); queryClient.clear(); setLocation('/general-store'); };
  const goBack = () => { if (window.history.length > 1 && document.referrer.startsWith(window.location.origin)) window.history.back(); else setLocation(admin ? '/admin' : '/dashboard'); };
  if (!isLoaded || (!admin && !isMasterAdmin && !workspaces.isFetched) || (!admin && isMasterAdmin && Boolean(selectedWorkspace) && !currentWorkspace.isFetched)) return <div className="min-h-[100dvh] bg-[#f5f7fa] p-6"><LoadingState label="Loading workspace" /></div>;
  if (!admin && workspaces.isError) return <div className="min-h-[100dvh] bg-[#f5f7fa] p-6"><ErrorState onRetry={() => void workspaces.refetch()} /></div>;
  if (!admin && currentWorkspace.isError) return <div className="min-h-[100dvh] bg-[#f5f7fa] p-6"><ErrorState onRetry={() => void currentWorkspace.refetch()} /></div>;
  if (!admin && (!currentWorkspace.isFetched || !currentWorkspace.data)) return <div className="min-h-[100dvh] bg-[#f5f7fa] p-6"><LoadingState label="Opening workspace" /></div>;
  return <div className="min-h-[100dvh] bg-[#f5f7fa] text-[#16253b]">
    <aside className={`fixed inset-y-0 left-0 z-50 flex flex-col border-r border-[#163a61] bg-[#061b34] text-white transition-all duration-200 ${collapsed?'w-[76px]':'w-[252px]'} ${mobileOpen?'translate-x-0':'-translate-x-full md:translate-x-0'}`}>
      <div className={`flex h-[68px] shrink-0 items-center border-b border-white/10 ${collapsed?'justify-center px-2':'justify-between px-5'}`}><div className="text-white">{!collapsed&&<Logo inverse/>}</div><button type="button" onClick={()=>setMobileOpen(false)} className="grid h-9 w-9 place-items-center rounded-lg text-blue-100/70 hover:bg-white/10 md:hidden" aria-label="Close navigation"><X className="h-5 w-5"/></button><button type="button" onClick={()=>setCollapsed(v=>!v)} className="hidden h-9 w-9 place-items-center rounded-lg text-blue-100/70 hover:bg-white/10 md:grid" aria-label={collapsed?'Expand navigation':'Collapse navigation'}>{collapsed?<PanelLeftOpen className="h-5 w-5"/>:<PanelLeftClose className="h-5 w-5"/>}</button></div>
      <div className="px-3 pt-3"><div className="rounded-xl border border-white/10 bg-white/[.055] p-3">{collapsed?<div className="mx-auto grid h-9 w-9 place-items-center rounded-lg bg-[#1c5fc4] text-xs font-black">{initials(displayName)}</div>:<><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-emerald-400"/><p className="text-[9px] font-bold uppercase tracking-[.14em] text-blue-100/55">{admin?'Master Admin':'Workspace'}</p></div><p className="mt-1 truncate text-sm font-bold">{displayName}</p>{admin&&<select aria-label="Switch merchant account" defaultValue="" onChange={e=>switchToMerchant(Number(e.target.value))} className="mt-2 w-full rounded-lg border border-white/10 bg-[#0b294b] px-2 py-2 text-xs font-semibold text-white"><option value="">View merchant…</option>{adminMerchants.data?.filter(m=>m.email.toLowerCase()!==ADMIN_EMAIL).map(m=><option key={m.id} value={m.id}>{m.storeName}</option>)}</select>}{!admin&&!isMasterAdmin&&(workspaces.data?.length??0)>1&&<select aria-label="Switch workspace" value={currentWorkspace.data?.id??''} onChange={e=>switchWorkspace(Number(e.target.value))} className="mt-2 w-full rounded-lg border border-white/10 bg-[#0b294b] px-2 py-2 text-xs font-semibold text-white"><option value="" disabled>Choose workspace</option>{workspaces.data?.map(w=><option key={w.id} value={w.id}>{w.storeName}</option>)}</select>}</>}</div></div>
      <nav className="mt-4 flex-1 overflow-y-auto px-3 pb-3" aria-label="Main navigation">{groups.map(group=>{const isOpen=expanded[group.label]??true;return <section key={group.label} className="mb-4">{!collapsed&&<button type="button" onClick={()=>setExpanded(v=>({...v,[group.label]:!isOpen}))} className="mb-1 flex w-full items-center justify-between px-2 py-1 text-[9px] font-bold uppercase tracking-[.16em] text-blue-100/45">{group.label}<ChevronDown className={`h-3.5 w-3.5 transition-transform ${isOpen?'':'-rotate-90'}`}/></button>}{(collapsed||isOpen)&&group.items.map(({href,label,icon:Icon})=>{const selected=location===href||location.startsWith(`${href}/`);return <Link key={href} href={href} onClick={()=>setMobileOpen(false)} title={collapsed?label:undefined} data-active={selected} className={`group mb-1 flex items-center gap-3 rounded-xl px-3 py-2.5 text-[12px] font-semibold transition ${selected?'bg-[#1859b8] text-white shadow-[0_8px_18px_rgba(16,85,180,.22)]':'text-blue-100/70 hover:bg-white/[.07] hover:text-white'} ${collapsed?'justify-center':''}`}><Icon className="h-[16px] w-[16px] shrink-0"/><span className={collapsed?'hidden':'flex-1'}>{label}</span>{selected&&!collapsed&&<ChevronRight className="h-3.5 w-3.5 opacity-70"/>}</Link>})}</section>})}</nav>
      <div className="shrink-0 border-t border-white/10 px-3 py-3">{isAdminPreview&&<button onClick={returnToAdmin} className="mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-[12px] font-semibold text-blue-100/70 hover:bg-white/[.07] hover:text-white"><ArrowLeft className="h-[16px] w-[16px]"/><span className={collapsed?'hidden':''}>Return to admin</span></button>}<Link href="/" className="mb-1 flex items-center gap-3 rounded-xl px-3 py-2.5 text-[12px] font-semibold text-blue-100/70 hover:bg-white/[.07] hover:text-white"><Building2 className="h-[16px] w-[16px]"/><span className={collapsed?'hidden':''}>Public site</span></Link>{!admin&&<button onClick={switchToCustomer} className="mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-[12px] font-semibold text-blue-100/70 hover:bg-white/[.07] hover:text-white"><ShoppingCart className="h-[16px] w-[16px]"/><span className={collapsed?'hidden':''}>Customer view</span></button>}<button onClick={()=>signOut({redirectUrl:'/'})} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-[12px] font-semibold text-blue-100/70 hover:bg-white/[.07] hover:text-white"><LogOut className="h-[16px] w-[16px]"/><span className={collapsed?'hidden':''}>Sign out</span></button></div>
    </aside>
    {mobileOpen&&<button className="fixed inset-0 z-40 bg-black/40 backdrop-blur-sm md:hidden" onClick={()=>setMobileOpen(false)} aria-label="Close navigation"/>}
    <main className={`min-h-[100dvh] transition-[padding] duration-200 ${collapsed?'md:pl-[76px]':'md:pl-[252px]'}`}>
      <header className="sticky top-0 z-30 flex h-[68px] items-center justify-between border-b border-[#dfe5ec] bg-white/95 px-4 shadow-[0_2px_14px_rgba(15,31,48,.03)] backdrop-blur-xl sm:px-6 lg:px-8"><div className="flex min-w-0 flex-1 items-center gap-3"><button type="button" onClick={()=>setMobileOpen(true)} className="grid h-10 w-10 place-items-center rounded-xl border border-[#dfe5ec] bg-white md:hidden" aria-label="Open navigation"><Menu className="h-5 w-5"/></button><button type="button" onClick={goBack} className="hidden h-9 items-center gap-2 rounded-lg px-2 text-xs font-bold text-[#7b899d] hover:bg-[#f1f4f8] sm:inline-flex"><ArrowLeft className="h-4 w-4"/>Back</button><div className="hidden w-full max-w-[610px] lg:flex"><label className="flex h-10 w-full items-center gap-2 rounded-xl border border-[#dfe5ec] bg-[#f8fafc] px-3 text-[#8a97a9] focus-within:border-[#9cb7df] focus-within:bg-white"><Search className="h-4 w-4 shrink-0"/><input aria-label="Search anything" placeholder="Search anything… (products, orders, customers, AI...)" className="min-w-0 flex-1 bg-transparent text-xs font-medium text-[#253650] outline-none placeholder:text-[#9aa7b8]"/><kbd className="rounded-md border border-[#dfe5ec] bg-white px-1.5 py-0.5 text-[9px] font-bold text-[#94a0b0]">⌘ K</kbd></label></div><div className="min-w-0 lg:hidden"><p className="truncate text-sm font-black text-[#17273d]">{active?.label??(admin?'Admin':'Overview')}</p><p className="hidden truncate text-[10px] text-[#7c8b9e] sm:block">{admin?'Lunavo platform administration':displayName}</p></div></div><div className="flex items-center gap-2"><div className="hidden items-center gap-2 border-r border-[#e2e7ed] pr-3 sm:flex"><button type="button" onClick={()=>setLocation('/activity')} className="relative grid h-9 w-9 place-items-center rounded-lg text-[#53647b] hover:bg-[#f2f5f9]" aria-label="Notifications"><Bell className="h-4 w-4"/><span className="absolute right-1.5 top-1.5 h-1.5 w-1.5 rounded-full bg-[#e24b43]"/></button><button type="button" onClick={()=>setLocation('/guide')} className="grid h-9 w-9 place-items-center rounded-lg text-[#53647b] hover:bg-[#f2f5f9]" aria-label="Help"><CircleHelp className="h-4 w-4"/></button></div><div className="ml-1 flex items-center gap-2"><div className="grid h-9 w-9 place-items-center rounded-full bg-[#15365d] text-xs font-black text-white">{initials(user?.fullName||user?.primaryEmailAddress?.emailAddress)}</div><div className="hidden max-w-[150px] sm:block"><p className="truncate text-xs font-black text-[#1e2d43]">{user?.firstName||'Account'}</p><p className="truncate text-[10px] text-[#7c8b9e]">{admin?'Master Admin':'Merchant'}</p></div><ChevronDown className="hidden h-4 w-4 text-[#7b899d] sm:block"/></div></div></header>
      <div className="mx-auto w-full max-w-[1600px] px-4 py-5 sm:px-6 lg:px-8 lg:py-7">{children}</div>
    </main><HelpBot/>
  </div>;
}

export function PublicHeader() {
  const chooseMerchantProfile=()=>window.localStorage.setItem('lunavo-role','merchant');
  return <header className="sticky top-0 z-30 flex min-h-[68px] items-center justify-between border-b border-border bg-background/90 px-4 backdrop-blur-xl sm:px-6 lg:px-10"><Link href="/" data-testid="link-public-logo"><Logo/></Link><nav className="flex items-center gap-1.5" aria-label="Public navigation"><Link href="/general-store" className="hidden rounded-lg px-3 py-2 text-sm font-semibold text-muted-foreground hover:bg-muted hover:text-foreground sm:inline-flex">Store</Link><Link href="/auctions" className="hidden rounded-lg px-3 py-2 text-sm font-semibold text-muted-foreground hover:bg-muted hover:text-foreground md:inline-flex">Auctions</Link><Link href="/leaderboard" className="hidden rounded-lg px-3 py-2 text-sm font-semibold text-muted-foreground hover:bg-muted hover:text-foreground lg:inline-flex">Leaderboard</Link><Link href="/dashboard" onClick={chooseMerchantProfile} className="hidden rounded-lg px-3 py-2 text-sm font-semibold text-muted-foreground hover:bg-muted hover:text-foreground sm:inline-flex">Merchant</Link><Link href="/sign-in" className="rounded-lg px-3 py-2 text-sm font-semibold text-muted-foreground hover:bg-muted hover:text-foreground">Sign in</Link><Link href="/sign-up" className="rounded-lg bg-primary px-4 py-2.5 text-sm font-extrabold text-primary-foreground shadow-sm hover:opacity-90">Get started</Link></nav></header>;
}