import type { StoreSection } from '@/lib/assistant-types';

type ProductCard = { id: number; title: string; imageUrl?: string | null; sellingPrice?: number | null; currency?: string | null };

type Props = { section: StoreSection; products?: ProductCard[] };

export function StorefrontSection({ section, products = [] }: Props) {
  if (!section.visible) return null;
  const s = section.settings;
  const title = typeof s.title === 'string' ? s.title : '';
  const subtitle = typeof s.subtitle === 'string' ? s.subtitle : '';
  const imageUrl = typeof s.imageUrl === 'string' ? s.imageUrl : '';
  const buttonText = typeof s.buttonText === 'string' ? s.buttonText : 'Shop now';

  switch (section.type) {
    case 'announcement': return <div className="bg-[#182333] px-4 py-2 text-center text-xs font-semibold text-white">{title || 'Welcome to our store'}</div>;
    case 'header': return <header className="sticky top-0 z-20 border-b border-[#e7e1d6] bg-white/95 px-5 py-4 backdrop-blur"><div className="mx-auto flex max-w-[1280px] items-center justify-between gap-6"><strong className="text-xl font-black tracking-[-.04em]">{title || 'Your Store'}</strong><nav className="hidden gap-5 text-sm font-semibold md:flex"><a href="#shop">Shop</a><a href="#about">About</a><a href="#contact">Contact</a></nav><button className="rounded-full border border-[#d9d2c4] px-4 py-2 text-xs font-bold">Cart</button></div></header>;
    case 'hero': return <section className="relative overflow-hidden bg-[#f5f1e9]"><div className="mx-auto grid max-w-[1280px] items-center gap-10 px-6 py-16 md:grid-cols-2 md:px-10 lg:py-24"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[#a2772e]">{subtitle || 'Discover something worth keeping'}</p><h1 className="mt-4 max-w-xl text-4xl font-black leading-[.96] tracking-[-.065em] md:text-6xl">{title || 'A storefront built around your brand.'}</h1><p className="mt-5 max-w-lg text-base leading-7 text-[#5d6670]">{typeof s.body === 'string' ? s.body : 'Beautiful products, clear value, and a frictionless buying experience.'}</p><a href="#shop" className="mt-7 inline-flex rounded-full bg-[#182333] px-6 py-3 text-sm font-extrabold text-white">{buttonText}</a></div>{imageUrl?<img src={imageUrl} alt={typeof s.imageAlt === 'string' ? s.imageAlt : ''} className="aspect-[4/3] w-full rounded-[2rem] object-cover shadow-2xl"/>:<div className="aspect-[4/3] rounded-[2rem] bg-[#ded7c9]"/>}</div></section>;
    case 'product_grid': case 'featured_collection': return <section id="shop" className="mx-auto max-w-[1280px] px-6 py-14 md:px-10"><div className="max-w-2xl"><h2 className="text-3xl font-black tracking-[-.05em]">{title || 'Featured products'}</h2><p className="mt-2 text-sm leading-6 text-[#697687]">{subtitle || 'Shop the collection.'}</p></div><div className="mt-8 grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-4">{products.slice(0,8).map(product=><article key={product.id} className="group"><div className="aspect-square overflow-hidden rounded-2xl bg-[#f1ede4]">{product.imageUrl?<img src={product.imageUrl} alt={product.title} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/>:<div className="h-full w-full"/>}</div><h3 className="mt-3 text-sm font-bold">{product.title}</h3><p className="mt-1 text-sm text-[#697687]">{product.sellingPrice ?? ''} {product.currency ?? ''}</p></article>)}</div></section>;
    case 'image_with_text': case 'story': return <section id="about" className="mx-auto grid max-w-[1280px] gap-10 px-6 py-14 md:grid-cols-2 md:px-10"><div className="overflow-hidden rounded-[2rem] bg-[#ede8de]">{imageUrl&&<img src={imageUrl} alt={typeof s.imageAlt === 'string' ? s.imageAlt : ''} className="h-full min-h-[360px] w-full object-cover"/>}</div><div className="self-center"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#a2772e]">{subtitle}</p><h2 className="mt-3 text-3xl font-black tracking-[-.05em]">{title || 'Why customers choose us'}</h2><p className="mt-4 text-sm leading-7 text-[#697687]">{typeof s.body === 'string' ? s.body : ''}</p></div></section>;
    case 'benefits': return <section className="border-y border-[#e7e1d6] bg-[#fbfaf6] px-6 py-10"><div className="mx-auto grid max-w-[1280px] gap-4 sm:grid-cols-3">{(['Secure checkout','Fast fulfilment','Human support'] as const).map(v=><div key={v} className="rounded-2xl bg-white p-5 text-center shadow-sm"><p className="text-sm font-extrabold">{v}</p></div>)}</div></section>;
    case 'newsletter': return <section className="mx-auto max-w-[900px] px-6 py-16 text-center"><h2 className="text-3xl font-black tracking-[-.05em]">{title || 'Stay in the loop'}</h2><p className="mt-2 text-sm text-[#697687]">{subtitle || 'Get new products and offers.'}</p><div className="mx-auto mt-6 flex max-w-lg gap-2"><input className="h-12 min-w-0 flex-1 rounded-full border border-[#d9d2c4] px-5" placeholder="Email address"/><button className="rounded-full bg-[#182333] px-5 text-sm font-bold text-white">Subscribe</button></div></section>;
    case 'footer': return <footer id="contact" className="bg-[#182333] px-6 py-12 text-white"><div className="mx-auto max-w-[1280px]"><strong className="text-xl">{title || 'Your Store'}</strong><p className="mt-2 max-w-md text-sm leading-6 text-[#b9c1ca]">{subtitle || 'Built with TS Commerce.'}</p></div></footer>;
    default: return <section className="mx-auto max-w-[1280px] px-6 py-12"><h2 className="text-2xl font-black">{title}</h2>{subtitle&&<p className="mt-2 text-sm text-[#697687]">{subtitle}</p>}</section>;
  }
}
