/**
 * TS Commerce completeness registry.
 *
 * This is a product contract, not a claim that every worker/UI is already
 * deployed. Each capability must remain usable without a third-party API key.
 * Flutterwave is the deliberate external payment rail exception.
 */
export const COMMERCE_CAPABILITIES = [
  // Storefront experience
  "responsive-storefront",
  "mobile-first-checkout",
  "guest-checkout",
  "customer-accounts",
  "wishlist",
  "recently-viewed",
  "product-compare",
  "product-q-and-a",
  "reviews-and-rating",
  "back-in-stock-alerts",
  "price-drop-alerts",
  "sticky-add-to-cart",
  "quick-view",
  "collections",
  "faceted-search",
  "smart-search-suggestions",
  "product-recommendations",
  "bundles-and-upsells",
  "trust-and-social-proof",
  "accessibility-controls",
  "seo-metadata-and-structured-data",
  "sitemap-and-robots-management",
  "localized-storefront-content",

  // Catalog and inventory
  "bulk-product-editor",
  "variant-and-option-management",
  "sku-and-barcode-management",
  "inventory-reservations",
  "low-stock-rules",
  "stockout-forecasting",
  "purchase-order-workflows",
  "bundled-inventory",
  "inventory-adjustment-audit",
  "catalog-deduplication",
  "catalog-quality-scoring",
  "supplier-url-import",
  "supplier-data-mapping",
  "landed-cost-calculation",

  // Orders and fulfillment
  "order-state-machine",
  "split-fulfillment",
  "partial-fulfillment",
  "returns-and-rma",
  "refund-workflows",
  "shipping-rules",
  "pickup-and-local-delivery",
  "international-shipping",
  "tracking-events",
  "fulfillment-exception-center",
  "packing-slip-and-invoice-generation",
  "order-timeline",

  // Growth and marketing
  "abandoned-cart-recovery",
  "customer-segmentation",
  "loyalty-programs",
  "discount-engine",
  "quantity-breaks",
  "bogo-promotions",
  "free-shipping-thresholds",
  "campaign-planner",
  "email-campaigns",
  "onsite-personalization",
  "a-b-experiments",
  "attribution-modeling",
  "referral-program",

  // Self-hosted intelligence
  "local-ai-command-center",
  "local-product-research",
  "local-pricing-brain",
  "local-demand-forecasting",
  "local-customer-support-brain",
  "local-seo-writer",
  "local-ad-copywriter",
  "local-image-generation",
  "local-image-editing",
  "local-video-generation",
  "seamless-video-stitching",
  "creative-variation-engine",
  "business-simulator",
  "commerce-time-machine",
  "profit-firewall",
  "store-genome",
  "catalog-doctor",
  "supplier-twin",
  "failure-predictor",
  "decision-replay",
  "experiment-orchestrator",
  "business-autopilot",
  "demand-gravity-map",
  "margin-escape-room",
  "autonomous-incident-center",

  // Payments and finance
  "ts-pay-payment-sessions",
  "ts-pay-internal-ledger",
  "provider-webhook-verification",
  "provider-reconciliation",
  "duplicate-payment-protection",
  "refund-and-dispute-ledgering",
  "merchant-payout-requests",
  "settlement-currency-tracking",
  "provider-fee-tracking",
  "platform-fee-tracking",
  "merchant-net-calculation",
  "subscription-billing",
  "subscription-earnings-offset",
  "payment-risk-rules",
  "financial-audit-log",

  // Security and compliance
  "self-hosted-authentication",
  "two-factor-authentication",
  "session-and-device-management",
  "login-alerts",
  "suspicious-login-detection",
  "rate-limiting",
  "brute-force-protection",
  "role-based-access-control",
  "permission-scopes",
  "admin-audit-log",
  "merchant-audit-log",
  "kyc-gating-before-payout",
  "privacy-controls",
  "data-export-and-deletion",
  "retention-controls",
  "consent-records",
  "security-event-center",

  // Operations and developer platform
  "notification-center",
  "email-queue",
  "sms-ready-notification-abstraction",
  "automation-workflows",
  "scheduled-jobs",
  "background-job-retries",
  "idempotency-keys",
  "dead-letter-queue",
  "health-monitoring",
  "backup-and-restore",
  "object-storage-abstraction",
  "developer-api",
  "api-key-scopes",
  "api-key-rotation",
  "webhook-secrets",
  "webhook-replay-tools",
  "api-usage-logs",
  "rate-limit-management",
  "import-export-tools",
  "csv-data-tools",
  "feature-flags",
  "maintenance-mode",
  "incident-mode",
  "realtime-event-stream",

  // Marketplace and multi-store
  "unlimited-merchant-stores",
  "store-isolation",
  "marketplace-opt-in",
  "marketplace-product-listing-fees",
  "marketplace-monthly-fee",
  "merchant-marketplace-controls",
  "multi-currency-pricing",
  "country-aware-tax-rules",
  "multi-timezone-store-settings",
  "custom-domains",
  "theme-system",
  "brand-kit",
  "white-label-ready-storefront",
] as const;

export type CommerceCapability = (typeof COMMERCE_CAPABILITIES)[number];

export const SELF_HOSTED_CAPABILITY_POLICY = {
  thirdPartyApiKeysRequired: false,
  externalPaymentRail: "flutterwave",
  aiMayMoveMoney: false,
  aiMayConfirmPayment: false,
  aiMayEditLedger: false,
  aiMayBypassPermissions: false,
} as const;

export function hasCommerceCapability(capability: string): capability is CommerceCapability {
  return (COMMERCE_CAPABILITIES as readonly string[]).includes(capability);
}
