import { sql } from "drizzle-orm";
import { db } from "@workspace/db";
const INTERVAL_MS=60_000;const BATCH_SIZE=500;let running=false;
async function createNotification(row:any){await db.execute(sql`INSERT INTO customer_notifications(merchant_id,visitor_key,notification_type,entity_type,entity_id,title,body,deep_link,dedupe_key) VALUES(${Number(row.merchant_id)},${String(row.visitor_key)},${String(row.notification_type)},${String(row.entity_type)},${String(row.entity_id)},${String(row.title)},${String(row.body)},${row.deep_link?String(row.deep_link):null},${String(row.dedupe_key)}) ON CONFLICT(merchant_id,dedupe_key) DO NOTHING`);}
export async function runCustomerAlertSweep(){if(running)return;running=true;try{
 const prices=await db.execute(sql`SELECT w.id,w.merchant_id,w.visitor_key,w.supplier_product_id,w.target_price,w.currency,p.title FROM customer_price_watches w JOIN supplier_products p ON p.id=w.supplier_product_id WHERE w.active=true AND p.status='active' AND p.selling_price IS NOT NULL AND p.currency=w.currency AND p.selling_price::numeric<=w.target_price::numeric AND (w.last_notified_at IS NULL OR w.last_notified_at<now()-interval '24 hours') ORDER BY w.updated_at ASC LIMIT ${BATCH_SIZE}`);
 for(const row of prices.rows as any[]){await createNotification({merchant_id:row.merchant_id,visitor_key:row.visitor_key,notification_type:"price_watch",entity_type:"product",entity_id:String(row.supplier_product_id),title:"Price target reached",body:`${row.title} is now at or below your target price of ${row.currency} ${Number(row.target_price).toFixed(2)}.`,deep_link:`/store/${row.merchant_id}?productId=${row.supplier_product_id}`,dedupe_key:`price-watch:${row.id}:${new Date().toISOString().slice(0,10)}`});await db.execute(sql`UPDATE customer_price_watches SET last_notified_at=now(),updated_at=now() WHERE id=${row.id} AND active=true`);}
 const searches=await db.execute(sql`SELECT s.id,s.merchant_id,s.visitor_key,s.query,p.id product_id,p.title FROM customer_saved_searches s JOIN supplier_products p ON p.merchant_id=s.merchant_id AND p.status='active' WHERE s.active=true AND (p.title ILIKE '%'||s.query||'%' OR COALESCE(p.description,'') ILIKE '%'||s.query||'%') AND p.updated_at>=now()-interval '24 hours' AND (s.last_notified_at IS NULL OR s.last_notified_at<now()-interval '24 hours') ORDER BY s.updated_at ASC LIMIT ${BATCH_SIZE}`);
 for(const row of searches.rows as any[]){await createNotification({merchant_id:row.merchant_id,visitor_key:row.visitor_key,notification_type:"saved_search",entity_type:"product",entity_id:String(row.product_id),title:"New match for your saved search",body:`${row.title} matches your saved search "${row.query}".`,deep_link:`/store/${row.merchant_id}?productId=${row.product_id}`,dedupe_key:`saved-search:${row.id}:${row.product_id}`});await db.execute(sql`UPDATE customer_saved_searches SET last_notified_at=now(),updated_at=now() WHERE id=${row.id} AND active=true`);}
}finally{running=false;}}
export function startCustomerAlertWorker(){void runCustomerAlertSweep();const timer=setInterval(()=>void runCustomerAlertSweep(),INTERVAL_MS);timer.unref?.();return()=>clearInterval(timer);}