import { createHash, randomBytes, randomUUID, scrypt as nodeScrypt, timingSafeEqual } from "node:crypto";
import { promisify } from "node:util";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { createTransport } from "nodemailer";
import type { Request, Response, NextFunction } from "express";
import { sql } from "drizzle-orm";
import { db } from "@workspace/db";

const scrypt=promisify(nodeScrypt);export const COOKIE="lunavo_session";const SESSION_DAYS=30;
export type LocalAuthUser={id:string;email:string;username:string;firstName:string;lastName:string;role:string};type AuthRequest=Request&{auth?:{userId:string|null};localUser?:LocalAuthUser};
function sessionHash(token:string){return createHash("sha256").update(token).digest("hex");}
async function passwordHash(password:string){const salt=randomBytes(16);const key=Buffer.from(await scrypt(password,salt,64));return `${salt.toString("base64url")}.${key.toString("base64url")}`;}
async function verifyPassword(password:string,encoded:string){const[saltEncoded,hashEncoded]=encoded.split(".");if(!saltEncoded||!hashEncoded)return false;const salt=Buffer.from(saltEncoded,"base64url");const expected=Buffer.from(hashEncoded,"base64url");const actual=Buffer.from(await scrypt(password,salt,expected.length));return actual.length===expected.length&&timingSafeEqual(actual,expected);}
function readCookie(req:Request){const header=req.headers.cookie;if(!header)return null;for(const pair of header.split(";")){const[name,...value]=pair.trim().split("=");if(name===COOKIE)return decodeURIComponent(value.join("="));}return null;}
export async function authenticateRequest(req:AuthRequest,_res:Response,next:NextFunction){try{const token=readCookie(req);if(!token){req.auth={userId:null};next();return;}const digest=sessionHash(token);const result=await db.execute(sql`SELECT u.id,u.email,u.username,u.first_name,u.last_name,u.role FROM local_auth_sessions s INNER JOIN local_auth_users u ON u.id=s.user_id WHERE s.token_hash=${digest} AND s.expires_at>now() LIMIT 1`);const row=result.rows[0] as any;if(!row){req.auth={userId:null};next();return;}req.auth={userId:String(row.id)};req.localUser={id:String(row.id),email:String(row.email),username:String(row.username),firstName:String(row.first_name),lastName:String(row.last_name),role:String(row.role)};void db.execute(sql`UPDATE local_auth_sessions SET last_seen_at=now() WHERE token_hash=${digest}`);next();}catch(error){next(error);}}
export async function createLocalSession(userId:string){const token=randomBytes(48).toString("base64url");await db.execute(sql`INSERT INTO local_auth_sessions (id,user_id,token_hash,expires_at) VALUES (${randomUUID()},${userId},${sessionHash(token)},now()+${SESSION_DAYS} * interval '1 day')`);return token;}
export function setSessionCookie(res:Response,token:string){const secure=process.env.NODE_ENV==="production";res.setHeader("Set-Cookie",`${COOKIE}=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${SESSION_DAYS*24*60*60}${secure?"; Secure":""}`);}
export function clearSessionCookie(res:Response){const secure=process.env.NODE_ENV==="production";res.setHeader("Set-Cookie",`${COOKIE}=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0${secure?"; Secure":""}`);}
export async function revokeCurrentSession(req:Request){const token=readCookie(req);if(token)await db.execute(sql`DELETE FROM local_auth_sessions WHERE token_hash=${sessionHash(token)}`);}
export async function registerLocalUser(input:{email:string;username:string;firstName:string;lastName:string;password:string;role?:string}){const email=input.email.trim().toLowerCase();const username=input.username.trim().toLowerCase();if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email))throw new Error("Enter a valid email address");if(!/^[a-z0-9_.-]{3,64}$/.test(username))throw new Error("Username must be 3–64 letters, numbers, dots, dashes, or underscores");if(input.password.length<8)throw new Error("Password must be at least 8 characters");const id=randomUUID();const hash=await passwordHash(input.password);await db.transaction(async tx=>{await tx.execute(sql`INSERT INTO local_auth_users (id,email,username,first_name,last_name,password_hash,role) VALUES (${id},${email},${username},${input.firstName.trim()},${input.lastName.trim()},${hash},${input.role??"merchant"})`);await tx.execute(sql`INSERT INTO merchants (local_auth_user_id,clerk_user_id,name,email,store_name,status) VALUES (${id},${id},${`${input.firstName} ${input.lastName}`.trim()},${email},${`${input.firstName}'s Store`.slice(0,120)},'active')`);await tx.execute(sql`INSERT INTO subscriptions (merchant_id,amount_due,amount_paid,earnings_held,status,payment_method) SELECT id,30,0,0,'pending',NULL FROM merchants WHERE local_auth_user_id=${id}`);});return{id,email,username,firstName:input.firstName.trim(),lastName:input.lastName.trim(),role:input.role??"merchant"};}
export async function verifyLocalCredentials(email:string,password:string){const result=await db.execute(sql`SELECT id,email,username,first_name,last_name,password_hash,role FROM local_auth_users WHERE lower(email)=lower(${email.trim()}) LIMIT 1`);const row=result.rows[0] as any;if(!row||!(await verifyPassword(password,String(row.password_hash))))throw new Error("Invalid email or password");return{id:String(row.id),email:String(row.email),username:String(row.username),firstName:String(row.first_name),lastName:String(row.last_name),role:String(row.role)};}
async function deliverResetCode(email:string,code:string){const from=process.env.SMTP_FROM?.trim()||process.env.LUNAVO_LOCAL_MAIL_FROM?.trim()||"no-reply@lunavo.local";const subject="Lunavo password reset code";const text=`Your Lunavo password reset code is ${code}. It expires in 15 minutes. If you did not request this, ignore this message.`;const host=process.env.SMTP_HOST?.trim();if(host){const port=Number(process.env.SMTP_PORT||587);const transport=createTransport({host,port,secure:port===465,auth:process.env.SMTP_USER?{user:process.env.SMTP_USER,password:process.env.SMTP_PASSWORD||""}:undefined});await transport.sendMail({from,to:email,subject,text});return;}const root=process.env.LUNAVO_LOCAL_OBJECT_STORAGE_PATH?.trim()||"./data/lunavo";const outbox=path.join(root,"mail-outbox");await mkdir(outbox,{recursive:true});await writeFile(path.join(outbox,`${Date.now()}-${randomUUID()}.eml`),`From: ${from}\nTo: ${email}\nSubject: ${subject}\n\n${text}\n`,{mode:0o600});}
export async function requestPasswordReset(email:string){const result=await db.execute(sql`SELECT id FROM local_auth_users WHERE lower(email)=lower(${email.trim()}) LIMIT 1`);const user=result.rows[0] as {id?:string}|undefined;const generic={accepted:true};if(!user?.id)return generic;const code=String(Math.floor(100000+Math.random()*900000));await db.execute(sql`UPDATE local_auth_password_resets SET consumed_at=now() WHERE user_id=${user.id} AND consumed_at IS NULL`);await db.execute(sql`INSERT INTO local_auth_password_resets (id,user_id,code_hash,expires_at) VALUES (${randomUUID()},${user.id},${sessionHash(code)},now()+interval '15 minutes')`);await deliverResetCode(email.trim().toLowerCase(),code);return generic;}
export async function verifyPasswordResetCode(email:string,code:string){const result=await db.execute(sql`SELECT r.id,r.user_id,r.code_hash,r.attempts FROM local_auth_password_resets r INNER JOIN local_auth_users u ON u.id=r.user_id WHERE lower(u.email)=lower(${email.trim()}) AND r.consumed_at IS NULL AND r.expires_at>now() ORDER BY r.created_at DESC LIMIT 1`);const row=result.rows[0] as any;if(!row||Number(row.attempts)>=5)return false;const valid=timingSafeEqual(Buffer.from(sessionHash(code.trim())),Buffer.from(String(row.code_hash)));if(!valid)await db.execute(sql`UPDATE local_auth_password_resets SET attempts=attempts+1 WHERE id=${row.id}`);return valid;}
export async function completePasswordReset(email:string,code:string,newPassword:string){if(newPassword.length<8)throw new Error("Password must be at least 8 characters");const verified=await verifyPasswordResetCode(email,code);if(!verified)throw new Error("Invalid or expired verification code");const hash=await passwordHash(newPassword);const updated=await db.execute(sql`UPDATE local_auth_users SET password_hash=${hash},updated_at=now() WHERE lower(email)=lower(${email.trim()}) RETURNING id`);const user=updated.rows[0] as {id?:string}|undefined;if(!user?.id)throw new Error("Account not found");await db.execute(sql`UPDATE local_auth_password_resets SET consumed_at=now() WHERE user_id=${user.id} AND consumed_at IS NULL`);await db.execute(sql`DELETE FROM local_auth_sessions WHERE user_id=${user.id}`);return user.id;}
