import { useEffect, useMemo, useRef, useState } from "react";
import { CheckCircle2, Download, ExternalLink, Film, RefreshCw, Send, Share2, Unplug, UploadCloud, WandSparkles } from "lucide-react";
import { customFetch, useListSupplierProducts } from "@workspace/api-client-react";
import { AppShell } from "@/components/app-shell";
import { Badge, Button, ErrorState, LoadingState, Notice, SectionHeading } from "@/components/primitives";

type Product={id:number;title:string;imageUrl:string|null};
type Creative={id:string;platform:string;aspectRatio:string;durationSeconds:number;title:string;caption:string|null;status:string};
type Campaign={id:string;status:string};
type CustomMedia={id:string;filename:string;mimeType:string;mediaType:string;byteSize:number;createdAt:string};
type Provider={id:string|null;provider:string;label:string;configured:boolean;connected:boolean;accountId:string|null;accountName:string|null;status:string};
type Job={id:string;provider:string;caption:string|null;status:string;externalPostId:string|null;errorMessage:string|null;createdAt:string;publishedAt:string|null};

export default function AdStudio(){
 const productsQuery=useListSupplierProducts(); const inputRef=useRef<HTMLInputElement>(null);
 const [products,setProducts]=useState<Product[]>([]); const [campaigns,setCampaigns]=useState<Campaign[]>([]); const [creatives,setCreatives]=useState<Creative[]>([]); const [customMedia,setCustomMedia]=useState<CustomMedia[]>([]); const [providers,setProviders]=useState<Provider[]>([]); const [jobs,setJobs]=useState<Job[]>([]);
 const [productId,setProductId]=useState(""); const [goal,setGoal]=useState("sales"); const [audience,setAudience]=useState(""); const [offer,setOffer]=useState(""); const [customPrompt,setCustomPrompt]=useState(""); const [socialCaption,setSocialCaption]=useState(""); const [selectedCreative,setSelectedCreative]=useState(""); const [selectedProviders,setSelectedProviders]=useState<string[]>([]); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [stitchIds,setStitchIds]=useState<string[]>([]); const [stitching,setStitching]=useState(false);
 const load=async()=>{setLoading(true);try{const [ads,p,j]=await Promise.all([customFetch<{campaigns:Campaign[];creatives:Creative[];customMedia:CustomMedia[]}>('/api/ads/generator/campaigns'),customFetch<Provider[]>('/api/social/providers'),customFetch<Job[]>('/api/social/publish-jobs')]);const list=(productsQuery.data??[]) as Product[];setProducts(list);setCampaigns(ads.campaigns??[]);setCreatives(ads.creatives??[]);setCustomMedia(ads.customMedia??[]);setProviders(p??[]);setJobs(j??[]);if(!productId&&list[0])setProductId(String(list[0].id));}catch(e){setMessage(e instanceof Error?e.message:'Creative workspace could not be loaded.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[productsQuery.data]); const selected=useMemo(()=>products.find(p=>String(p.id)===productId)??null,[products,productId]); const completed=useMemo(()=>creatives.filter(c=>c.status==='completed'),[creatives]); const chosenCreative=useMemo(()=>creatives.find(c=>c.id===selectedCreative)??null,[creatives,selectedCreative]);
 const generate=async()=>{if(!selected){setMessage('Choose a catalog product first.');return}setBusy(true);try{await customFetch('/api/ads/generator/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({productId:selected.id,goal,audience,offer,customPrompt})});setMessage('Fresh ad variants generated with an audio bed.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Video generation failed.')}finally{setBusy(false)}};
 const generateStore=async()=>{setBusy(true);try{const r=await customFetch<{processed:number}>('/api/ads/generator/generate-store',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({limit:10,goal,audience,offer,customPrompt})});setMessage(`${r.processed} product(s) processed into ad packs.`);await load()}catch(e){setMessage(e instanceof Error?e.message:'Store-wide generation failed.')}finally{setBusy(false)}};
 const upload=async(file:File|null)=>{if(!file)return;const allowed=['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm'];if(!allowed.includes(file.type)||file.size>25*1024*1024){setMessage('Upload a JPEG, PNG, WebP, GIF, MP4 or WebM file up to 25 MB.');return}setBusy(true);try{const dataUrl=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>typeof reader.result==='string'?resolve(reader.result):reject(new Error('Could not read file'));reader.onerror=()=>reject(reader.error??new Error('Could not read file'));reader.readAsDataURL(file)});const r=await customFetch<{asset:CustomMedia}>('/api/ads/media',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({media:{filename:file.name,mimeType:file.type,data:dataUrl}})});setCustomMedia(v=>[r.asset,...v]);setMessage('Custom campaign media saved separately from your store.')}catch(e){setMessage(e instanceof Error?e.message:'Custom media upload failed.')}finally{setBusy(false)}};
 const stitch=async()=>{if(stitchIds.length<2){setMessage('Select at least two clips with the same aspect ratio.');return}setStitching(true);try{const r=await fetch('/api/ads/generator/stitch',{method:'POST',headers:{'content-type':'application/json'},credentials:'include',body:JSON.stringify({creativeIds:stitchIds})});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error||'Stitching failed')}const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='ts-commerce-long-ad.mp4';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);setMessage('Long-form ad exported with the generated audio bed.')}catch(e){setMessage(e instanceof Error?e.message:'Stitching failed')}finally{setStitching(false)}};
 const connect=async(provider:string)=>{try{const r=await customFetch<{authorizeUrl:string}>(`/api/social/connect/${provider}`);window.location.href=r.authorizeUrl}catch(e){setMessage(e instanceof Error?e.message:'Unable to start social connection.')}};
 const toggleProvider=(provider:string)=>setSelectedProviders(v=>v.includes(provider)?v.filter(x=>x!==provider):[...v,provider]);
 const publish=async()=>{if(!selectedProviders.length){setMessage('Select at least one connected social account.');return}if(!chosenCreative){setMessage('Select a completed generated creative first.');return}setBusy(true);try{const r=await customFetch<{results:Array<{provider:string,status:string}>;message:string}>('/api/social/publish',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({providers:selectedProviders,creativeId:chosenCreative.id,caption:socialCaption||chosenCreative.caption})});setMessage(r.message);await load()}catch(e){setMessage(e instanceof Error?e.message:'Publishing could not be queued.')}finally{setBusy(false)}};
 if(loading)return <AppShell><LoadingState label="Loading Creative Studio"/></AppShell>; if(!products.length)return <AppShell><ErrorState onRetry={()=>void load()}/></AppShell>;
 return <AppShell><div className="mx-auto max-w-[1240px]">
  <div className="flex flex-wrap items-end justify-between gap-5"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#a2772e]">Creative + Social Studio</p><h1 className="mt-2 text-4xl font-extrabold tracking-[-.07em]">Make it. Own it. Publish it.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#697687]">Use TS Commerce generation, add your own prompt, bring media from anywhere, download everything, then send one publish request to your connected channels.</p></div><Badge tone="success">No fake publish success</Badge></div>
  {message&&<div className="mt-6"><Notice title="Creative Studio">{message}</Notice></div>}
  <section className="mt-8 rounded-2xl border border-[#d9d2c4] bg-[#182333] p-6 text-[#f8f3e8] md:p-8"><div className="flex items-start gap-3"><WandSparkles className="mt-1 h-6 w-6 text-[#d6aa46]"/><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#d6aa46]">Creative brain</p><h2 className="mt-2 text-2xl font-extrabold">Control every input.</h2><p className="mt-2 text-sm leading-6 text-[#b8c2cc]">Product facts remain grounded in your real catalog. Your prompt is optional creative direction and never becomes fabricated proof.</p></div></div>
   <div className="mt-6 grid gap-4 lg:grid-cols-3"><label className="text-sm font-bold lg:col-span-2">Product<select value={productId} onChange={e=>setProductId(e.target.value)} className="mt-2 h-11 w-full rounded-lg border border-[#526376] bg-[#243344] px-3 text-[#f8f3e8]"><option value="">Choose product</option>{products.map(p=><option key={p.id} value={p.id}>{p.title}{p.imageUrl?'':' — missing image'}</option>)}</select></label><label className="text-sm font-bold">Goal<select value={goal} onChange={e=>setGoal(e.target.value)} className="mt-2 h-11 w-full rounded-lg border border-[#526376] bg-[#243344] px-3 text-[#f8f3e8]"><option value="sales">Sales</option><option value="traffic">Traffic</option><option value="awareness">Awareness</option></select></label></div>
   <div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm font-bold">Audience<input value={audience} onChange={e=>setAudience(e.target.value)} className="mt-2 h-11 w-full rounded-lg border border-[#526376] bg-[#243344] px-3 text-[#f8f3e8]"/></label><label className="text-sm font-bold">Offer context<input value={offer} onChange={e=>setOffer(e.target.value)} className="mt-2 h-11 w-full rounded-lg border border-[#526376] bg-[#243344] px-3 text-[#f8f3e8]"/></label></div>
   <label className="mt-4 block text-sm font-bold">My custom prompt<textarea value={customPrompt} onChange={e=>setCustomPrompt(e.target.value)} rows={4} placeholder="Describe exactly how you want the ad to feel, sound and flow." className="mt-2 w-full rounded-lg border border-[#526376] bg-[#243344] px-3 py-3 text-sm text-[#f8f3e8]"/></label>
   <div className="mt-5 flex flex-wrap gap-3"><Button onClick={generate} disabled={busy||!selected?.imageUrl} className="bg-[#d6aa46] text-[#182333]"><Film className="h-4 w-4"/>{busy?'Working…':'Generate this ad'}</Button><Button onClick={generateStore} disabled={busy} variant="secondary">Generate for 10 products</Button><Button onClick={()=>inputRef.current?.click()} disabled={busy} variant="secondary"><UploadCloud className="h-4 w-4"/>Bring my own image/video</Button><input ref={inputRef} type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm" className="hidden" onChange={e=>void upload(e.target.files?.[0]??null)}/></div>
  </section>
  <section className="mt-8"><SectionHeading eyebrow="Custom media" title="Assets outside your store" description="These are optional campaign assets and are kept separate from your catalog media."/><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{customMedia.map(m=><div key={m.id} className="rounded-xl border border-[#d9d2c4] bg-[#fbfaf6] p-4"><Badge>{m.mediaType}</Badge><p className="mt-2 truncate text-xs font-bold">{m.filename}</p><a href={`/api/ads/media/${m.id}/download`} className="mt-3 inline-flex items-center gap-2 text-xs font-extrabold text-[#8a6826] underline"><Download className="h-3.5 w-3.5"/>Download</a></div>)}</div></section>
  <section className="mt-8 rounded-2xl border border-[#d9d2c4] bg-[#fbfaf6] p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-[#a2772e]">Long-form studio</p><h2 className="mt-2 text-xl font-extrabold">Stitch your best clips</h2><p className="mt-1 text-xs leading-5 text-[#697687]">Select generated clips with the same ratio and export one longer MP4.</p></div><Button onClick={stitch} disabled={stitching||stitchIds.length<2}>{stitching?<><RefreshCw className="h-4 w-4 animate-spin"/>Stitching…</>:<>Stitch selected ({stitchIds.length})</>}</Button></div></section>
  <section className="mt-8"><SectionHeading eyebrow="Generated ads" title="Preview and download" description="Every generated MP4 contains the generated audio bed; download the original asset whenever you need it."/><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{completed.map(c=><article key={c.id} className={'overflow-hidden rounded-2xl border bg-[#fbfaf6] '+(selectedCreative===c.id?'border-[#a2772e]':'border-[#d9d2c4')}><button className="block w-full text-left" onClick={()=>{setSelectedCreative(c.id);setSocialCaption(c.caption??'')}}><div className="aspect-[9/14] bg-[#101923]"><video controls playsInline preload="metadata" src={`/api/ads/generator/creatives/${c.id}`} className="h-full w-full object-contain"/></div><div className="p-4"><div className="flex items-center justify-between gap-2"><Badge tone="success">{c.platform}</Badge>{selectedCreative===c.id&&<CheckCircle2 className="h-4 w-4 text-[#a2772e]"/>}</div><p className="mt-3 text-sm font-extrabold">{c.title}</p><p className="mt-2 line-clamp-3 text-xs leading-5 text-[#697687]">{c.caption}</p></div></button><div className="grid grid-cols-2 gap-2 p-4 pt-0"><label className="col-span-2 flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={stitchIds.includes(c.id)} onChange={e=>setStitchIds(v=>e.target.checked?[...new Set([...v,c.id])]:v.filter(id=>id!==c.id))}/>Use for long video</label><a href={`/api/ads/generator/creatives/${c.id}`} className="col-span-2 inline-flex items-center justify-center gap-2 rounded-xl bg-[#182333] px-3 py-2 text-xs font-extrabold text-[#f8f3e8]"><Download className="h-3.5 w-3.5"/>Download MP4</a></div></article>)}</div></section>
  <section className="mt-10 rounded-2xl border border-[#d9d2c4] bg-[#fbfaf6] p-6 md:p-8"><div className="flex items-start gap-3"><Share2 className="mt-1 h-6 w-6 text-[#a2772e]"/><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-[#a2772e]">One-click social publishing</p><h2 className="mt-2 text-2xl font-extrabold">Connect once, publish from here.</h2><p className="mt-2 text-sm leading-6 text-[#697687]">Connections are optional. A selected publish job never becomes “published” until the provider confirms success.</p></div></div>
    <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{providers.map(p=><div key={p.provider} className="rounded-xl border border-[#d9d2c4] bg-white p-4"><div className="flex items-center justify-between gap-2"><p className="font-extrabold">{p.label}</p><Badge tone={p.connected?'success':p.configured?'warning':'neutral'}>{p.connected?'Connected':p.configured?'Ready':'Not configured'}</Badge></div><p className="mt-2 text-xs text-[#697687]">{p.accountName||'No account connected'}</p><div className="mt-4">{p.connected?<><button onClick={()=>toggleProvider(p.provider)} className={'inline-flex w-full items-center justify-center gap-2 rounded-xl px-3 py-2 text-xs font-extrabold '+(selectedProviders.includes(p.provider)?'bg-[#d6aa46] text-[#182333]':'bg-[#182333] text-[#f8f3e8]')}><CheckCircle2 className="h-3.5 w-3.5"/>{selectedProviders.includes(p.provider)?'Selected':'Select'}</button><button onClick={()=>customFetch(`/api/social/connections/${p.id}`,{method:'DELETE'}).then(()=>void load()).catch(()=>setMessage('Disconnect failed.'))} disabled={!p.id} className="mt-2 inline-flex w-full items-center justify-center gap-2 rounded-xl border border-[#d9d2c4] px-3 py-2 text-xs font-extrabold text-[#697687]"><Unplug className="h-3.5 w-3.5"/>Disconnect</button></>:<button onClick={()=>void connect(p.provider)} disabled={!p.configured} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#182333] px-3 py-2 text-xs font-extrabold text-[#f8f3e8] disabled:opacity-40"><ExternalLink className="h-3.5 w-3.5"/>Connect</button>}</div></div>)}</div>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_.9fr]"><div className="rounded-xl border border-[#d9d2c4] bg-white p-5"><p className="text-sm font-extrabold">Publish caption</p><textarea value={socialCaption} onChange={e=>setSocialCaption(e.target.value)} rows={7} placeholder={chosenCreative?.caption||'Select a generated creative to start'} className="mt-3 w-full rounded-xl border border-[#d9d2c4] p-3 text-sm outline-none"/><Button onClick={publish} disabled={busy||!selectedCreative||!selectedProviders.length} className="mt-4 w-full">{busy?<><RefreshCw className="h-4 w-4 animate-spin"/>Sending…</>:<><Send className="h-4 w-4"/>Publish to selected accounts</>}</Button></div><div><p className="text-sm font-extrabold">Publish history</p><div className="mt-3 space-y-2">{jobs.slice(0,12).map(j=><div key={j.id} className="rounded-xl border border-[#d9d2c4] bg-white p-3"><div className="flex items-center justify-between gap-2"><p className="text-xs font-extrabold">{j.provider}</p><Badge tone={j.status==='published'?'success':j.status==='failed'?'danger':'warning'}>{j.status}</Badge></div><p className="mt-1 text-[11px] leading-4 text-[#697687]">{j.errorMessage||j.externalPostId||'Provider result pending'}</p></div>)}</div></div></div>
  </section>
 </div></AppShell>;
}
