import { useEffect, useState } from 'react';
import { BrainCircuit, Plus, RefreshCw, XCircle } from 'lucide-react';
import { customFetch } from '@workspace/api-client-react';
import { AppShell } from '@/components/app-shell';
import { Badge, Button, ErrorState, LoadingState, Notice, SectionHeading } from '@/components/primitives';

type Job={id:number;niche:string|null;status:string;research:Record<string,unknown>;build_plan:Record<string,unknown>;error_message:string|null;created_at:string;updated_at:string};
export default function AdminAiStores(){
 const [jobs,setJobs]=useState<Job[]>([]); const [niche,setNiche]=useState(''); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 const load=async()=>{setLoading(true);try{const r=await customFetch<{jobs:Job[]}>('/api/admin/ai-stores',{responseType:'json'});setJobs(r.jobs??[])}catch(e){setMessage(e instanceof Error?e.message:'AI store jobs could not be loaded.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const create=async()=>{setBusy(true);setMessage('');try{await customFetch('/api/admin/ai-stores',{method:'POST',body:JSON.stringify({niche}),responseType:'json'});setNiche('');setMessage('AI store creation job queued. Research and external publishing remain provider-confirmed.');await load()}catch(e){setMessage(e instanceof Error?e.message:'AI store job could not be queued.')}finally{setBusy(false)}};
 const cancel=async(id:number)=>{if(!window.confirm('Cancel this AI store job?'))return;setBusy(true);try{await customFetch(`/api/admin/ai-stores/${id}/cancel`,{method:'POST',responseType:'json'});await load()}catch(e){setMessage(e instanceof Error?e.message:'Job could not be cancelled.')}finally{setBusy(false)}};
 return <AppShell admin><div className="mx-auto max-w-[1180px]"><SectionHeading eyebrow="Master admin · AI commerce" title="AI Store Creator" description="Queue stores for autonomous research and construction. Lunavo never invents supplier connections, products, market evidence or published social activity."/><section className="mt-6 rounded-2xl border border-[#d9d2c4] bg-[#fbfaf6] p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#182333] text-[#f8f3e8]"><BrainCircuit className="h-5 w-5"/></span><div><h2 className="font-extrabold">Create an AI store job</h2><p className="text-xs text-[#697687]">Leave niche blank for a broad market research pass, or describe the niche in plain language.</p></div></div><div className="mt-5 flex flex-col gap-3 sm:flex-row"><input value={niche} onChange={e=>setNiche(e.target.value)} maxLength={1000} className="h-11 flex-1 rounded-xl border border-[#d5cdbd] bg-white px-3 text-sm" placeholder="e.g. premium modest fashion for West African professionals"/><Button onClick={create} disabled={busy}><Plus className="h-4 w-4"/>Queue AI store</Button></div>{message&&<div className="mt-4"><Notice tone="success" title="AI store creator">{message}</Notice></div>}</section><section className="mt-7">{loading?<LoadingState label="Loading AI store jobs"/>:jobs.length?<div className="space-y-3">{jobs.map(job=><div key={job.id} className="rounded-2xl border border-[#d9d2c4] bg-[#fbfaf6] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[.14em] text-[#a2772e]">Job #{job.id}</p><h3 className="mt-1 font-extrabold">{job.niche||'Market discovery store'}</h3><p className="mt-1 text-xs text-[#697687]">Created {new Date(job.created_at).toLocaleString()}</p></div><Badge tone={job.status==='failed'?'danger':job.status==='published'?'success':'neutral'}>{job.status.replaceAll('_',' ')}</Badge></div>{job.error_message&&<p className="mt-3 text-xs font-bold text-[#a33e38]">{job.error_message}</p>}{['queued','researching','ready_for_review','building'].includes(job.status)&&<Button variant="secondary" className="mt-4" onClick={()=>void cancel(job.id)} disabled={busy}><XCircle className="h-4 w-4"/>Cancel job</Button>}</div>)}</div>:<div className="rounded-2xl border border-dashed border-[#d9d2c4] p-10 text-center"><p className="font-extrabold">No AI store jobs yet.</p><p className="mt-2 text-sm text-[#697687]">Queue the first store and the durable job record will track its lifecycle.</p><Button variant="secondary" className="mt-4" onClick={()=>void load()}><RefreshCw className="h-4 w-4"/>Refresh</Button></div>}</section></div></AppShell>;
}
