import { type FormEvent, useEffect, useMemo, useState } from "react";
import { CheckCircle2, Clock3, FlaskConical, GitBranch, PauseCircle, PlayCircle, ShieldCheck, Zap } from "lucide-react";
import AppShell from "@/components/app-shell";

type Workflow = { id:string; workflow_key:string; name:string; description:string|null; enabled:boolean; mode:"dry_run"|"approval"|"automatic"; trigger_event:string; conditions:unknown; actions:unknown; cooldown_seconds:number; daily_run_limit:number; version:number; next_scheduled_at:string|null; schedule_interval_seconds:number; };
type Run = { id:string; status:string; event_id:string|null; result:Record<string,unknown>; error_message:string|null; created_at:string; approval_status:string|null; };
const inputClass="mt-2 h-11 w-full rounded-xl border border-[#d9d2c4] bg-white px-3 text-sm text-[#182333] outline-none focus:border-[#b14f36] focus:ring-2 focus:ring-[#b14f36]/15";
const triggers=["order.created","payment.verified","inventory.reserved","inventory.released","inventory.committed","refund.processed","invoice.payment_verified","marketplace.listing_reviewed","storefront.published","merchant.operation.created","merchant.message.created","schedule.tick"];

export default function Automations(){
  const [workflows,setWorkflows]=useState<Workflow[]>([]),[selected,setSelected]=useState<Workflow|null>(null),[runs,setRuns]=useState<Run[]>([]);
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const [name,setName]=useState("New order operations"),[key,setKey]=useState("new-order-operations"),[trigger,setTrigger]=useState("order.created"),[mode,setMode]=useState<Workflow["mode"]>("approval");
  const [conditionPath,setConditionPath]=useState(""),[conditionOp,setConditionOp]=useState("eq"),[conditionValue,setConditionValue]=useState("");
  const [actionKind,setActionKind]=useState("create_operation"),[actionTitle,setActionTitle]=useState("Review new order"),[operationKind,setOperationKind]=useState("task");
  async function load(){setLoading(true);try{const r=await fetch("/api/merchant/automation-workflows");const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not load workflows");setWorkflows(d.workflows||[]);}catch(e){setMessage(e instanceof Error?e.message:"Could not load workflows");}finally{setLoading(false);}}
  async function loadRuns(w:Workflow){setSelected(w);const r=await fetch("/api/merchant/automation-workflows/"+w.id+"/runs");const d=await r.json();if(r.ok)setRuns(d.runs||[]);else setMessage(d.error||"Could not load run history");}
  useEffect(()=>{void load();},[]);
  const conditions=useMemo(()=>conditionPath?[{path:conditionPath,op:conditionOp,value:conditionOp==="exists"?undefined:conditionOp==="in"?conditionValue.split(",").map(v=>v.trim()).filter(Boolean):conditionValue}]:[],[conditionPath,conditionOp,conditionValue]);
  const action=actionKind==="create_operation"?{kind:actionKind,config:{kind:operationKind,title:actionTitle,priority:"normal"}}:actionKind==="create_message"?{kind:actionKind,config:{subject:"Lunavo automation",body:actionTitle}}:{kind:actionKind,config:{key:"automation.flag",enabled:true,config:{}}};
  async function createWorkflow(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/merchant/automation-workflows",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({workflowKey:key,name,description:"Merchant-defined workflow created in Automation Studio.",triggerEvent:trigger,mode,conditions,actions:[action],dailyRunLimit:100,cooldownSeconds:0,scheduleIntervalSeconds:trigger==="schedule.tick"?3600:0})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Workflow could not be created");setMessage("Workflow created disabled. Review it, then enable it.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Workflow could not be created");}finally{setBusy(false);}}
  async function updateWorkflow(id:string,patch:Partial<Workflow>){const r=await fetch("/api/merchant/automation-workflows/"+id,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(patch)});const d=await r.json();if(!r.ok){setMessage(d.error||"Workflow update failed");return;}setMessage("Workflow updated.");await load();if(selected&&selected.id===id)await loadRuns(d.workflow);}
  async function runNow(w:Workflow){const r=await fetch("/api/merchant/automation-workflows/"+w.id+"/run-now",{method:"POST",headers:{"content-type":"application/json"}});const d=await r.json();setMessage(r.ok?"Test dispatched. Event: "+d.testEventId:d.error||"Test failed");await loadRuns(w);}
  async function decide(run:Run,approve:boolean){const r=await fetch("/api/merchant/automation-runs/"+run.id+"/decision",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({approve,note:approve?"Approved from Automation Studio":"Rejected from Automation Studio"})});const d=await r.json();setMessage(r.ok?"Run "+d.status+".":d.error||"Decision failed");if(selected)await loadRuns(selected);}
  return <AppShell><div className="mx-auto max-w-[1280px] px-5 py-8 md:px-8">
    <div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[.18em] text-[#a2772e]">Automation Studio</p><h1 className="mt-2 text-4xl font-extrabold tracking-[-.07em] text-[#182333]">Turn real commerce events into safe actions.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#697687]">Build event → condition → action workflows. Preview them, require approval, or run guarded internal actions automatically.</p></div><div className="flex items-center gap-2 rounded-full border border-[#c9d8d1] bg-[#f5faf7] px-4 py-2 text-xs font-extrabold text-[#2f6958]"><ShieldCheck className="h-4 w-4"/>Guarded by Lunavo policy</div></div>
    {message&&<div className="mt-6 rounded-xl border border-[#d9d2c4] bg-white p-4 text-sm font-bold text-[#4d5e6f]">{message}</div>}
    <div className="mt-8 grid gap-6 lg:grid-cols-[.85fr_1.15fr]">
      <section className="rounded-2xl border border-[#d9d2c4] bg-[#fbfaf6] p-6"><div className="flex items-center gap-3"><GitBranch className="h-5 w-5 text-[#8a6826]"/><h2 className="text-xl font-extrabold">Create a workflow</h2></div>
        <form onSubmit={createWorkflow} className="mt-6 space-y-4">
          <label className="block text-sm font-bold">Workflow name<input value={name} onChange={e=>setName(e.target.value)} className={inputClass} maxLength={160} required/></label>
          <label className="block text-sm font-bold">Stable key<input value={key} onChange={e=>setKey(e.target.value)} className={inputClass} pattern="[a-zA-Z0-9._:-]{1,80}" required/></label>
          <label className="block text-sm font-bold">Trigger<select value={trigger} onChange={e=>setTrigger(e.target.value)} className={inputClass}>{triggers.map(t=><option key={t}>{t}</option>)}</select></label>
          <label className="block text-sm font-bold">Execution safety<select value={mode} onChange={e=>setMode(e.target.value as Workflow["mode"])} className={inputClass}><option value="dry_run">Preview only</option><option value="approval">Require approval</option><option value="automatic">Automatic (guarded)</option></select></label>
          <div className="rounded-xl border border-[#ddd4c5] bg-white p-4"><p className="text-xs font-extrabold uppercase tracking-[.12em] text-[#697687]">Optional condition</p><div className="mt-3 grid gap-3 sm:grid-cols-[1.2fr_.7fr_1fr]"><input value={conditionPath} onChange={e=>setConditionPath(e.target.value)} placeholder="payload.status" className={inputClass}/><select value={conditionOp} onChange={e=>setConditionOp(e.target.value)} className={inputClass}><option value="eq">equals</option><option value="neq">not equals</option><option value="contains">contains</option><option value="in">in list</option><option value="gt">greater than</option><option value="gte">at least</option><option value="lt">less than</option><option value="lte">at most</option><option value="exists">exists</option></select><input value={conditionValue} onChange={e=>setConditionValue(e.target.value)} disabled={conditionOp==="exists"} placeholder="value" className={inputClass}/></div></div>
          <div className="rounded-xl border border-[#ddd4c5] bg-white p-4"><p className="text-xs font-extrabold uppercase tracking-[.12em] text-[#697687]">Action</p><select value={actionKind} onChange={e=>setActionKind(e.target.value)} className={inputClass}><option value="create_operation">Create internal operation</option><option value="create_message">Create merchant message</option><option value="set_feature_flag">Set feature flag</option><option value="log">Log only</option></select>{actionKind==="create_operation"&&<div className="mt-3 grid gap-3 sm:grid-cols-2"><select value={operationKind} onChange={e=>setOperationKind(e.target.value)} className={inputClass}><option value="task">Task</option><option value="product_alert">Product alert</option><option value="support_ticket">Support ticket</option><option value="lead">Lead</option><option value="delivery_issue">Delivery issue</option><option value="supplier_issue">Supplier issue</option></select><input value={actionTitle} onChange={e=>setActionTitle(e.target.value)} placeholder="Action title" className={inputClass}/></div>}{actionKind==="create_message"&&<input value={actionTitle} onChange={e=>setActionTitle(e.target.value)} placeholder="Message body" className={inputClass}/>}</div>
          <button disabled={busy} className="inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#182333] px-4 text-sm font-extrabold text-white disabled:opacity-50"><Zap className="h-4 w-4"/>{busy?"Creating…":"Create disabled workflow"}</button>
        </form>
      </section>
      <section className="rounded-2xl border border-[#d9d2c4] bg-[#fbfaf6] p-6"><div className="flex items-center justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-[#697687]">Your workflows</p><h2 className="mt-1 text-xl font-extrabold">Control room</h2></div><button onClick={()=>void load()} className="text-xs font-extrabold text-[#8a6826] underline">Refresh</button></div>
        <div className="mt-5 space-y-3">{loading?<p className="text-sm text-[#697687]">Loading workflows…</p>:workflows.length===0?<p className="rounded-xl bg-white p-5 text-sm text-[#697687]">No workflows yet. Create one above.</p>:workflows.map(w=><div key={w.id} className="rounded-xl border border-[#ddd4c5] bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-extrabold">{w.name}</p><p className="mt-1 text-xs text-[#697687]">{w.workflow_key} · {w.trigger_event} · v{w.version}</p></div><span className="rounded-full bg-[#f0ede6] px-2.5 py-1 text-[11px] font-extrabold text-[#697687]">{w.enabled?"Enabled":"Disabled"}</span></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>void updateWorkflow(w.id,{enabled:!w.enabled})} className="inline-flex items-center gap-1.5 rounded-lg border border-[#d9d2c4] px-3 py-2 text-xs font-extrabold">{w.enabled?<><PauseCircle className="h-3.5 w-3.5"/>Disable</>:<><PlayCircle className="h-3.5 w-3.5"/>Enable</>}</button><button onClick={()=>void runNow(w)} className="inline-flex items-center gap-1.5 rounded-lg border border-[#d9d2c4] px-3 py-2 text-xs font-extrabold"><FlaskConical className="h-3.5 w-3.5"/>Test now</button><button onClick={()=>void loadRuns(w)} className="rounded-lg border border-[#d9d2c4] px-3 py-2 text-xs font-extrabold">Run history</button></div></div>)}</div>
      </section>
    </div>
    <section className="mt-6 rounded-2xl border border-[#d9d2c4] bg-[#182333] p-6 text-[#f8f3e8]"><div className="flex items-center gap-3"><Clock3 className="h-5 w-5 text-[#d6aa46]"/><div><h2 className="font-extrabold">Run history & approvals</h2><p className="mt-1 text-xs text-[#b8c2cc]">{selected?selected.name:"Select a workflow to inspect real execution records."}</p></div></div>{selected&&<div className="mt-5 space-y-2">{runs.length===0?<p className="text-sm text-[#b8c2cc]">No runs recorded yet.</p>:runs.map(run=><div key={run.id} className="rounded-xl border border-white/10 bg-white/5 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-extrabold">{run.status}</p><p className="mt-1 text-xs text-[#9faebe]">{new Date(run.created_at).toLocaleString()} · {run.event_id||"synthetic test/schedule"}</p></div><div>{run.status==="approval_required"&&<div className="flex gap-2"><button onClick={()=>void decide(run,true)} className="rounded-lg bg-[#d6aa46] px-3 py-2 text-xs font-extrabold text-[#182333]">Approve</button><button onClick={()=>void decide(run,false)} className="rounded-lg border border-white/20 px-3 py-2 text-xs font-extrabold">Reject</button></div>}{run.status==="completed"&&<CheckCircle2 className="h-5 w-5 text-[#9ed0bb]"/>}</div></div>{run.error_message&&<p className="mt-3 text-xs text-[#f0b0a0]">{run.error_message}</p>}</div>)}</div>}</section>
    <p className="mt-4 text-xs leading-5 text-[#697687]">Automatic actions are intentionally limited to safe internal operations, messages and feature flags. Financial settlement, payouts and external publishing remain behind their dedicated provider-authoritative boundaries.</p>
  </div></AppShell>;
}