import { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowRight, BadgeCheck, Bot, Boxes, BrainCircuit, CheckCircle2, CircleDollarSign, CloudCog, Cpu, Gift, Globe2, Layers3, Megaphone, PackageCheck, Percent, Play, Radar, RefreshCw, ShieldCheck, Sparkles, Store, UsersRound, Video, WalletCards, Zap } from 'lucide-react';
import { customFetch } from '@workspace/api-client-react';
import { AppShell } from '@/components/app-shell';
import { Badge, Button, Notice, SectionHeading, LoadingState } from '@/components/primitives';

type AutoDsResponse = { settings: { enabled:boolean; mode:string; autoAllocateSupplierCost:boolean; requireApprovalBeforeExternalOrder:boolean; minimumMarginPercent:string|number; defaultCarrier:string|null }; capabilities: { automaticInternalRouting:boolean; automaticSupplierApiOrdering:boolean; reason:string }; jobs: Array<{ id:string; orderId:number; status:string; mode:string; currency:string|null; createdAt:string; lastError:string|null }> };
type Discount = { id:number; code:string; kind:string; value:string; active:boolean; usageCount:number; usageLimit:number|null; currency:string|null };

const capabilities = [
  ['Autonomous commerce brain','AI can analyze catalog, orders, margins and growth signals without becoming the money-moving authority.',BrainCircuit],
  ['Local image studio','Self-hosted creative generation boundary; no hosted AI key is required.',Sparkles],
  ['Long-form video','5–10 minute video orchestration with segment stitching and continuity controls.',Video],
  ['TS Pay control layer','Checkout, ledger, fees, refunds and reconciliation remain first-party; Flutterwave stays the payment rail.',WalletCards],
  ['Profit Firewall','Margin floors, approval gates and risk checks before supplier-side automation.',ShieldCheck],
  ['Omnichannel catalog','Storefront, marketplace, POS, digital products and creator commerce share one catalog model.',Globe2],
  ['Supplier orchestration','Verified orders can enter fulfillment workflows with explicit merchant controls.',PackageCheck],
  ['Growth engine','Discounts, loyalty, affiliates, campaigns and customer signals live beside commerce data.',Megaphone],
] as const;

export default function CommerceSuite() {
  const [data,setData]=useState<AutoDsResponse|null>(null); const [discounts,setDiscounts]=useState<Discount[]>([]); const [enabled,setEnabled]=useState(false); const [mode,setMode]=useState<'assisted'|'auto'>('assisted'); const [autoAllocate,setAutoAllocate]=useState(false); const [approval,setApproval]=useState(true); const [margin,setMargin]=useState('10'); const [carrier,setCarrier]=useState(''); const [code,setCode]=useState(''); const [value,setValue]=useState('10'); const [kind,setKind]=useState<'percentage'|'fixed'>('percentage'); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [pulse,setPulse]=useState(0);
  const load=async()=>{setLoading(true);try{const [auto,discount]=await Promise.all([customFetch<AutoDsResponse>('/api/automation/auto-ds'),customFetch<{codes:Discount[]}>('/api/commerce/discount-codes')]);setData(auto);setDiscounts(discount.codes);setEnabled(auto.settings.enabled);setMode(auto.settings.mode==='auto'?'auto':'assisted');setAutoAllocate(auto.settings.autoAllocateSupplierCost);setApproval(auto.settings.requireApprovalBeforeExternalOrder);setMargin(String(auto.settings.minimumMarginPercent));setCarrier(auto.settings.defaultCarrier??'');setPulse(p=>p+1);}catch(e){setMessage(e instanceof Error?e.message:'Commerce Suite could not be loaded.')}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const saveAutoDs=async()=>{setSaving(true);setMessage('');try{await customFetch('/api/automation/auto-ds',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({enabled,mode,autoAllocateSupplierCost:autoAllocate,requireApprovalBeforeExternalOrder:approval,minimumMarginPercent:Number(margin),defaultCarrier:carrier})});setMessage('Automation controls saved.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Automation controls could not be saved.')}finally{setSaving(false)}};
  const createDiscount=async()=>{try{await customFetch('/api/commerce/discount-codes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code,value:Number(value),kind})});setCode('');setMessage('Discount code created.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Discount code could not be created.')}};
  const liveJobs=useMemo(()=>data?.jobs?.filter(j=>['pending','processing','approved'].includes(j.status)).length??0,[data]);
  if(loading)return <AppShell><LoadingState label="Loading Lunavo Command Center"/></AppShell>;
  return <AppShell><div className="mx-auto max-w-[1320px] pb-12">
    <header className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[#a2772e]">Lunavo Commerce OS</p><h1 className="mt-2 text-4xl font-extrabold tracking-[-.07em] md:text-5xl">The command center.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#697687]">One operating layer for storefronts, payments, fulfillment, growth, creator commerce and self-hosted intelligence. Built to feel like an entire commerce company in one workspace.</p></div><div className="flex gap-2"><Button onClick={()=>void load()} variant="outline"><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button><Badge tone="success"><span className="mr-1 inline-block h-1.5 w-1.5 rounded-full bg-current"/>Systems online</Badge></div></header>
    {message&&<div className="mt-6"><Notice tone={message.toLowerCase().includes('could not')||message.toLowerCase().includes('unavailable')?'danger':'success'} title="Lunavo">{message}</Notice></div>}
    <section className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={Activity} label="Automation jobs" value={String(data?.jobs?.length??0)} hint={`${liveJobs} active`} /><Metric icon={Percent} label="Promotion codes" value={String(discounts.length)} hint="Commerce-native"/><Metric icon={Radar} label="Automation mode" value={mode==='auto'?'AUTO':'ASSISTED'} hint={enabled?'Enabled':'Guarded'} /><Metric icon={Cpu} label="Intelligence" value="LOCAL" hint="No hosted AI key"/></section>
    <section className="mt-8 overflow-hidden rounded-3xl border border-[#334154] bg-[#182333] text-[#f8f3e8] shadow-[0_28px_70px_rgba(24,35,51,.16)]"><div className="p-6 md:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex items-center gap-2"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#d6aa46]/15 text-[#e1b95d]"><Zap className="h-5 w-5"/></span><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#d6aa46]">Autonomous commerce</p></div><h2 className="mt-4 text-2xl font-extrabold">Auto-DS + Profit Firewall</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#b8c2cc]">Let Lunavo orchestrate verified supplier-backed orders while enforcing your margin floor and approval policy. No AI action can confirm a payment, edit the ledger or bypass authorization.</p></div><Badge tone={enabled?'success':'neutral'}>{enabled?'Automation armed':'Automation guarded'}</Badge></div><div className="mt-7 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><DarkField label="Automation" value={enabled?'On':'Off'}><select value={enabled?'yes':'no'} onChange={e=>setEnabled(e.target.value==='yes')}><option value="no">Off</option><option value="yes">On</option></select></DarkField><DarkField label="Mode" value=""><select value={mode} onChange={e=>setMode(e.target.value as 'assisted'|'auto')}><option value="assisted">Assisted</option><option value="auto">Auto routing</option></select></DarkField><DarkField label="Margin floor" value=""><input value={margin} onChange={e=>setMargin(e.target.value)} type="number" min="0" max="100" step="0.01"/></DarkField><DarkField label="Carrier" value=""><input value={carrier} onChange={e=>setCarrier(e.target.value)} placeholder="Optional"/></DarkField></div><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="flex gap-3 rounded-xl border border-[#536174] bg-[#243344] p-4 text-sm font-bold"><input type="checkbox" checked={approval} onChange={e=>setApproval(e.target.checked)}/>Require approval before external supplier order</label><label className="flex gap-3 rounded-xl border border-[#536174] bg-[#243344] p-4 text-sm font-bold"><input type="checkbox" checked={autoAllocate} onChange={e=>setAutoAllocate(e.target.checked)}/>Allow recorded supplier-cost allocation</label></div><div className="mt-5 flex flex-wrap items-center gap-3"><Button onClick={saveAutoDs} disabled={saving} className="bg-[#d6aa46] text-[#182333] hover:bg-[#e0b95d]">{saving?'Saving…':'Save automation'}</Button><span className="text-xs text-[#aeb9c4]">{data?.capabilities.reason}</span></div></div></section>
    <section className="mt-8"><div className="flex items-end justify-between"><SectionHeading eyebrow="Built-in frontier" title="The parts that make Lunavo feel unfair" description="A connected operating system instead of a pile of plugins."/><span className="hidden text-xs font-bold text-[#697687] md:block">Pulse {pulse}</span></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{capabilities.map(([title,desc,Icon])=><div key={title} className="group rounded-2xl border border-[#d9d2c4] bg-[#fbfaf6] p-5 transition hover:-translate-y-0.5 hover:shadow-[0_18px_40px_rgba(24,35,51,.08)]"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#eef3f4] text-[#315e6c]"><Icon className="h-5 w-5"/></span><CheckCircle2 className="h-4 w-4 text-[#6d9d7f]"/></div><h3 className="mt-4 text-sm font-extrabold">{title}</h3><p className="mt-2 text-xs leading-5 text-[#697687]">{desc}</p></div>)}</div></section>
    <section className="mt-8 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-[#d9d2c4] bg-[#fbfaf6] p-6"><SectionHeading eyebrow="Growth engine" title="Promotion cockpit" description="Create reusable percentage or fixed-value discounts without leaving the operating system."/><div className="mt-5 grid gap-3 sm:grid-cols-[1fr_120px_120px_auto]"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="WELCOME10" className="h-10 rounded-lg border border-[#d9d2c4] bg-white px-3 text-sm"/><select value={kind} onChange={e=>setKind(e.target.value as 'percentage'|'fixed')} className="h-10 rounded-lg border border-[#d9d2c4] bg-white px-3 text-sm"><option value="percentage">%</option><option value="fixed">Fixed</option></select><input value={value} onChange={e=>setValue(e.target.value)} type="number" min="0.01" className="h-10 rounded-lg border border-[#d9d2c4] bg-white px-3 text-sm"/><Button onClick={createDiscount} disabled={!code.trim()}>Create</Button></div><div className="mt-5 space-y-2">{discounts.length?discounts.map(d=><div key={d.id} className="flex items-center justify-between rounded-xl border border-[#d9d2c4] p-3"><div><p className="text-sm font-extrabold">{d.code}</p><p className="text-xs text-[#697687]">{d.kind==='percentage'?d.value+'%':d.value+' '+(d.currency??'')} · {d.usageCount} uses</p></div><Badge tone={d.active?'success':'neutral'}>{d.active?'Active':'Inactive'}</Badge></div>):<p className="text-sm text-[#697687]">No discount codes yet.</p>}</div></div>
    <div className="rounded-2xl border border-[#d9d2c4] bg-[#fbfaf6] p-6"><SectionHeading eyebrow="Creator + retention" title="Commerce beyond physical products" description="Lunavo's commerce model is designed to cover digital delivery, courses, memberships, loyalty and saved shopping."/><div className="mt-5 grid grid-cols-2 gap-3"><Tile icon={Layers3} title="Digital catalog" text="Files, entitlements and digital product types."/><Tile icon={Store} title="Courses" text="Lessons, curriculum, previews and certificates."/><Tile icon={UsersRound} title="Memberships" text="Access-oriented customer commerce."/><Tile icon={Gift} title="Loyalty & gifts" text="Points, gift cards and retention primitives."/></div></div></section>
    <section className="mt-8 rounded-2xl border border-[#d9d2c4] bg-[#fbfaf6] p-6"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><SectionHeading eyebrow="Orchestration feed" title="Fulfillment jobs" description="Verified supplier-backed orders entering the automation layer."/><div className="flex gap-2"><Badge tone="success"><CheckCircle2 className="mr-1 h-3 w-3"/>Ledger-safe</Badge><Badge tone="neutral">No fake payment state</Badge></div></div>{data?.jobs?.length?<div className="mt-5 space-y-2">{data.jobs.map(j=><div key={j.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#d9d2c4] p-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#eef3f4] text-[#315e6c]"><PackageCheck className="h-4 w-4"/></span><div><p className="text-sm font-extrabold">Order #{j.orderId}</p><p className="mt-1 text-xs text-[#697687]">{j.mode} · {j.currency??'currency pending'} · {new Date(j.createdAt).toLocaleString()}</p></div></div><Badge tone={j.status==='approved'?'success':'warning'}>{j.status}</Badge></div>)}</div>:<p className="mt-5 text-sm text-[#697687]">No Auto-DS jobs yet. A verified supplier-backed order will appear here when orchestration is enabled.</p>}</section>
    <footer className="mt-8 grid gap-4 rounded-2xl border border-[#bfd6dc] bg-[#eef7f8] p-5 md:grid-cols-3"><FooterItem icon={ShieldCheck} title="Guardrails first" text="AI never becomes the payment authority."/><FooterItem icon={CloudCog} title="Self-hosted core" text="Core intelligence has no hosted AI credential dependency."/><FooterItem icon={CircleDollarSign} title="Real money rails" text="Flutterwave is the external payment rail; TS Pay remains the control layer."/></footer>
  </div></AppShell>;
}
function Metric({icon:Icon,label,value,hint}:{icon:any;label:string;value:string;hint:string}){return <div className="rounded-2xl border border-[#d9d2c4] bg-[#fbfaf6] p-5"><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-[.08em] text-[#697687]">{label}</span><Icon className="h-4 w-4 text-[#a2772e]"/></div><p className="mt-3 text-2xl font-extrabold tracking-[-.04em]">{value}</p><p className="mt-1 text-xs text-[#697687]">{hint}</p></div>}
function DarkField({label,children}:{label:string;value?:string;children:React.ReactNode}){return <label className="rounded-xl border border-[#536174] bg-[#243344] p-4 text-sm font-bold">{label}{children}</label>}
function Tile({icon:Icon,title,text}:{icon:any;title:string;text:string}){return <div className="rounded-xl bg-[#f7f4ed] p-4"><Icon className="h-5 w-5 text-[#315e6c]"/><p className="mt-2 text-sm font-extrabold">{title}</p><p className="mt-1 text-xs leading-5 text-[#697687]">{text}</p></div>}
function FooterItem({icon:Icon,title,text}:{icon:any;title:string;text:string}){return <div className="flex gap-3"><Icon className="mt-0.5 h-5 w-5 shrink-0 text-[#315e6c]"/><div><p className="text-sm font-extrabold text-[#315e6c]">{title}</p><p className="mt-1 text-xs leading-5 text-[#315e6c]/80">{text}</p></div></div>}
