import { useEffect,useState } from "react";
import { CreditCard, Pause, Play, RefreshCw, ShieldCheck, XCircle } from "lucide-react";
import { customFetch } from "@workspace/api-client-react";
import { AppShell } from "@/components/app-shell";
import { Badge,Button,LoadingState,Notice,SectionHeading } from "@/components/primitives";

type Plan=any; type Sub=any; type Product={id:number;title:string;sellingPrice:number|null;currency:string;status:string;visibility:string};

export default function CustomerSubscriptions(){
 const [plans,setPlans]=useState<Plan[]>([]),[subs,setSubs]=useState<Sub[]>([]),[products,setProducts]=useState<Product[]>([]);
 const [form,setForm]=useState({productId:"",name:"",description:"",intervalUnit:"month",intervalCount:"1",gracePeriodDays:"3",maxFailedAttempts:"4"});
 const [message,setMessage]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);try{const [p,s,pr]=await Promise.all([customFetch<{plans:Plan[]}>("/api/commerce/customer-subscription-plans",{responseType:"json"}),customFetch<{subscriptions:Sub[]}>("/api/commerce/customer-subscriptions",{responseType:"json"}),customFetch<any>("/api/supplier-products",{responseType:"json"})]);setPlans(p.plans||[]);setSubs(s.subscriptions||[]);const list=Array.isArray(pr)?pr:(pr.products||pr.data||[]);setProducts(list.filter((x:Product)=>x.status==="active"&&x.visibility==="active"&&x.sellingPrice!==null));}catch(e){setMessage(e instanceof Error?e.message:"Subscription controls could not be loaded.");}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const create=async()=>{setSaving(true);setMessage("");try{await customFetch("/api/commerce/customer-subscription-plans",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,productId:Number(form.productId),intervalCount:Number(form.intervalCount),gracePeriodDays:Number(form.gracePeriodDays),maxFailedAttempts:Number(form.maxFailedAttempts)})});setForm({...form,name:"",description:""});setMessage("Customer subscription plan created.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Plan could not be created.");}finally{setSaving(false);}};
 if(loading)return <AppShell><LoadingState label="Loading customer subscriptions"/></AppShell>;
 return <AppShell><div className="mx-auto max-w-[1240px]">
  <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#a2772e]">Recurring commerce</p><h1 className="mt-2 text-4xl font-extrabold tracking-[-.07em]">Customer subscriptions</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#697687]">Sell recurring access with explicit plans, verified Flutterwave payments, renewal attempts, grace periods and fail-closed entitlement state.</p></div><Badge tone="success"><ShieldCheck className="mr-1 inline h-3.5 w-3.5"/>Server verified billing</Badge></div>
  {message&&<div className="mt-6"><Notice title="Subscription controls" tone={/could not|failed|invalid|error/i.test(message)?"danger":"success"}>{message}</Notice></div>}
  <section className="mt-8 rounded-2xl border border-[#d9d2c4] bg-[#fbfaf6] p-6"><SectionHeading eyebrow="Plan builder" title="Create a recurring plan" description="Use an existing published product as the canonical priced item. The customer charge always matches the server price."/>
   <div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-4">
    <label className="text-sm font-bold lg:col-span-2">Product<select value={form.productId} onChange={e=>setForm({...form,productId:e.target.value})} className="mt-2 h-11 w-full rounded-xl border border-[#d9d2c4] bg-white px-3"><option value="">Choose a published product</option>{products.map(p=><option key={p.id} value={p.id}>{p.title} · {p.sellingPrice} {p.currency}</option>)}</select></label>
    <label className="text-sm font-bold">Plan name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} maxLength={120} className="mt-2 h-11 w-full rounded-xl border border-[#d9d2c4] bg-white px-3"/></label>
    <label className="text-sm font-bold">Interval<select value={form.intervalUnit} onChange={e=>setForm({...form,intervalUnit:e.target.value})} className="mt-2 h-11 w-full rounded-xl border border-[#d9d2c4] bg-white px-3"><option value="month">Monthly</option><option value="week">Weekly</option><option value="day">Daily</option><option value="year">Yearly</option></select></label>
   </div>
   <div className="mt-4 grid gap-4 sm:grid-cols-3"><label className="text-sm font-bold">Interval count<input type="number" min="1" max="12" value={form.intervalCount} onChange={e=>setForm({...form,intervalCount:e.target.value})} className="mt-2 h-11 w-full rounded-xl border border-[#d9d2c4] bg-white px-3"/></label><label className="text-sm font-bold">Grace days<input type="number" min="0" max="30" value={form.gracePeriodDays} onChange={e=>setForm({...form,gracePeriodDays:e.target.value})} className="mt-2 h-11 w-full rounded-xl border border-[#d9d2c4] bg-white px-3"/></label><label className="text-sm font-bold">Max failed attempts<input type="number" min="1" max="12" value={form.maxFailedAttempts} onChange={e=>setForm({...form,maxFailedAttempts:e.target.value})} className="mt-2 h-11 w-full rounded-xl border border-[#d9d2c4] bg-white px-3"/></label></div>
   <label className="mt-4 block text-sm font-bold">Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} maxLength={500} rows={3} className="mt-2 w-full rounded-xl border border-[#d9d2c4] bg-white p-3"/></label>
   <Button className="mt-5" onClick={()=>void create()} disabled={saving||!form.productId||!form.name.trim()}>{saving?"Creating…":"Create subscription plan"}</Button>
  </section>
  <section className="mt-8"><SectionHeading eyebrow="Plans" title="Published subscription plans"/><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{plans.length?plans.map(p=><article key={p.id} className="rounded-2xl border border-[#d9d2c4] bg-[#fbfaf6] p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-extrabold">{p.name}</h3><p className="mt-1 text-xs text-[#697687]">{p.product_title}</p></div><Badge tone={p.status==="active"?"success":"neutral"}>{p.status}</Badge></div><p className="mt-4 font-mono text-lg font-bold">{(Number(p.amount_minor)/100).toFixed(2)} {p.currency}</p><p className="mt-1 text-xs text-[#697687]">Every {p.interval_count} {p.interval_unit}{p.interval_count===1?"":"s"} · {p.grace_period_days} grace days</p><a className="mt-4 inline-flex text-xs font-extrabold text-[#a34c35] underline" href={"/subscribe/"+p.id} target="_blank" rel="noreferrer">Open public checkout</a></article>):<p className="rounded-xl border border-dashed p-5 text-sm text-[#697687]">No recurring plans yet.</p>}</div></section>
  <section className="mt-8"><SectionHeading eyebrow="Live lifecycle" title="Customer subscriptions" action={<Button variant="ghost" onClick={()=>void load()}><RefreshCw className="h-4 w-4"/>Refresh</Button>}/><div className="mt-4 overflow-x-auto rounded-2xl border border-[#d9d2c4] bg-[#fbfaf6]"><table className="w-full min-w-[950px] text-left text-sm"><thead className="bg-[#f3efe7] text-[10px] uppercase tracking-[.12em] text-[#697687]"><tr><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Plan</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Next charge</th><th className="px-5 py-3">Failures</th></tr></thead><tbody className="divide-y divide-[#ded8cd]">{subs.map(s=><tr key={s.id}><td className="px-5 py-4"><p className="font-extrabold">{s.customer_name}</p><p className="text-xs text-[#697687]">{s.customer_email}</p></td><td className="px-5 py-4">{s.plan_name}<p className="text-xs text-[#697687]">{(Number(s.amount_minor)/100).toFixed(2)} {s.currency}</p></td><td className="px-5 py-4"><Badge tone={s.status==="active"?"success":s.status==="past_due"?"warning":"danger"}>{s.status}</Badge></td><td className="px-5 py-4 text-xs">{new Date(s.next_charge_at).toLocaleString()}</td><td className="px-5 py-4 font-mono">{s.failed_attempts}/{s.max_failed_attempts}</td></tr>)}</tbody></table>{!subs.length&&<p className="p-5 text-sm text-[#697687]">No customer subscriptions yet.</p>}</div></section>
 </div></AppShell>;
}