import { useEffect, useState } from "react";
import { MapPin, MessageSquareText, RefreshCw, ShoppingCart, Star, UserRound } from "lucide-react";
import { customFetch } from "@workspace/api-client-react";
import { AppShell } from "@/components/app-shell";
import { Badge, Button, EmptyState, ErrorState, LoadingState } from "@/components/primitives";

type Cart={id:string;customer_email:string|null;customer_name:string|null;currency:string;subtotal:number;status:string;last_activity_at:string};
type Review={id:string;rating:number;title:string|null;body:string;status:string;verified_purchase:boolean;customer_name:string;customer_email:string;merchant_reply:string|null};

async function readJson<T>(url:string){return customFetch<T>(url,{responseType:"json"});}
async function writeJson<T>(url:string,data:unknown){return customFetch<T>(url,{method:"POST",responseType:"json",body:JSON.stringify(data),headers:{"Content-Type":"application/json"}});}

export default function CustomerExperience(){
 const [carts,setCarts]=useState<Cart[]>([]);
 const [reviews,setReviews]=useState<Review[]>([]);
 const [customerId,setCustomerId]=useState("");
 const [addresses,setAddresses]=useState<any[]>([]);
 const [loading,setLoading]=useState(true);
 const [error,setError]=useState("");
 const [reply,setReply]=useState<Record<string,string>>({});
 const load=async()=>{setError("");setLoading(true);try{const [c,r]=await Promise.all([readJson<{carts:Cart[]}>("/api/merchant/cart-recovery"),readJson<{reviews:Review[]}>("/api/merchant/reviews")]);setCarts(c.carts);setReviews(r.reviews);}catch{setError("Customer experience data could not be loaded.")}finally{setLoading(false)}};
 useEffect(()=>{void load();},[]);
 const loadAddresses=async()=>{const id=Number(customerId);if(!Number.isInteger(id)||id<1)return;try{const r=await readJson<{addresses:any[]}>(`/api/merchant/customer-addresses/${id}`);setAddresses(r.addresses);}catch{setAddresses([])}};
 const moderate=async(id:string,status:string)=>{try{await writeJson(`/api/merchant/reviews/${id}/moderate`,{status});await load();}catch{setError("Review moderation failed.")}};
 const sendReply=async(id:string)=>{const value=(reply[id]??"").trim();if(!value)return;try{await writeJson(`/api/merchant/reviews/${id}/reply`,{reply:value});setReply(v=>({...v,[id]:""}));await load();}catch{setError("Review reply could not be saved.")}};
 if(loading)return <AppShell><LoadingState label="Loading customer experience" /></AppShell>;
 if(error&&!carts.length&&!reviews.length)return <AppShell><ErrorState onRetry={load} /></AppShell>;
 return <AppShell><div className="mx-auto max-w-[1280px] space-y-6">
  <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-[#a2772e]">Customer experience</p><h1 className="mt-2 text-3xl font-black tracking-[-.05em]">Retention, trust & customer data</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#697687]">Recover abandoned carts, moderate verified reviews, and manage customer address records.</p></div><Button variant="secondary" onClick={()=>void load()}><RefreshCw className="h-4 w-4"/>Refresh</Button></header>
  {error&&<div className="rounded-xl bg-[#fff0ed] px-4 py-3 text-sm font-bold text-[#943b35]">{error}</div>}
  <section className="rounded-2xl border border-[#d9d2c4] bg-[#fbfaf6] p-5"><div className="flex items-center gap-3"><ShoppingCart className="h-5 w-5 text-[#2f6958]"/><div><h2 className="font-extrabold">Abandoned carts</h2><p className="text-xs text-[#697687]">{carts.filter(c=>c.status==="abandoned").length} abandoned · {carts.filter(c=>c.status==="recovered").length} recovered</p></div></div>{carts.length?<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b text-[10px] uppercase tracking-[.12em] text-[#8994a2]"><tr><th className="px-2 py-3">Customer</th><th className="px-2 py-3">State</th><th className="px-2 py-3">Value</th><th className="px-2 py-3">Last activity</th></tr></thead><tbody className="divide-y">{carts.map(c=><tr key={c.id}><td className="px-2 py-3"><p className="font-bold">{c.customer_name||"Guest"}</p><p className="text-xs text-[#697687]">{c.customer_email||"No email captured"}</p></td><td className="px-2 py-3"><Badge tone={c.status==="recovered"?"success":c.status==="abandoned"?"warning":"neutral"}>{c.status}</Badge></td><td className="px-2 py-3 font-mono">{c.currency} {Number(c.subtotal).toFixed(2)}</td><td className="px-2 py-3 text-xs text-[#697687]">{new Date(c.last_activity_at).toLocaleString()}</td></tr>)}</tbody></table></div>:<EmptyState title="No recoverable carts yet" description="Idle carts will appear here after the recovery sweep runs."/>}</section>
  <section className="rounded-2xl border border-[#d9d2c4] bg-[#fbfaf6] p-5"><div className="flex items-center gap-3"><Star className="h-5 w-5 text-[#a2772e]"/><div><h2 className="font-extrabold">Verified-purchase reviews</h2><p className="text-xs text-[#697687]">Moderate and reply without losing the verified-purchase signal.</p></div></div>{reviews.length?<div className="mt-5 space-y-4">{reviews.map(r=><article key={r.id} className="rounded-xl border border-[#e2ddd2] bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold">{r.title||"Untitled review"}</p><p className="mt-1 text-xs text-[#697687]">{r.customer_name} · {r.customer_email}</p></div><div className="flex items-center gap-2"><Badge tone="success">{r.verified_purchase?"Verified purchase":"Unverified"}</Badge><span className="font-mono text-sm">{"★".repeat(r.rating)}{"☆".repeat(5-r.rating)}</span><Badge tone={r.status==="approved"?"success":r.status==="flagged"?"danger":"warning"}>{r.status}</Badge></div></div><p className="mt-3 text-sm leading-6 text-[#4f5d70]">{r.body}</p><div className="mt-4 flex flex-wrap gap-2">{r.status!=="approved"&&<Button className="min-h-9" onClick={()=>void moderate(r.id,"approved")}>Approve</Button>}{r.status!=="rejected"&&<Button variant="secondary" className="min-h-9" onClick={()=>void moderate(r.id,"rejected")}>Reject</Button>}{r.status!=="flagged"&&<Button variant="secondary" className="min-h-9" onClick={()=>void moderate(r.id,"flagged")}>Flag</Button>}</div><div className="mt-4 flex gap-2"><input value={reply[r.id]||""} onChange={e=>setReply(v=>({...v,[r.id]:e.target.value}))} maxLength={2000} placeholder={r.merchant_reply?"Update merchant reply":"Reply to customer"} className="min-w-0 flex-1 rounded-lg border border-[#d9d2c4] bg-[#f8f5ee] px-3 py-2 text-sm"/><Button variant="secondary" onClick={()=>void sendReply(r.id)}><MessageSquareText className="h-4 w-4"/>Reply</Button></div></article>)}</div>:<EmptyState title="No reviews yet" description="Verified reviews will appear here after customers submit them."/>}</section>
  <section className="rounded-2xl border border-[#d9d2c4] bg-[#fbfaf6] p-5"><div className="flex items-center gap-3"><MapPin className="h-5 w-5 text-[#315e6c]"/><div><h2 className="font-extrabold">Customer address book</h2><p className="text-xs text-[#697687]">Look up address records by customer ID.</p></div></div><div className="mt-4 flex max-w-xl gap-2"><input value={customerId} onChange={e=>setCustomerId(e.target.value)} inputMode="numeric" placeholder="Customer ID" className="h-10 flex-1 rounded-lg border border-[#d9d2c4] bg-[#f8f5ee] px-3 font-mono text-sm"/><Button variant="secondary" onClick={()=>void loadAddresses()}><UserRound className="h-4 w-4"/>Load</Button></div>{addresses.length?<div className="mt-4 grid gap-3 sm:grid-cols-2">{addresses.map(a=><div key={a.id} className="rounded-xl border border-[#e2ddd2] bg-white p-4"><div className="flex items-center justify-between gap-2"><b>{a.label}</b>{a.is_default&&<Badge tone="success">Default</Badge>}</div><p className="mt-2 text-sm">{a.recipient_name}</p><p className="mt-1 text-xs leading-5 text-[#697687]">{a.address_line1}{a.address_line2?", "+a.address_line2:""}<br/>{a.city}{a.state?", "+a.state:""} {a.postal_code||""}<br/>{a.country}</p></div>)}</div>:customerId&&<p className="mt-4 text-sm text-[#697687]">No address records found.</p>}</section>
 </div></AppShell>;
}