import { ArrowDownRight, ArrowUpRight, Banknote, CircleDollarSign, CreditCard, PackageCheck, UsersRound } from 'lucide-react';
import { useGetDashboardOverview, useListDashboardActivity } from '@workspace/api-client-react';
import { Link } from 'wouter';
import { AppShell } from '@/components/app-shell';
import { Badge, EmptyState, ErrorState, LoadingState, MetricCard, Notice, SectionHeading } from '@/components/primitives';
import { money, timeAgo } from '@/lib/format';

export default function Dashboard() {
  const overview = useGetDashboardOverview();
  const activity = useListDashboardActivity();
  if (overview.isLoading) return <AppShell><LoadingState /></AppShell>;
  if (overview.isError || !overview.data) return <AppShell><ErrorState onRetry={() => { void overview.refetch(); }} /></AppShell>;
  const data = overview.data;
  const subscription = data.subscription;
  const needsAttention = ['warning', 'suspended', 'past_due'].includes(subscription.status);
  return <AppShell><div className="mx-auto max-w-[1320px]">
    <div className="flex flex-wrap items-start justify-between gap-5"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#a2772e]">Merchant overview</p><h1 className="mt-2 text-3xl font-extrabold tracking-[-.06em] md:text-4xl" data-testid="text-store-name">{data.storeName}</h1><p className="mt-1 text-sm text-[#697687]">/{data.storeSlug} · your business at a glance</p></div><Badge tone={subscription.status === 'active' ? 'success' : 'warning'}>{subscription.status.replaceAll('_', ' ')}</Badge></div>
    {needsAttention && <div className="mt-7"><Notice tone={subscription.status === 'suspended' ? 'danger' : 'warning'} title={subscription.status === 'suspended' ? 'Your account is suspended' : 'Your subscription needs attention'}>You have {money(subscription.amountDue - subscription.amountPaid)} remaining on your platform subscription. <Link href="/billing" className="font-extrabold underline" data-testid="link-notice-billing">Review billing</Link>.</Notice></div>}
    <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Revenue" value={money(data.revenue)} detail={<span className="inline-flex items-center gap-1 text-[#2f6958]"><ArrowUpRight className="h-3.5 w-3.5" />{data.revenueChange}% from last period</span>} icon={<CircleDollarSign className="h-5 w-5" />} /><MetricCard label="Available balance" value={money(data.availableBalance)} detail="Ready to transfer" icon={<Banknote className="h-5 w-5" />} accent /><MetricCard label="Orders" value={data.orders.toLocaleString()} detail="Across all channels" icon={<PackageCheck className="h-5 w-5" />} /><MetricCard label="Customers" value={data.customers.toLocaleString()} detail="Unique buyers" icon={<UsersRound className="h-5 w-5" />} /></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-[1.4fr_.8fr]"><section className="rounded-xl border border-[#d9d2c4] bg-[#fbfaf6] p-5 md:p-6"><SectionHeading eyebrow="Cash position" title="Revenue movement" description="A view of your recorded gross revenue." />{data.revenueSeries.some((point) => point.amount > 0) ? <div className="flex h-52 items-end gap-2 border-b border-l border-[#d9d2c4] px-3 pb-0 pt-6 md:gap-4">{data.revenueSeries.map((point, index) => { const max = Math.max(...data.revenueSeries.map((item) => item.amount), 1); return <div key={point.label} className="group flex h-full flex-1 flex-col items-center justify-end gap-2"><div className="relative w-full max-w-10 rounded-t-md bg-[#c4a152] transition-all duration-300 group-hover:bg-[#182333]" style={{ height: `${(point.amount / max) * 88}%` }} title={money(point.amount)} data-testid={`bar-revenue-${index}`} /><span className="font-mono text-[10px] text-[#8994a2]">{point.label}</span></div>; })}</div> : <EmptyState title="No revenue recorded yet" description="Real revenue will appear here when commerce activity is connected and recorded." />}</section><section className="rounded-xl border border-[#d9d2c4] bg-[#182333] p-5 text-[#f8f3e8] md:p-6"><p className="font-mono text-[10px] uppercase tracking-[.16em] text-[#d6aa46]">Settlement view</p><h2 className="mt-3 text-xl font-extrabold">Where funds sit</h2><div className="mt-7 space-y-5"><BalanceRow label="Available" value={money(data.availableBalance)} /><BalanceRow label="Pending" value={money(data.pendingBalance)} /><BalanceRow label="Held for platform fee" value={money(data.earningsHeldForSubscription)} brass /></div><div className="mt-7 border-t border-[#46566a] pt-4 text-xs leading-5 text-[#aab6c2]">Held earnings are applied to the $30 platform fee only when you confirm payment.</div></section></div>
    <div className="mt-8 grid gap-8 lg:grid-cols-[1.1fr_.9fr]"><section><SectionHeading eyebrow="Ledger" title="Recent activity" action={<Link href="/billing" className="text-xs font-extrabold text-[#8a6826] underline" data-testid="link-view-billing">View billing</Link>} />{activity.isLoading ? <LoadingState label="Loading activity" /> : activity.data?.length ? <div className="divide-y divide-[#ded8cd] rounded-xl border border-[#d9d2c4] bg-[#fbfaf6] px-5">{activity.data.map((item) => <div className="flex items-center gap-4 py-4" key={item.id} data-testid={`activity-${item.id}`}><div className={`grid h-9 w-9 shrink-0 place-items-center rounded-full ${item.tone === 'negative' ? 'bg-[#f6e2de] text-[#a33e38]' : 'bg-[#e3eee9] text-[#2f6958]'}`}>{item.tone === 'negative' ? <ArrowDownRight className="h-4 w-4" /> : <ArrowUpRight className="h-4 w-4" />}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-extrabold">{item.title}</p><p className="truncate text-xs text-[#697687]">{item.description} · {timeAgo(item.occurredAt)}</p></div><span className={`font-mono text-sm ${item.tone === 'negative' ? 'text-[#a33e38]' : 'text-[#2f6958]'}`}>{item.amount === null ? '—' : `${item.tone === 'negative' ? '−' : '+'}${money(item.amount, item.currency)}`}</span></div>)}</div> : <EmptyState title="No activity yet" description="When your first order moves through the ledger, it will appear here." />}</section><section><SectionHeading eyebrow="Subscription" title="Platform plan" /><div className="rounded-xl border border-[#d9d2c4] bg-[#fbfaf6] p-5"><div className="flex items-start justify-between"><div><p className="font-mono text-3xl tracking-[-.08em]">$30<span className="font-sans text-sm tracking-normal text-[#697687]"> / month</span></p><p className="mt-2 text-xs text-[#697687]">{subscription.paymentMethod ? `Paid via ${subscription.paymentMethod}` : 'No payment method on file'}</p></div><CreditCard className="h-5 w-5 text-[#a2772e]" /></div><div className="mt-6 space-y-3 text-sm"><div className="flex justify-between"><span className="text-[#697687]">Paid this cycle</span><strong>{money(subscription.amountPaid)}</strong></div><div className="flex justify-between"><span className="text-[#697687]">Held from earnings</span><strong>{money(subscription.earningsHeld)}</strong></div></div><Link href="/billing" className="mt-6 block rounded-lg bg-[#e9e1cd] px-4 py-3 text-center text-sm font-extrabold text-[#79591b] hover:bg-[#e3d7b9]" data-testid="link-manage-subscription">Manage subscription</Link></div></section></div>
  </div></AppShell>;
}

function BalanceRow({ label, value, brass = false }: { label: string; value: string; brass?: boolean }) {
  return <div className="flex items-center justify-between border-b border-[#46566a] pb-3 last:border-0"><span className={`text-sm ${brass ? 'text-[#d6aa46]' : 'text-[#aab6c2]'}`}>{label}</span><strong className={`font-mono text-sm ${brass ? 'text-[#f0d894]' : 'text-[#f8f3e8]'}`}>{value}</strong></div>;
}