import { type FormEvent, useState } from 'react';
import { Copy, FileText, Plus, Send, ShieldCheck, Trash2 } from 'lucide-react';
import { useQueryClient } from '@tanstack/react-query';
import { getListInvoicesQueryKey, useCreateInvoice, useListInvoices, useSendInvoice, useVerifyInvoicePayment, useVoidInvoice } from '@workspace/api-client-react';
import { AppShell } from '@/components/app-shell';
import { Badge, Button, EmptyState, ErrorState, LoadingState, Notice, SubmitButton } from '@/components/primitives';
import { money } from '@/lib/format';

const input = 'mt-1 h-10 w-full rounded-lg border border-[#d9d2c4] bg-[#f7f4ed] px-3 text-sm outline-none focus:border-[#bca26a]';
type Line = { description: string; quantity: string; unitPrice: string };
const initialLine = (): Line => ({ description: '', quantity: '1', unitPrice: '' });

export default function Invoices() {
  const invoices = useListInvoices(); const create = useCreateInvoice(); const send = useSendInvoice(); const voidInvoice = useVoidInvoice(); const verify = useVerifyInvoicePayment();
  const client = useQueryClient(); const [lines, setLines] = useState<Line[]>([initialLine()]); const [message, setMessage] = useState('');
  const invalidate = () => void client.invalidateQueries({ queryKey: getListInvoicesQueryKey() });
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    create.mutate({ data: { customerName: String(form.get('customerName')), customerEmail: String(form.get('customerEmail')), customerPhone: String(form.get('customerPhone') || '') || null, billingAddress: String(form.get('billingAddress') || '') || null, shippingAddress: String(form.get('shippingAddress') || '') || null, currency: String(form.get('currency')).toUpperCase(), lines: lines.map((l) => ({ description: l.description, quantity: Number(l.quantity), unitPrice: Number(l.unitPrice) })), discountAmount: Number(form.get('discount') || 0), taxAmount: Number(form.get('tax') || 0), shippingAmount: Number(form.get('shipping') || 0), dueDate: String(form.get('dueDate') || '') || null, notes: String(form.get('notes') || '') || null, terms: String(form.get('terms') || '') || null } }, { onSuccess: () => { event.currentTarget.reset(); setLines([initialLine()]); invalidate(); setMessage('Draft invoice created with a fixed pricing snapshot.'); }, onError: () => setMessage('Invoice could not be created. Check the pricing fields and currency.') });
  };
  if (invoices.isLoading) return <AppShell><LoadingState label="Loading invoices" /></AppShell>;
  if (invoices.isError || !invoices.data) return <AppShell><ErrorState onRetry={() => void invoices.refetch()} /></AppShell>;
  const publicUrl = (path: string) => `${window.location.origin}${import.meta.env.BASE_URL.replace(/\/$/, '')}${path}`;
  return <AppShell><div className="mx-auto max-w-[1180px]"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#a2772e]">Finance / invoices</p><h1 className="mt-2 text-3xl font-extrabold tracking-[-.06em]">Invoices with a clear review trail.</h1><p className="mt-2 text-sm text-[#697687]">Customer references are evidence awaiting your review. They never claim online card capture.</p></div>{message && <div className="mt-5"><Notice title="Invoice update" tone={message.includes('could') ? 'danger' : 'success'}>{message}</Notice></div>}
    <div className="mt-8 grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><section className="rounded-2xl border border-[#d9d2c4] bg-[#fbfaf6] p-6"><h2 className="text-xl font-extrabold">New invoice</h2><form onSubmit={submit} className="mt-5 space-y-3"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Customer name<input name="customerName" required minLength={2} className={input}/></label><label className="text-sm font-bold">Customer email<input name="customerEmail" required type="email" className={input}/></label></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Currency<input name="currency" required defaultValue="USD" maxLength={3} className={input}/></label><label className="text-sm font-bold">Due date<input name="dueDate" type="date" className={input}/></label></div><label className="text-sm font-bold">Customer phone <input name="customerPhone" className={input}/></label>
      <div className="space-y-2 rounded-xl border border-[#d9d2c4] p-3"><p className="text-sm font-extrabold">Line items</p>{lines.map((line, i) => <div className="grid grid-cols-[1fr_70px_90px_auto] gap-2" key={i}><input required placeholder="Description" value={line.description} onChange={(e) => setLines(lines.map((x,j) => j === i ? {...x,description:e.target.value}:x))} className={input}/><input required min="0.001" step="0.001" type="number" value={line.quantity} onChange={(e) => setLines(lines.map((x,j) => j === i ? {...x,quantity:e.target.value}:x))} className={input}/><input required min="0" step="0.01" placeholder="Price" type="number" value={line.unitPrice} onChange={(e) => setLines(lines.map((x,j) => j === i ? {...x,unitPrice:e.target.value}:x))} className={input}/><button type="button" aria-label="Remove line" disabled={lines.length === 1} onClick={() => setLines(lines.filter((_,j) => j !== i))} className="mt-1 text-[#a33e38]"><Trash2 className="h-4 w-4"/></button></div>)}<Button type="button" variant="secondary" className="mt-2 min-h-8 px-3 text-xs" onClick={() => setLines([...lines, initialLine()])}><Plus className="h-3.5 w-3.5"/>Add line</Button></div>
      <div className="grid grid-cols-3 gap-2"><label className="text-xs font-bold">Discount<input name="discount" min="0" step="0.01" type="number" defaultValue="0" className={input}/></label><label className="text-xs font-bold">Tax<input name="tax" min="0" step="0.01" type="number" defaultValue="0" className={input}/></label><label className="text-xs font-bold">Shipping<input name="shipping" min="0" step="0.01" type="number" defaultValue="0" className={input}/></label></div><label className="text-sm font-bold">Billing address<textarea name="billingAddress" className={`${input} h-16 py-2`}/></label><label className="text-sm font-bold">Shipping address<textarea name="shippingAddress" className={`${input} h-16 py-2`}/></label><label className="text-sm font-bold">Notes<textarea name="notes" className={`${input} h-16 py-2`}/></label><label className="text-sm font-bold">Terms<textarea name="terms" className={`${input} h-16 py-2`}/></label><SubmitButton loading={create.isPending}>Create draft</SubmitButton></form></section>
      <section className="space-y-3">{invoices.data.length ? invoices.data.map((invoice) => <article key={invoice.id} className="rounded-2xl border border-[#d9d2c4] bg-[#fbfaf6] p-5"><div className="flex flex-wrap justify-between gap-3"><div><div className="flex gap-2"><h2 className="font-mono font-bold">{invoice.invoiceNumber}</h2><Badge tone={invoice.status === 'paid' ? 'success' : invoice.status === 'void' ? 'neutral' : 'warning'}>{invoice.status}</Badge></div><p className="mt-1 text-sm text-[#697687]">{invoice.customerName} · {invoice.customerEmail}</p><p className="mt-2 font-mono font-bold">{money(invoice.total, invoice.currency)} · paid {money(invoice.amountPaid, invoice.currency)}</p>{invoice.dueDate && <p className="mt-1 text-xs text-[#697687]">Due {invoice.dueDate}</p>}</div><div className="flex flex-wrap gap-2">{invoice.status === 'draft' && <Button className="min-h-8 px-3 text-xs" disabled={send.isPending} onClick={() => send.mutate({ id: invoice.id }, {onSuccess:invalidate,onError:() => setMessage('Invoice could not be sent.')})}><Send className="h-3.5 w-3.5"/>Send</Button>}{!['paid','void','draft'].includes(invoice.status) && <Button variant="secondary" className="min-h-8 px-3 text-xs" onClick={() => { void navigator.clipboard?.writeText(publicUrl(invoice.publicPath)); setMessage('Public invoice URL copied.'); }}><Copy className="h-3.5 w-3.5"/>Copy URL</Button>}{!['paid','void'].includes(invoice.status) && <Button variant="ghost" className="min-h-8 px-3 text-xs" disabled={voidInvoice.isPending} onClick={() => voidInvoice.mutate({id:invoice.id},{onSuccess:invalidate,onError:() => setMessage('Invoice could not be voided.')})}>Void</Button>}</div></div>{invoice.payments.filter((p) => p.status === 'pending_review').map((p) => <div className="mt-3 flex flex-wrap items-center justify-between gap-2 rounded-lg bg-[#fff7df] p-3 text-xs" key={p.id}><span>Reference {p.paymentReference} · {money(p.amount, p.currency)} awaiting review</span><Button className="min-h-8 px-3 text-xs" disabled={verify.isPending} onClick={() => verify.mutate({id:invoice.id,paymentId:p.id,data:{approved:true,reviewNote:null}},{onSuccess:invalidate,onError:() => setMessage('Payment review could not be completed.')})}><ShieldCheck className="h-3.5 w-3.5"/>Verify payment</Button></div>)}</article>) : <EmptyState title="No invoices yet" description="Create a draft to issue a customer-safe invoice URL."/>}</section></div></div></AppShell>;
}