import { type FormEvent, useEffect, useState } from 'react';
import { CheckCircle2, CreditCard, FileText, LoaderCircle } from 'lucide-react';
import { useParams } from 'wouter';
import { getGetPublicInvoiceQueryKey, useCreatePublicInvoiceWhopCheckout, useGetPublicInvoice, useSubmitInvoicePaymentReference, useVerifyPublicInvoiceWhopPayment } from '@workspace/api-client-react';
import { useQueryClient } from '@tanstack/react-query';
import { Button, ErrorState, LoadingState, Notice, SubmitButton } from '@/components/primitives';
import { money } from '@/lib/format';

const input = 'mt-2 h-11 w-full rounded-lg border border-[#d9d2c4] bg-[#f7f4ed] px-3 text-sm outline-none focus:border-[#bca26a]';
export default function PublicInvoice() {
  const { token = '' } = useParams<{token:string}>(); const queryClient = useQueryClient(); const invoice = useGetPublicInvoice(token, { query: { queryKey: getGetPublicInvoiceQueryKey(token), retry: false } }); const submit = useSubmitInvoicePaymentReference(); const whopCheckout = useCreatePublicInvoiceWhopCheckout(); const whopVerify = useVerifyPublicInvoiceWhopPayment(); const [reference,setReference] = useState(''); const [sender,setSender] = useState(''); const [message,setMessage] = useState(''); const [whopMessage,setWhopMessage] = useState('');
  useEffect(() => {
    if (new URLSearchParams(window.location.search).get('whop') !== 'return' || !token) return;
    window.history.replaceState({}, document.title, window.location.pathname);
    whopVerify.mutate({ token, data: {} }, {
      onSuccess: (result) => {
        setWhopMessage(result.paymentMessage);
        void queryClient.invalidateQueries({ queryKey: getGetPublicInvoiceQueryKey(token) });
      },
      onError: () => setWhopMessage('Whop has not reported a completed payment yet. Use Check payment again or retry checkout.'),
    });
  }, [queryClient, token]);
  if (invoice.isLoading) return <main className="grid min-h-[100dvh] place-items-center bg-[#f5f1e8] px-5"><div className="w-full max-w-md"><LoadingState label="Loading invoice"/></div></main>;
  if (invoice.isError || !invoice.data) return <main className="grid min-h-[100dvh] place-items-center bg-[#f5f1e8] px-5"><ErrorState onRetry={() => void invoice.refetch()}/></main>;
  const value = invoice.data;
  const onSubmit = (e: FormEvent) => { e.preventDefault(); submit.mutate({token,data:{amount: Math.max(0, value.total - value.amountPaid),paymentReference:reference,senderName:sender || null}}, {onSuccess:() => {setMessage('Your reference was submitted for merchant review. This does not confirm payment capture.');setReference('');},onError:() => setMessage('The payment reference could not be submitted. Check the reference and remaining amount.')}); };
  return <main className="noise min-h-[100dvh] bg-[#f5f1e8] px-5 py-10 text-[#182333]"><section className="mx-auto max-w-[640px] rounded-2xl border border-[#d9d2c4] bg-[#fbfaf6] p-6 shadow-[0_18px_38px_rgba(31,43,56,.07)] md:p-8"><header className="flex justify-between"><div><p className="font-mono text-xs">TS / COMMERCE</p><p className="mt-3 font-mono text-sm text-[#697687]">{value.invoiceNumber}</p></div><FileText className="h-7 w-7 text-[#a2772e]"/></header><h1 className="mt-5 text-3xl font-extrabold tracking-[-.06em]">Invoice for {value.customerName}</h1>{value.dueDate && <p className="mt-2 text-sm text-[#697687]">Due {value.dueDate}</p>}<div className="mt-6 divide-y divide-[#ded8cd] border-y border-[#ded8cd]">{value.lines.map((line) => <div className="flex justify-between py-3 text-sm" key={line.id}><span>{line.description} <span className="text-[#697687]">× {line.quantity}</span></span><b>{money(line.lineTotal,value.currency)}</b></div>)}</div><div className="ml-auto mt-5 max-w-xs space-y-2 text-sm"><p className="flex justify-between"><span>Subtotal</span><span>{money(value.subtotal,value.currency)}</span></p>{value.discountAmount > 0 && <p className="flex justify-between"><span>Discount</span><span>−{money(value.discountAmount,value.currency)}</span></p>}<p className="flex justify-between"><span>Tax</span><span>{money(value.taxAmount,value.currency)}</span></p><p className="flex justify-between"><span>Shipping</span><span>{money(value.shippingAmount,value.currency)}</span></p><p className="flex justify-between border-t pt-2 text-lg font-extrabold"><span>Total</span><span>{money(value.total,value.currency)}</span></p></div>{value.notes && <p className="mt-6 text-sm leading-6 text-[#697687]">{value.notes}</p>}{value.terms && <p className="mt-3 text-xs leading-5 text-[#697687]">Terms: {value.terms}</p>}
   {value.status !== 'paid' && value.status !== 'void' && <><div className="mt-7 rounded-xl border border-[#b8d6ca] bg-[#eff8f3] p-4"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-extrabold">Pay online with Whop</h2><p className="mt-1 text-xs leading-5 text-[#2e6957]">Complete payment in Whop’s hosted checkout. The invoice changes only after TS Commerce verifies the provider payment.</p></div><Button disabled={whopCheckout.isPending} onClick={() => whopCheckout.mutate({ token }, { onSuccess: (result) => window.location.assign(result.purchaseUrl), onError: () => setWhopMessage('Hosted checkout could not be opened. You can submit an offline reference below.') })}>{whopCheckout.isPending ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <CreditCard className="h-4 w-4" />}Pay {money(Math.max(0, value.total - value.amountPaid), value.currency)}</Button></div>{whopMessage && <div className="mt-4"><Notice tone={whopMessage.includes('not reported') || whopMessage.includes('could not') ? 'danger' : 'success'} title="Whop payment">{whopMessage}</Notice><Button variant="secondary" className="mt-3" disabled={whopVerify.isPending} onClick={() => whopVerify.mutate({ token, data: {} }, { onSuccess: (result) => { setWhopMessage(result.paymentMessage); void queryClient.invalidateQueries({ queryKey: getGetPublicInvoiceQueryKey(token) }); }, onError: () => setWhopMessage('Whop has not reported a completed payment yet.') })}>{whopVerify.isPending ? 'Checking…' : 'Check payment again'}</Button></div>}</div><form onSubmit={onSubmit} className="mt-5 rounded-xl border border-[#dfc27a] bg-[#fff7df] p-4"><h2 className="font-extrabold">Submit payment reference</h2><p className="mt-1 text-xs leading-5 text-[#765817]">For offline payments, tell the merchant about your transfer. This remains a pending review record and does not claim online capture.</p><label className="mt-3 block text-sm font-bold">Payment reference<input value={reference} onChange={e=>setReference(e.target.value)} required minLength={2} maxLength={240} className={input}/></label><label className="mt-3 block text-sm font-bold">Sender name <span className="font-normal">(optional)</span><input value={sender} onChange={e=>setSender(e.target.value)} maxLength={160} className={input}/></label><SubmitButton loading={submit.isPending}>Submit for review</SubmitButton></form></>}{message && <div className="mt-5"><Notice tone={message.startsWith('The')?'danger':'success'} title="Payment reference">{message}</Notice></div>}{value.status === 'paid' && <div className="mt-6 flex gap-2 rounded-xl bg-[#eff8f3] p-4 text-sm text-[#2e6957]"><CheckCircle2 className="h-5 w-5"/>This invoice has been paid.</div>}</section></main>;
}