import { type ReactNode } from 'react';
import { ArrowRight, Banknote, Globe2, LockKeyhole, ReceiptText, ShieldCheck, Sparkles, Store, TimerReset } from 'lucide-react';
import { Link } from 'wouter';
import { getHealthCheckQueryKey, useHealthCheck } from '@workspace/api-client-react';
import { Logo, PublicHeader } from '@/components/app-shell';

export default function Landing() {
  const health = useHealthCheck({ query: { queryKey: getHealthCheckQueryKey(), retry: false, staleTime: 30000 } });
  return <div className="min-h-[100dvh] overflow-hidden bg-[#f5f1e8] text-[#182333]">
    <PublicHeader />
    <main>
      <section className="relative mx-auto max-w-[1440px] px-5 pb-20 pt-16 md:px-10 md:pb-28 md:pt-24">
        <div className="pointer-events-none absolute -right-44 -top-32 h-[500px] w-[500px] rounded-full border-[70px] border-[#d6aa46]/15" /><div className="pointer-events-none absolute right-16 top-24 h-2 w-2 rounded-full bg-[#d6aa46]" />
        <div className="max-w-4xl"><p className="font-mono text-[11px] uppercase tracking-[.18em] text-[#a2772e]">Commerce, kept clear.</p><h1 className="mt-6 text-[clamp(3.4rem,9vw,8.2rem)] font-extrabold leading-[.94] tracking-[-.085em]">Know what’s<br /><span className="text-[#9b752e]">yours.</span> Know why.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-[#536174] md:text-xl">TS Commerce gives independent merchants a clean ledger for every sale, every held fee, and every next step.</p><div className="mt-9 flex flex-wrap items-center gap-3"><Link href="/sign-up" className="inline-flex items-center gap-3 rounded-lg bg-[#182333] px-5 py-3.5 text-sm font-extrabold text-[#f8f3e8] shadow-[0_12px_26px_rgba(24,35,51,.18)] hover:bg-[#25354a]" data-testid="link-hero-sign-up">Open your workspace <ArrowRight className="h-4 w-4" /></Link><Link href="/sign-in" className="rounded-lg border border-[#cfc7b8] bg-[#fbfaf6] px-5 py-3.5 text-sm font-extrabold text-[#182333] hover:border-[#bca26a]" data-testid="link-hero-sign-in">Sign in</Link></div></div>
        <div className="mt-20 grid gap-4 border-t border-[#d9d2c4] pt-5 text-xs text-[#697687] sm:grid-cols-3"><div className="flex items-center gap-2"><Globe2 className="h-4 w-4 text-[#a2772e]" />Built for commerce across borders</div><div className="flex items-center gap-2"><LockKeyhole className="h-4 w-4 text-[#a2772e]" />Balances that explain themselves</div><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-[#a2772e]" />A calm place to run your business</div></div>
      </section>
      <section className="bg-[#182333] px-5 py-20 text-[#f8f3e8] md:px-10 md:py-28"><div className="mx-auto grid max-w-[1240px] gap-14 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="font-mono text-[11px] uppercase tracking-[.18em] text-[#d6aa46]">The daily read</p><h2 className="mt-5 max-w-lg text-4xl font-extrabold leading-[1.02] tracking-[-.065em] md:text-6xl">A financial control room that speaks plainly.</h2></div><div className="grid gap-8 sm:grid-cols-2"><div className="border-l border-[#526174] pl-5"><Banknote className="h-5 w-5 text-[#d6aa46]" /><h3 className="mt-5 text-lg font-extrabold">Available means available.</h3><p className="mt-2 text-sm leading-6 text-[#aab6c2]">See what can move today, separated from what is still settling.</p></div><div className="border-l border-[#526174] pl-5"><ReceiptText className="h-5 w-5 text-[#d6aa46]" /><h3 className="mt-5 text-lg font-extrabold">Held is never hidden.</h3><p className="mt-2 text-sm leading-6 text-[#aab6c2]">Platform fees are shown as a deliberate line in the ledger, not a surprise.</p></div></div></div></section>
      <section className="ledger-grid px-5 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-[1240px]"><div className="flex flex-wrap items-end justify-between gap-8"><div><p className="font-mono text-[11px] uppercase tracking-[.18em] text-[#a2772e]">One operating rhythm</p><h2 className="mt-4 text-4xl font-extrabold tracking-[-.06em] md:text-5xl">Less guessing.<br />More shipping.</h2></div><p className="max-w-sm text-sm leading-6 text-[#697687]">From first payout to monthly subscription, the important context stays in the same place.</p></div><div className="mt-14 grid gap-px overflow-hidden rounded-2xl border border-[#d2cabb] bg-[#d2cabb] md:grid-cols-3"><InfoBlock index="01" icon={<Store />} title="Open your shop" text="Start with a workspace that feels like yours, not a spreadsheet someone handed you." /><InfoBlock index="02" icon={<TimerReset />} title="Watch the clock" text="Warnings and subscription days are visible early enough to do something about them." /><InfoBlock index="03" icon={<Sparkles />} title="Keep momentum" text="Move from question to action without hunting through settings or support threads." /></div></div></section>
      <section className="px-5 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-[1240px] rounded-2xl bg-[#e9e1cd] px-6 py-12 md:px-14 md:py-16"><div className="grid gap-10 md:grid-cols-[1fr_auto] md:items-center"><div><p className="font-mono text-[11px] uppercase tracking-[.18em] text-[#8a6826]">A better baseline</p><h2 className="mt-4 max-w-2xl text-3xl font-extrabold leading-tight tracking-[-.06em] md:text-5xl">Your numbers should lower your pulse, not raise it.</h2></div><Link href="/sign-up" className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#182333] px-5 py-3.5 text-sm font-extrabold text-[#f8f3e8] hover:bg-[#25354a]" data-testid="link-bottom-sign-up">Get started <ArrowRight className="h-4 w-4" /></Link></div></div></section>
    </main>
    <footer className="border-t border-[#d9d2c4] px-5 py-7 md:px-10"><div className="mx-auto flex max-w-[1440px] flex-wrap items-center justify-between gap-5"><Logo /><div className="flex items-center gap-4 text-xs text-[#697687]"><span data-testid="status-health">{health.data?.status === 'ok' ? 'Service online' : 'Independent commerce infrastructure'}</span><span>© 2025 TS Commerce</span></div></div></footer>
  </div>;
}

function InfoBlock({ index, icon, title, text }: { index: string; icon: ReactNode; title: string; text: string }) {
  return <div className="bg-[#fbfaf6] p-7 md:p-9"><div className="flex items-center justify-between text-[#a2772e]"><span className="font-mono text-xs">{index}</span>{icon}</div><h3 className="mt-12 text-xl font-extrabold tracking-[-.04em]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#697687]">{text}</p></div>;
}