import { type ReactNode } from 'react';
import { Activity, ArrowRight, Banknote, ChartNoAxesCombined, CircleDot, Globe2, LockKeyhole, ReceiptText, ShieldCheck, Sparkles, Store, TimerReset, WalletCards } from 'lucide-react';
import { Link } from 'wouter';
import { getHealthCheckQueryKey, useHealthCheck } from '@workspace/api-client-react';
import { Logo, PublicHeader } from '@/components/app-shell';

export default function Landing() {
  const health = useHealthCheck({ query: { queryKey: getHealthCheckQueryKey(), retry: false, staleTime: 30000 } });
  return <div className="noise min-h-[100dvh] overflow-hidden bg-background text-foreground">
    <PublicHeader />
    <main>
       <section className="relative mx-auto max-w-[1440px] px-5 pb-20 pt-16 md:px-10 md:pb-28 md:pt-24">
         <div className="pointer-events-none absolute -right-48 -top-36 h-[560px] w-[560px] rounded-full border-[1px] border-accent/25 after:absolute after:inset-8 after:rounded-full after:border after:border-accent/15" /><div className="pointer-events-none absolute right-24 top-28 h-2 w-2 rounded-full bg-accent shadow-[0_0_0_7px_hsl(var(--accent)/.12)]" />
         <div className="relative grid gap-14 lg:grid-cols-[1.15fr_.85fr] lg:items-end"><div className="max-w-4xl"><p className="studio-kicker">A marketplace built to move commerce forward.</p><h1 className="studio-display mt-6 text-[clamp(3.6rem,9vw,8.4rem)] leading-[.88]">Know what’s<br /><em>yours.</em> Know why.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-muted-foreground md:text-xl">Lunavo is a global commerce ecosystem where shoppers discover promoted products and merchants run stores, payments, inventory, fulfillment, marketing, and AI from one serious operating system.</p><div className="mt-9 flex flex-wrap items-center gap-3"><Link href="/general-store" className="inline-flex items-center gap-3 rounded-[11px] border border-border bg-card px-5 py-3.5 text-sm font-extrabold text-foreground hover:border-accent">Shop the General Store <ArrowRight className="h-4 w-4" /></Link><Link href="/sign-up" className="inline-flex items-center gap-3 rounded-[11px] bg-primary px-5 py-3.5 text-sm font-extrabold text-primary-foreground shadow-[0_12px_26px_rgba(31,43,56,.18)] hover:bg-[hsl(207_25%_24%)]" data-testid="link-hero-sign-up">Start selling <ArrowRight className="h-4 w-4" /></Link><Link href="/sign-in" className="rounded-[11px] border border-border bg-card px-5 py-3.5 text-sm font-extrabold text-foreground hover:border-accent" data-testid="link-hero-sign-in">Sign in</Link></div></div>
           <div className="studio-card relative overflow-hidden rounded-[18px] p-5 md:p-6" data-testid="panel-landing-ledger"><div className="flex items-center justify-between border-b border-border pb-4"><div><p className="studio-kicker !text-[9px] !text-muted-foreground">A quieter control room</p><p className="mt-1 text-sm font-extrabold">Your operating signal</p></div><CircleDot className="h-4 w-4 text-accent" /></div><div className="mt-5 space-y-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-[9px] bg-[hsl(var(--accent)/.12)] text-accent"><WalletCards className="h-4 w-4" /></span><div className="min-w-0 flex-1"><p className="text-xs font-extrabold">Available funds</p><p className="mt-0.5 text-[11px] text-muted-foreground">Ready to move when you are</p></div><span className="font-mono text-xs text-[#2f6958]">clear</span></div><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-[9px] bg-[#e1ebee] text-[#316071]"><Activity className="h-4 w-4" /></span><div className="min-w-0 flex-1"><p className="text-xs font-extrabold">Settlement activity</p><p className="mt-0.5 text-[11px] text-muted-foreground">Sales, holds, and releases in order</p></div><span className="font-mono text-xs text-[#316071]">live</span></div><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-[9px] bg-[#f7edd2] text-[#85601b]"><ChartNoAxesCombined className="h-4 w-4" /></span><div className="min-w-0 flex-1"><p className="text-xs font-extrabold">Next best action</p><p className="mt-0.5 text-[11px] text-muted-foreground">Context before a decision</p></div><span className="font-mono text-xs text-[#85601b]">ready</span></div></div><div className="mt-6 flex items-center gap-2 border-t border-border pt-4 text-[10px] text-muted-foreground"><span className="h-1.5 w-1.5 rounded-full bg-[#2f6958]" /> Historical money stays in its recorded currency.</div></div>
        </div>
        <div className="mt-20 grid gap-4 border-t border-[#d9d2c4] pt-5 text-xs text-[#697687] sm:grid-cols-3"><div className="flex items-center gap-2"><Globe2 className="h-4 w-4 text-[#c85d3f]" />Built for commerce across borders</div><div className="flex items-center gap-2"><LockKeyhole className="h-4 w-4 text-[#c85d3f]" />Balances that explain themselves</div><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-[#c85d3f]" />A calm place to run your business</div></div>
      </section>
       <section className="bg-primary px-5 py-20 text-primary-foreground md:px-10 md:py-28"><div className="mx-auto grid max-w-[1240px] gap-14 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="studio-kicker !text-[#e17d5d]">The daily read</p><h2 className="mt-5 max-w-lg text-4xl font-extrabold leading-[1.02] tracking-[-.065em] md:text-6xl">A financial control room that speaks plainly.</h2></div><div className="grid gap-8 sm:grid-cols-2"><div className="border-l border-primary-foreground/25 pl-5"><Banknote className="h-5 w-5 text-[#e17d5d]" /><h3 className="mt-5 text-lg font-extrabold">Available means available.</h3><p className="mt-2 text-sm leading-6 text-primary-foreground/65">See what can move today, separated from what is still settling.</p></div><div className="border-l border-primary-foreground/25 pl-5"><ReceiptText className="h-5 w-5 text-[#e17d5d]" /><h3 className="mt-5 text-lg font-extrabold">Held is never hidden.</h3><p className="mt-2 text-sm leading-6 text-primary-foreground/65">Platform fees are shown as a deliberate line in the ledger, not a surprise.</p></div></div></div></section>
       <section className="ledger-grid px-5 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-[1240px]"><div className="flex flex-wrap items-end justify-between gap-8"><div><p className="studio-kicker">One operating rhythm</p><h2 className="mt-4 text-4xl font-extrabold tracking-[-.06em] md:text-5xl">Less guessing.<br />More shipping.</h2></div><p className="max-w-sm text-sm leading-6 text-muted-foreground">From first payout to monthly subscription, the important context stays in the same place.</p></div><div className="mt-14 grid gap-px overflow-hidden rounded-[18px] border border-border bg-border md:grid-cols-3"><InfoBlock index="01" icon={<Store />} title="Open your shop" text="Start with a workspace that feels like yours, not a spreadsheet someone handed you." /><InfoBlock index="02" icon={<TimerReset />} title="Watch the clock" text="Warnings and subscription days are visible early enough to do something about them." /><InfoBlock index="03" icon={<Sparkles />} title="Keep momentum" text="Move from question to action without hunting through settings or support threads." /></div></div></section>
       <section className="px-5 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-[1240px] border border-[hsl(var(--accent)/.3)] bg-[hsl(var(--accent)/.1)] px-6 py-12 shadow-[0_18px_40px_rgba(31,43,56,.06)] md:px-14 md:py-16"><div className="grid gap-10 md:grid-cols-[1fr_auto] md:items-center"><div><p className="studio-kicker">A better baseline</p><h2 className="mt-4 max-w-2xl text-3xl font-extrabold leading-tight tracking-[-.06em] md:text-5xl">Your numbers should lower your pulse, not raise it.</h2><p className="mt-4 max-w-xl text-sm leading-6 text-muted-foreground">A clear place for the work between the sale and the bank account.</p></div><Link href="/sign-up" className="inline-flex items-center justify-center gap-2 rounded-[11px] bg-primary px-5 py-3.5 text-sm font-extrabold text-primary-foreground hover:bg-[hsl(207_25%_24%)]" data-testid="link-bottom-sign-up">Get started <ArrowRight className="h-4 w-4" /></Link></div></div></section>
    </main>
       <footer className="border-t border-border px-5 py-7 md:px-10"><div className="mx-auto flex max-w-[1440px] flex-wrap items-center justify-between gap-5"><Logo /><div className="flex items-center gap-4 text-xs text-muted-foreground"><span data-testid="status-health">{health.data?.status === 'ok' ? 'Service online' : 'Independent commerce infrastructure'}</span><span>© 2026 Lunavo</span></div></div></footer>
  </div>;
}

function InfoBlock({ index, icon, title, text }: { index: string; icon: ReactNode; title: string; text: string }) {
  return <div className="bg-card p-7 md:p-9"><div className="flex items-center justify-between text-accent"><span className="font-mono text-xs">{index}</span>{icon}</div><h3 className="mt-12 text-xl font-extrabold tracking-[-.04em]">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></div>;
}
