import { ArrowUpRight, CheckCircle2, Globe2, ShieldCheck, Sparkles } from "lucide-react";
import { LunavoApplicationShell } from "../components/lunavo-application-shell";

const surfaces: Record<string,{title:string;subtitle:string;eyebrow:string;items:string[]}>={
 analytics:{title:"Analytics",subtitle:"Turn commerce activity into decisions without inventing numbers.",eyebrow:"COMMERCE INTELLIGENCE",items:["Sales and order trends","Store and product performance","Customer cohorts and retention","Marketing attribution","Exportable operational reporting"]},
 marketing:{title:"Marketing",subtitle:"Coordinate campaigns, offers and customer journeys from the same operating layer.",eyebrow:"GROWTH",items:["Campaigns and promotions","Discount rules","Customer segments","Lifecycle messaging","Performance measurement"]},
 shipping:{title:"Shipping",subtitle:"Configure fulfillment from manual rates to carriers, tracking, pickup and international delivery.",eyebrow:"FULFILLMENT",items:["Shipping zones and rates","Carrier integrations","Automatic rates where supported","Tracking","Local delivery and pickup","International shipping"]},
 taxes:{title:"Taxes",subtitle:"Keep tax configuration attached to the order and settlement record.",eyebrow:"COMPLIANCE",items:["Tax regions and rules","Order tax calculation","Tax-inclusive and exclusive pricing","Reporting","Optional automation"]},
 domains:{title:"Domains",subtitle:"Manage the customer-facing addresses for every storefront.",eyebrow:"STOREFRONTS",items:["Custom domains","Domain verification","Store routing","SSL readiness","Store identity"]},
 integrations:{title:"Integrations",subtitle:"Connect external services without making them the source of truth for Lunavo.",eyebrow:"ECOSYSTEM",items:["Payment rail adapters","Shipping providers","Tax providers","Commerce integrations","Webhooks and event delivery"]},
 developer:{title:"API & Webhooks",subtitle:"Give merchants controlled programmatic access with scoped credentials and observable events.",eyebrow:"DEVELOPER",items:["Scoped API keys","Key rotation","Webhook secrets","Usage limits","API usage logs","Developer documentation"]},
 "store-builder":{title:"Store Builder",subtitle:"Create storefront experiences while keeping commerce logic centralized.",eyebrow:"EXPERIENCE",items:["Pages and navigation","Themes","Branding","Product presentation","Responsive storefronts","Custom domains"]},
 themes:{title:"Themes",subtitle:"A consistent design system for every merchant storefront.",eyebrow:"DESIGN SYSTEM",items:["Theme library","Brand controls","Typography and layout","Responsive previews","Store-specific customization"]},
 "digital-products":{title:"Digital Products",subtitle:"Sell downloadable and access-controlled digital goods.",eyebrow:"DIGITAL COMMERCE",items:["Digital catalogues","Secure delivery","Access records","Customer entitlements","Order linkage"]},
 courses:{title:"Courses",subtitle:"Build and sell structured learning products inside the commerce platform.",eyebrow:"LEARNING",items:["Course catalogue","Lessons and modules","Enrollment","Access control","Progress"]},
 memberships:{title:"Memberships",subtitle:"Package recurring access and benefits around customers.",eyebrow:"CUSTOMER ACCESS",items:["Membership plans","Entitlements","Recurring access","Customer status","Access history"]},
 services:{title:"Services",subtitle:"Sell services with the same catalogue, order and payment foundation.",eyebrow:"SERVICE COMMERCE",items:["Service catalogue","Pricing","Availability","Order linkage","Customer records"]},
 bookings:{title:"Bookings",subtitle:"Coordinate appointments and availability without separating them from commerce.",eyebrow:"SCHEDULING",items:["Availability","Appointments","Customer details","Booking status","Notifications"]},
 events:{title:"Events",subtitle:"Create ticketed experiences with commerce-grade order records.",eyebrow:"EVENT COMMERCE",items:["Events","Ticket types","Capacity","Attendee records","Order linkage"]},
 subscriptions:{title:"Subscriptions",subtitle:"Manage recurring commercial relationships with explicit billing states.",eyebrow:"RECURRING COMMERCE",items:["Plans","Subscription lifecycle","Renewals","Cancellation","Entitlements","Payment state"]},
 marketplace:{title:"Marketplace",subtitle:"Give merchants an optional channel to participate in the Lunavo marketplace.",eyebrow:"MULTI-VENDOR",items:["Merchant participation","Product listing fees","Marketplace subscription","Discovery","Order attribution","Marketplace reporting"]},
 invoices:{title:"Invoices",subtitle:"Create and track commercial invoices with payment state tied to real transactions.",eyebrow:"BILLING",items:["Invoice lifecycle","Line items","Tax and shipping","Payment state","Refund linkage"]},
 refunds:{title:"Refunds & disputes",subtitle:"Keep refunds, reversals and disputes traceable to their originating payment records.",eyebrow:"PAYMENT OPERATIONS",items:["Refund requests","Partial refunds","Provider evidence","Disputes","Chargebacks","Reconciliation exceptions"]},
};

export default function LunavoSurfacePage({surface}:{surface:keyof typeof surfaces}){const s=surfaces[surface];return <LunavoApplicationShell title={s.title} subtitle={s.subtitle}><section className="lunavo-hero-strip"><div><span className="lunavo-kicker">{s.eyebrow}</span><h2>{s.title}, built into the operating system.</h2><p>{s.subtitle}</p></div><button className="lunavo-button lunavo-button-primary">Configure <ArrowUpRight size={16}/></button></section><section className="lunavo-feature-grid">{s.items.map((x)=><article className="lunavo-feature-card" key={x}><div className="lunavo-metric-icon"><CheckCircle2 size={17}/></div><strong>{x}</strong><span>Designed as a first-class Lunavo capability.</span></article>)}</section><section className="lunavo-panel lunavo-integrity-panel"><div><ShieldCheck size={21}/><div><span className="lunavo-kicker">PLATFORM INTEGRITY</span><h3>Business rules remain authoritative.</h3><p>UI controls do not bypass authentication, permissions, payment verification, ledger integrity or provider reconciliation.</p></div></div><Globe2 size={22}/></section></LunavoApplicationShell>}

export function FrontierLabPage(){return <LunavoApplicationShell title="Frontier Lab" subtitle="Self-hosted intelligence for commerce workflows, bounded by platform controls."><section className="lunavo-hero-strip"><div><span className="lunavo-kicker">SELF-HOSTED INTELLIGENCE</span><h2>Intelligence that assists the operator—not the ledger.</h2><p>Local language, image and video capabilities can accelerate commerce work while financial authority stays deterministic.</p></div><Sparkles size={28}/></section><section className="lunavo-feature-grid">{["Product intelligence","Catalogue enrichment","Commerce analysis","Content generation","Image workflows","Video workflows","Local language runtime","Workflow assistance"].map(x=><article className="lunavo-feature-card" key={x}><div className="lunavo-metric-icon"><Sparkles size={17}/></div><strong>{x}</strong><span>Self-hosted capability surface with external API keys not required for core operation.</span></article>)}</section></LunavoApplicationShell>}
