import { useEffect, useMemo, useState } from 'react';
import { Link } from 'wouter';
import { CheckCircle2, ExternalLink, Megaphone, RefreshCw, Send, Unplug, Video } from 'lucide-react';
import { customFetch } from '@workspace/api-client-react';
import { AppShell } from '@/components/app-shell';
import { Badge, Button, LoadingState, Notice, SectionHeading } from '@/components/primitives';

type Provider={id:string|null;provider:string;label:string;configured:boolean;connected:boolean;accountName:string|null;status:string};
type Creative={id:string;platform:string;title:string;caption:string|null;status:string};
type CustomMedia={id:string;filename:string;mimeType:string;mediaType:string;byteSize:number;createdAt:string};
type Job={id:string;provider:string;caption:string|null;status:string;externalPostId:string|null;errorMessage:string|null;createdAt:string;publishedAt:string|null};

export default function SocialHub(){
 const [providers,setProviders]=useState<Provider[]>([]); const [creatives,setCreatives]=useState<Creative[]>([]); const [customMedia,setCustomMedia]=useState<CustomMedia[]>([]); const [jobs,setJobs]=useState<Job[]>([]); const [selected,setSelected]=useState(''); const [selectedMedia,setSelectedMedia]=useState(''); const [caption,setCaption]=useState(''); const [selectedProviders,setSelectedProviders]=useState<string[]>([]); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false);
 const load=async()=>{setLoading(true);try{const [p,c,j]=await Promise.all([customFetch<Provider[]>('/api/social/providers'),customFetch<{creatives:Creative[];customMedia:CustomMedia[]}>('/api/ads/generator/campaigns'),customFetch<Job[]>('/api/social/publish-jobs')]);setProviders(p);setCreatives((c.creatives??[]).filter(x=>x.status==='completed'));setCustomMedia(c.customMedia??[]);setJobs(j??[]);}catch(e){setMessage(e instanceof Error?e.message:'Social Hub could not be loaded.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const current=useMemo(()=>creatives.find(c=>c.id===selected)??null,[creatives,selected]);
 const media=useMemo(()=>customMedia.find(m=>m.id===selectedMedia)??null,[customMedia,selectedMedia]);
 const toggle=(provider:string)=>setSelectedProviders(v=>v.includes(provider)?v.filter(x=>x!==provider):[...v,provider]);
 const connect=async(provider:string)=>{try{const r=await customFetch<{authorizeUrl:string}>(`/api/social/connect/${provider}`);window.location.href=r.authorizeUrl}catch(e){setMessage(e instanceof Error?e.message:'Unable to start social connection.')}};
 const publish=async()=>{if(!selectedProviders.length){setMessage('Choose at least one connected social account.');return}if(!current&&!media){setMessage('Choose a generated creative or uploaded campaign media.');return}setBusy(true);try{const r=await customFetch<{message:string}>('/api/social/publish',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({providers:selectedProviders,creativeId:current?.id??null,adMediaAssetId:media?.id??null,caption:caption||(current?.caption??'')})});setMessage(r.message);await load()}catch(e){setMessage(e instanceof Error?e.message:'Publishing could not be queued.')}finally{setBusy(false)}};
 if(loading)return <AppShell><LoadingState label="Loading Social Hub"/></AppShell>;
 return <AppShell><div className="mx-auto max-w-[1240px]">
  <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#a2772e]">Social Hub</p><h1 className="mt-2 text-4xl font-extrabold tracking-[-.07em]">Publish your commerce content from one place.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#697687]">Connect supported social accounts, select generated or uploaded campaign media, edit the caption, and send one publish request to multiple providers. Every provider remains the source of truth for whether a post actually went live.</p></div><Link href="/ad-studio" className="inline-flex items-center gap-2 rounded-xl bg-[#182333] px-4 py-3 text-sm font-extrabold text-[#f8f3e8]"><Video className="h-4 w-4"/>Open Ad Studio</Link></div>
  {message&&<div className="mt-6"><Notice title="Social Hub">{message}</Notice></div>}
  <section className="mt-8"><SectionHeading eyebrow="Connect" title="Social accounts" description="Connections are optional. Providers that are not configured remain unavailable instead of pretending to be connected."/><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{providers.map(p=><article key={p.provider} className="rounded-2xl border border-[#d9d2c4] bg-[#fbfaf6] p-5"><div className="flex items-center justify-between"><p className="font-extrabold">{p.label}</p><Badge tone={p.connected?'success':p.configured?'warning':'neutral'}>{p.connected?'Connected':p.configured?'Ready':'Not configured'}</Badge></div><p className="mt-2 text-xs text-[#697687]">{p.accountName||'No account connected'}</p><div className="mt-4">{p.connected?<button onClick={()=>toggle(p.provider)} className={'inline-flex w-full items-center justify-center gap-2 rounded-xl px-3 py-2 text-xs font-extrabold '+(selectedProviders.includes(p.provider)?'bg-[#d6aa46] text-[#182333]':'bg-[#182333] text-[#f8f3e8]')}><CheckCircle2 className="h-3.5 w-3.5"/>{selectedProviders.includes(p.provider)?'Selected for publishing':'Select for publishing'}</button>:<button onClick={()=>void connect(p.provider)} disabled={!p.configured} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#182333] px-3 py-2 text-xs font-extrabold text-[#f8f3e8] disabled:opacity-40"><ExternalLink className="h-3.5 w-3.5"/>Connect</button>}</div>{p.connected&&p.id&&<button onClick={()=>customFetch(`/api/social/connections/${p.id}`,{method:'DELETE'}).then(()=>load()).catch(()=>setMessage('Disconnect failed.'))} className="mt-2 inline-flex w-full items-center justify-center gap-2 rounded-xl border border-[#d9d2c4] px-3 py-2 text-xs font-extrabold text-[#697687]"><Unplug className="h-3.5 w-3.5"/>Disconnect</button>}</article>)}</div></section>
  <section className="mt-8 rounded-2xl border border-[#bfd6dc] bg-[#eef7f8] p-6"><div className="flex items-center gap-3"><Megaphone className="h-5 w-5 text-[#315e6c]"/><div><p className="font-extrabold text-[#182333]">One-click publishing</p><p className="mt-1 text-xs leading-5 text-[#477563]">Select multiple connected providers once, then create publish jobs from the same generated creative or uploaded campaign media. Actual live publication is only reported after provider confirmation.</p></div></div></section>
  <section className="mt-8"><SectionHeading eyebrow="Generated" title="Choose a generated ad" description="Generated TS Commerce ads are ready for selection and download."/><div className="mt-5 grid gap-3 md:grid-cols-3">{creatives.map(c=><button key={c.id} onClick={()=>{setSelected(c.id);setSelectedMedia('');setCaption(c.caption??'')}} className={'rounded-xl border p-4 text-left '+(selected===c.id?'border-[#a2772e] bg-[#fff8e5]':'border-[#d9d2c4] bg-[#fbfaf6]')}><div className="flex items-center justify-between"><div><p className="text-sm font-extrabold">{c.title}</p><p className="mt-1 text-xs text-[#697687]">{c.platform}</p></div><CheckCircle2 className={'h-4 w-4 '+(selected===c.id?'text-[#a2772e]':'text-transparent')}/></div></button>)}</div></section>
  <section className="mt-8"><SectionHeading eyebrow="External creative" title="Use your own uploaded image or video" description="This media does not need to originate from your store. It can be a separate campaign asset."/><div className="mt-5 grid gap-3 md:grid-cols-3">{customMedia.map(m=><button key={m.id} onClick={()=>{setSelectedMedia(m.id);setSelected('');setCaption('')}} className={'rounded-xl border p-4 text-left '+(selectedMedia===m.id?'border-[#315e6c] bg-[#eef7f8]':'border-[#d9d2c4] bg-[#fbfaf6]')}><div className="flex items-center justify-between"><div><p className="truncate text-sm font-extrabold">{m.filename}</p><p className="mt-1 text-xs text-[#697687]">{m.mediaType} · {(m.byteSize/1024/1024).toFixed(1)} MB</p></div><CheckCircle2 className={'h-4 w-4 '+(selectedMedia===m.id?'text-[#315e6c]':'text-transparent')}/></div></button>)}</div></section>
  <section className="mt-8"><div className="rounded-2xl border border-[#d9d2c4] bg-[#fbfaf6] p-5"><p className="text-sm font-extrabold">Caption</p><textarea value={caption} onChange={e=>setCaption(e.target.value)} rows={7} placeholder="Write or edit your social caption" className="mt-3 w-full rounded-xl border border-[#d9d2c4] bg-white p-3 text-sm outline-none"/><Button onClick={publish} disabled={busy||(!selected&&!selectedMedia)||!selectedProviders.length} className="mt-4 w-full">{busy?<><RefreshCw className="h-4 w-4 animate-spin"/>Queueing…</>:<><Send className="h-4 w-4"/>Publish to selected accounts</>}</Button></div></section>
  <section className="mt-8"><SectionHeading eyebrow="History" title="Publish jobs"/><div className="mt-4 space-y-2">{jobs.map(j=><div key={j.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#d9d2c4] bg-[#fbfaf6] p-4"><div><p className="text-sm font-extrabold">{j.provider}</p><p className="mt-1 text-xs text-[#697687]">{j.errorMessage||j.externalPostId||'Provider result pending'} · {new Date(j.createdAt).toLocaleString()}</p></div><Badge tone={j.status==='published'?'success':j.status==='failed'?'danger':'warning'}>{j.status}</Badge></div>)}{!jobs.length&&<p className="text-sm text-[#697687]">No publish jobs yet.</p>}</div></section>
 </div></AppShell>;
}
