import { useEffect,useState } from "react";
import { CreditCard, RefreshCw, ShieldCheck, XCircle } from "lucide-react";
import { customFetch } from "@workspace/api-client-react";
import { AppShell } from "@/components/app-shell";
import { Badge,Button,LoadingState,Notice } from "@/components/primitives";

export default function SubscriptionPortal(){
 const [token,setToken]=useState(()=>localStorage.getItem("lunavo_subscription_token")||""),[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState("");
 const load=async()=>{if(!token.trim()){setMessage("Enter the private subscription portal token supplied after signup.");return;}setLoading(true);setMessage("");try{setData(await customFetch<any>("/api/public/customer-subscriptions/portal?token="+encodeURIComponent(token.trim()),{responseType:"json"}));localStorage.setItem("lunavo_subscription_token",token.trim());}catch(e){setMessage(e instanceof Error?e.message:"Subscription portal could not be loaded.");}finally{setLoading(false);}};
 useEffect(()=>{if(token)void load();},[]);
 const pay=async()=>{try{const r=await customFetch<any>("/api/public/customer-subscriptions/pay",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token}),responseType:"json"});if(r.paymentUrl)window.location.assign(r.paymentUrl);else setMessage("No payment checkout is currently available.");}catch(e){setMessage(e instanceof Error?e.message:"Payment could not be prepared.");}};
 const cancel=async()=>{if(!confirm("Cancel this subscription?"))return;try{await customFetch("/api/public/customer-subscriptions/cancel",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token}),responseType:"json"});setMessage("Subscription cancelled.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Subscription could not be cancelled.");}};
 return <AppShell><div className="mx-auto max-w-3xl py-10"><section className="rounded-3xl border border-[#d9d2c4] bg-[#fbfaf6] p-7 shadow-[0_24px_70px_rgba(31,43,56,.08)] md:p-9"><div className="flex items-start justify-between gap-5"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#a2772e]">Private customer portal</p><h1 className="mt-2 text-3xl font-extrabold tracking-[-.06em]">Manage your subscription</h1><p className="mt-2 text-sm text-[#697687]">Your portal token is a bearer credential. Keep it private.</p></div><ShieldCheck className="h-7 w-7 text-[#315e6c]"/></div>
 <div className="mt-7 flex gap-3"><input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Paste your private portal token" className="h-12 flex-1 rounded-xl border border-[#d9d2c4] bg-white px-3"/><Button onClick={()=>void load()} disabled={loading}><RefreshCw className="h-4 w-4"/>{loading?"Loading…":"Open"}</Button></div>
 {message&&<div className="mt-5"><Notice title="Subscription portal" tone={/could not|unavailable|failed|required|not found/i.test(message)?"danger":"success"}>{message}</Notice></div>}
 {data&&<div className="mt-7 space-y-5"><div className="rounded-2xl bg-[#182333] p-6 text-[#f8f3e8]"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs text-[#b9c3cd]">{data.subscription.store_name}</p><h2 className="mt-1 text-2xl font-extrabold">{data.subscription.plan_name}</h2><p className="mt-2 text-sm text-[#b9c3cd]">{data.subscription.product_title}</p></div><Badge tone={data.subscription.status==="active"?"success":data.subscription.status==="past_due"?"warning":"danger"}>{data.subscription.status}</Badge></div><p className="mt-6 font-mono text-2xl font-black">{(Number(data.subscription.amount_minor)/100).toFixed(2)} {data.subscription.currency}</p><p className="mt-1 text-xs text-[#b9c3cd]">Next charge {new Date(data.subscription.next_charge_at).toLocaleString()}</p></div>
 {["pending_payment","past_due"].includes(data.subscription.status)&&<Button onClick={()=>void pay()} className="w-full"><CreditCard className="h-4 w-4"/>Make payment</Button>}
 {data.subscription.status!=="cancelled"&&data.subscription.status!=="expired"&&<Button variant="secondary" onClick={()=>void cancel()} className="w-full"><XCircle className="h-4 w-4"/>Cancel subscription</Button>}
 <div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-[#a2772e]">Billing history</p><div className="mt-3 space-y-2">{(data.attempts||[]).map((a:any)=><div key={a.attempt_number} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#d9d2c4] bg-white p-4"><div><p className="text-sm font-extrabold">Attempt #{a.attempt_number}</p><p className="text-xs text-[#697687]">{new Date(a.created_at).toLocaleString()}</p></div><Badge tone={a.status==="successful"?"success":a.status==="submitted"?"info":"warning"}>{a.status}</Badge></div>)}</div></div>
 </div>}
 </section></div></AppShell>;
}