import { FormEvent, useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { Copy, MapPin, Pencil, Plus, RefreshCw, Shield, UserPlus, Users } from 'lucide-react';
import {
  getGetTeamAccessQueryKey, getListTeamInvitationsQueryKey, getListTeamLocationsQueryKey, getListTeamMembershipsQueryKey, getListTeamRolesQueryKey,
  useCreateTeamInvitation, useCreateTeamLocation, useDisableTeamLocation, useDisableTeamMembership, useGetTeamAccess, useListTeamInvitations,
  useListTeamLocations, useListTeamMemberships, useListTeamRoles, useRevokeTeamInvitation, useRotateTeamInvitationLink, useSetDefaultTeamLocation,
  useUpdateTeamLocation, useUpdateTeamMembership,
} from '@workspace/api-client-react';
import type { TeamLocation } from '@workspace/api-client-react';
import { AppShell } from '@/components/app-shell';
import { Badge, Button, EmptyState, ErrorState, LoadingState, Notice, SectionHeading, SubmitButton } from '@/components/primitives';

const input = 'mt-1 w-full rounded-[10px] border border-[#d5cdbd] bg-[#f7f4ed] px-3 py-2.5 text-sm outline-none focus:border-[#a2772e]';
const teamKeys = [getGetTeamAccessQueryKey(), getListTeamLocationsQueryKey(), getListTeamRolesQueryKey(), getListTeamMembershipsQueryKey(), getListTeamInvitationsQueryKey()];
const safeJson = (value: string) => { try { return value.trim() ? JSON.parse(value) as Record<string, unknown> : {}; } catch { throw new Error('Address and contact must be valid JSON.'); } };

function ScopeChecks({ locations, value, onChange }: { locations: TeamLocation[]; value: string[]; onChange: (value: string[]) => void }) {
  return <fieldset><legend className="text-sm font-bold">Location scope <span className="font-normal text-[#697687]">(optional; leave clear for all locations)</span></legend><div className="mt-2 flex flex-wrap gap-3">{locations.filter((l) => l.isActive).map((location) => <label key={location.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value.includes(location.id)} onChange={(e) => onChange(e.target.checked ? [...value, location.id] : value.filter((id) => id !== location.id))} />{location.name}</label>)}</div></fieldset>;
}

function LocationForm({ location, onDone }: { location?: TeamLocation; onDone: () => void }) {
  const create = useCreateTeamLocation(); const update = useUpdateTeamLocation();
  const [name, setName] = useState(location?.name ?? ''); const [type, setType] = useState(location?.locationType ?? 'store');
  const [country, setCountry] = useState(location?.country ?? ''); const [currency, setCurrency] = useState(location?.currency ?? '');
  const [timezone, setTimezone] = useState(location?.timezone ?? Intl.DateTimeFormat().resolvedOptions().timeZone);
  const [address, setAddress] = useState(JSON.stringify(location?.address ?? {}, null, 2)); const [contact, setContact] = useState(JSON.stringify(location?.contact ?? {}, null, 2));
  const [fulfillment, setFulfillment] = useState(location?.supportsFulfillment ?? true); const [pos, setPos] = useState(location?.supportsPos ?? false); const [inventory, setInventory] = useState(location?.supportsInventory ?? true); const [error, setError] = useState('');
  const submit = (e: FormEvent) => { e.preventDefault(); setError(''); try { const data = { name, locationType: type || undefined, country: country.toUpperCase(), currency: currency.toUpperCase(), timezone, address: safeJson(address), contact: safeJson(contact), supportsFulfillment: fulfillment, supportsPos: pos, supportsInventory: inventory }; const mutation = location ? update : create; const variables = location ? { id: location.id, data } : { data }; mutation.mutate(variables as never, { onSuccess: onDone, onError: () => setError('Location could not be saved. Check your access and values.') }); } catch (err) { setError(err instanceof Error ? err.message : 'Invalid location details.'); } };
  const busy = create.isPending || update.isPending;
  return <form onSubmit={submit} className="mt-4 grid gap-3 rounded-xl border border-[#d9d2c4] bg-[#f7f4ed] p-4 md:grid-cols-2">
    <label className="text-sm font-bold">Location name<input required maxLength={160} value={name} onChange={(e) => setName(e.target.value)} className={input} /></label>
    <label className="text-sm font-bold">Type<input maxLength={64} value={type} onChange={(e) => setType(e.target.value)} className={input} placeholder="store, warehouse…" /></label>
    <label className="text-sm font-bold">Country<input required minLength={2} maxLength={3} value={country} onChange={(e) => setCountry(e.target.value)} className={input} placeholder="NG" /></label>
    <label className="text-sm font-bold">Currency<input required minLength={3} maxLength={3} value={currency} onChange={(e) => setCurrency(e.target.value)} className={input} placeholder="NGN" /></label>
    <label className="text-sm font-bold md:col-span-2">Timezone<input required maxLength={100} value={timezone} onChange={(e) => setTimezone(e.target.value)} className={input} placeholder="Africa/Lagos" /></label>
    <label className="text-sm font-bold">Address (JSON)<textarea value={address} onChange={(e) => setAddress(e.target.value)} className={`${input} min-h-24 font-mono text-xs`} /></label>
    <label className="text-sm font-bold">Contact (JSON)<textarea value={contact} onChange={(e) => setContact(e.target.value)} className={`${input} min-h-24 font-mono text-xs`} /></label>
    <div className="flex flex-wrap gap-4 text-sm md:col-span-2">{[[fulfillment,setFulfillment,'Fulfillment'],[pos,setPos,'POS'],[inventory,setInventory,'Inventory']].map(([checked, set, label]) => <label key={String(label)} className="flex items-center gap-2"><input type="checkbox" checked={checked as boolean} onChange={(e) => (set as (v:boolean)=>void)(e.target.checked)} />{String(label)}</label>)}</div>
    {error && <p role="alert" className="text-sm text-[#a33e38] md:col-span-2">{error}</p>}<div className="flex gap-2 md:col-span-2"><SubmitButton loading={busy}>{location ? 'Save location' : 'Create location'}</SubmitButton><Button type="button" variant="ghost" onClick={onDone}>Cancel</Button></div>
  </form>;
}

export default function Team() {
  const client = useQueryClient(); const access = useGetTeamAccess(); const locations = useListTeamLocations(); const roles = useListTeamRoles(); const memberships = useListTeamMemberships(); const invitations = useListTeamInvitations();
  const createInvite = useCreateTeamInvitation(); const revokeInvite = useRevokeTeamInvitation(); const rotateInvite = useRotateTeamInvitationLink(); const disableLocation = useDisableTeamLocation(); const defaultLocation = useSetDefaultTeamLocation(); const disableMember = useDisableTeamMembership(); const updateMember = useUpdateTeamMembership();
  const [editing, setEditing] = useState<TeamLocation | 'new' | null>(null); const [email, setEmail] = useState(''); const [roleId, setRoleId] = useState(''); const [inviteScope, setInviteScope] = useState<string[]>([]); const [inviteUrl, setInviteUrl] = useState<string | null>(null); const [message, setMessage] = useState('');
  const invalidate = () => void Promise.all(teamKeys.map((queryKey) => client.invalidateQueries({ queryKey })));
  const canTeam = !!access.data?.permissions.includes('team.manage'); const canLocations = !!access.data?.permissions.includes('locations.manage');
  const allLoading = access.isLoading || locations.isLoading || roles.isLoading || memberships.isLoading || invitations.isLoading;
  const anyError = access.isError || locations.isError || roles.isError || memberships.isError || invitations.isError;
  if (allLoading) return <AppShell><LoadingState label="Loading team and locations" /></AppShell>;
  if (anyError || !access.data || !locations.data || !roles.data || !memberships.data || !invitations.data) return <AppShell><ErrorState onRetry={invalidate} /></AppShell>;
  const mutationDone = (text: string) => { setMessage(text); invalidate(); };
  return <AppShell><div className="mx-auto max-w-[1180px] space-y-10">
    <SectionHeading eyebrow="Workspace controls" title="Team & locations" description="Manage access and operating locations using the merchant’s persisted workspace settings." action={<Button variant="secondary" onClick={invalidate}><RefreshCw className="h-4 w-4" />Refresh</Button>} />
    {message && <Notice tone="success" title="Updated" onDismiss={() => setMessage('')}>{message}</Notice>}
    <section className="rounded-2xl border border-[#d5cdbd] bg-[#fcfaf5] p-5"><div className="flex items-start gap-3"><Shield className="mt-1 h-5 w-5 text-[#a2772e]" /><div><h2 className="font-extrabold">Your current access</h2><p className="mt-1 text-sm text-[#697687]">Role: <strong>{access.data.role}</strong> · {access.data.locationIds === null ? 'All locations' : `${access.data.locationIds.length} assigned location(s)`}</p><div className="mt-3 flex flex-wrap gap-2">{access.data.permissions.length ? access.data.permissions.map((permission) => <Badge key={permission} tone="info">{permission}</Badge>) : <span className="text-sm text-[#697687]">No permissions are assigned.</span>}</div></div></div></section>
    <section><SectionHeading eyebrow="Operating footprint" title="Locations" description="Each location retains its own locale, contact record, and capabilities." action={canLocations ? <Button onClick={() => setEditing('new')}><Plus className="h-4 w-4" />Add location</Button> : <Badge tone="warning">locations.manage required</Badge>} />
      {editing === 'new' && <LocationForm onDone={() => { setEditing(null); mutationDone('Location saved.'); }} />}
      <div className="grid gap-4 md:grid-cols-2">{locations.data.length ? locations.data.map((location) => <article key={location.id} className="rounded-2xl border border-[#d5cdbd] bg-[#fcfaf5] p-5"><div className="flex justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-extrabold">{location.name}</h3>{location.isDefault && <Badge tone="brass">Default</Badge>}{!location.isActive && <Badge tone="danger">Disabled</Badge>}</div><p className="mt-1 text-sm text-[#697687]">{location.locationType} · {location.country} · {location.currency} · {location.timezone}</p><p className="mt-2 text-xs text-[#697687]">Capabilities: {['Fulfillment','POS','Inventory'].filter((x, i) => [location.supportsFulfillment, location.supportsPos, location.supportsInventory][i]).join(', ') || 'None'}</p></div><MapPin className="h-5 w-5 text-[#a2772e]" /></div>
        {canLocations && <div className="mt-4 flex flex-wrap gap-2"><Button variant="secondary" className="min-h-8 px-3 text-xs" onClick={() => setEditing(location)}><Pencil className="h-3.5 w-3.5" />Edit</Button>{!location.isDefault && location.isActive && <Button variant="ghost" className="min-h-8 px-3 text-xs" disabled={defaultLocation.isPending} onClick={() => defaultLocation.mutate({ id: location.id }, { onSuccess: () => mutationDone('Default location changed.') })}>Set default</Button>}{location.isActive && <Button variant="danger" className="min-h-8 px-3 text-xs" disabled={disableLocation.isPending} onClick={() => disableLocation.mutate({ id: location.id }, { onSuccess: () => mutationDone('Location disabled.') })}>Disable</Button>}</div>}
        {editing !== 'new' && editing?.id === location.id && <LocationForm location={location} onDone={() => { setEditing(null); mutationDone('Location saved.'); }} />}</article>) : <EmptyState title="No locations yet" description="Create the first operating location to scope staff access." />}</div></section>
    <section className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div><SectionHeading eyebrow="People" title="Staff memberships" description="Owners are protected from role changes and disable actions." />{memberships.data.length ? <div className="space-y-3">{memberships.data.map((member) => { const owner = member.roleKey === 'owner'; return <article key={member.id} className="rounded-xl border border-[#d9d2c4] bg-[#fcfaf5] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-mono text-xs font-bold">{member.clerkUserId}</p><p className="mt-1 text-xs text-[#697687]">{member.status} · {member.locationIds.length ? `${member.locationIds.length} scoped location(s)` : 'All locations'}</p></div><Badge tone={owner ? 'brass' : member.status === 'active' ? 'success' : 'neutral'}>{owner ? 'Owner protected' : member.roleKey}</Badge></div>{canTeam && !owner && <div className="mt-3 flex flex-wrap items-center gap-2"><select aria-label={`Role for ${member.clerkUserId}`} defaultValue={member.roleId} className="rounded-lg border border-[#d5cdbd] bg-[#f7f4ed] px-2 py-1.5 text-xs" onChange={(e) => updateMember.mutate({ id: member.id, data: { roleId: e.target.value, locationIds: member.locationIds } }, { onSuccess: () => mutationDone('Staff role updated.') })}>{roles.data.map((r) => <option key={r.id} value={r.id}>{r.name}</option>)}</select><Button variant="danger" className="min-h-8 px-3 text-xs" disabled={disableMember.isPending} onClick={() => disableMember.mutate({ id: member.id }, { onSuccess: () => mutationDone('Staff member disabled.') })}>Disable</Button></div>}</article>; })}</div> : <EmptyState title="No staff memberships" description="Accepted invitations will appear here." />}</div>
      <div><SectionHeading eyebrow="Policy" title="Roles & permissions" description="System roles define the permissions granted to staff." /> <div className="space-y-3">{roles.data.map((role) => <article key={role.id} className="rounded-xl border border-[#d9d2c4] bg-[#fcfaf5] p-4"><div className="flex justify-between gap-2"><h3 className="font-bold">{role.name}</h3>{role.isSystem && <Badge tone="neutral">System</Badge>}</div>{role.description && <p className="mt-1 text-xs text-[#697687]">{role.description}</p>}<p className="mt-2 text-xs text-[#536174]">{role.permissions.join(' · ') || 'No permissions'}</p></article>)}</div></div></section>
    <section><SectionHeading eyebrow="Access links" title="Invitations" description="Invitation links are generated once and are not emailed by TS Commerce." />{canTeam ? <form onSubmit={(e) => { e.preventDefault(); createInvite.mutate({ data: { email, roleId, locationIds: inviteScope } }, { onSuccess: (result) => { setInviteUrl(result.inviteUrl); setEmail(''); setInviteScope([]); mutationDone('Invitation created. No email was sent.'); }, onError: () => setMessage('Invitation could not be created.') }); }} className="grid gap-3 rounded-2xl border border-[#d5cdbd] bg-[#f7f4ed] p-4 md:grid-cols-2"><label className="text-sm font-bold">Email<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className={input} /></label><label className="text-sm font-bold">Role<select required value={roleId} onChange={(e) => setRoleId(e.target.value)} className={input}><option value="">Choose a role</option>{roles.data.filter((r) => r.key !== 'owner').map((r) => <option key={r.id} value={r.id}>{r.name}</option>)}</select></label><div className="md:col-span-2"><ScopeChecks locations={locations.data} value={inviteScope} onChange={setInviteScope} /></div><div className="md:col-span-2"><SubmitButton loading={createInvite.isPending}><UserPlus className="h-4 w-4" />Create invitation</SubmitButton></div></form> : <Notice tone="warning" title="Management unavailable">You need team.manage to create, revoke, or rotate invitations.</Notice>}
      {inviteUrl && <CopyableUrl value={inviteUrl} onDismiss={() => setInviteUrl(null)} />}
      <div className="mt-4 space-y-3">{invitations.data.length ? invitations.data.map((invitation) => <article key={invitation.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#d9d2c4] bg-[#fcfaf5] p-4"><div><p className="font-bold">{invitation.email} <span className="font-normal text-[#697687]">· {invitation.roleKey}</span></p><p className="mt-1 text-xs text-[#697687]">Expires {new Date(invitation.expiresAt).toLocaleString()} · {invitation.revokedAt ? 'revoked' : invitation.acceptedAt ? 'accepted' : 'pending'}</p></div>{canTeam && !invitation.revokedAt && !invitation.acceptedAt && <div className="flex gap-2"><Button variant="secondary" className="min-h-8 px-3 text-xs" disabled={rotateInvite.isPending} onClick={() => rotateInvite.mutate({ id: invitation.id }, { onSuccess: (r) => { setInviteUrl(r.inviteUrl); mutationDone('Invitation link rotated. No email was sent.'); } })}>Rotate link</Button><Button variant="danger" className="min-h-8 px-3 text-xs" disabled={revokeInvite.isPending} onClick={() => revokeInvite.mutate({ id: invitation.id }, { onSuccess: () => mutationDone('Invitation revoked.') })}>Revoke</Button></div>}</article>) : <EmptyState title="No invitations" description="Create a secure invitation link for a team member." />}</div></section>
  </div></AppShell>;
}

function CopyableUrl({ value, onDismiss }: { value: string; onDismiss: () => void }) { const [copied, setCopied] = useState(false); const absoluteValue = new URL(value, window.location.origin).toString(); return <Notice tone="info" title="Copy this invitation URL" onDismiss={onDismiss}><p>No email was sent. This link is displayed only now.</p><div className="mt-2 flex gap-2"><input aria-label="Invitation URL" readOnly value={absoluteValue} className="min-w-0 flex-1 rounded border border-[#bfd6dc] bg-white px-2 py-1 text-xs" /><Button type="button" variant="secondary" className="min-h-8 px-3 text-xs" onClick={() => void navigator.clipboard.writeText(absoluteValue).then(() => setCopied(true))}><Copy className="h-3.5 w-3.5" />{copied ? 'Copied' : 'Copy'}</Button></div></Notice>; }