
import { Router, type Request, type Response } from "express";
import { and, eq, sql } from "drizzle-orm";
import { createHash, randomBytes } from "node:crypto";
import { getAuth } from "../lib/auth-compat";
import { requirePermission } from "../lib/tenant-access";
import { db, merchantsTable, customersTable } from "@workspace/db";
import { emitDomainEvent } from "../lib/domain-events";

const router=Router();
const txt=(v:unknown,max:number)=>typeof v==="string"?v.trim().slice(0,max):"";
const mail=(v:unknown)=>txt(v,254).toLowerCase();
const visitorKey=(v:unknown)=>{const s=txt(v,120);return /^[A-Za-z0-9._:-]{8,120}$/.test(s)?s:null;};
const sha=(v:string)=>createHash("sha256").update(v).digest("hex");
async function publicStore(key:string){const [m]=await db.select({id:merchantsTable.id,publicStoreKey:merchantsTable.publicStoreKey}).from(merchantsTable).where(and(eq(merchantsTable.publicStoreKey,key),eq(merchantsTable.status,"active"))).limit(1);return m??null;}
async function merchantFor(req:Request){const userId=getAuth(req).userId;if(!userId)return null;const [m]=await db.select().from(merchantsTable).where(and(eq(merchantsTable.status,"active"),sql`(${merchantsTable.clerkUserId}=${userId} OR ${merchantsTable.localAuthUserId}=${userId})`)).limit(1);if(!m)return null;await requirePermission(userId,m.id,"team.manage");return m;}
function fail(res:Response,status:number,error:string){return res.status(status).json({error});}

router.post("/public/store/:merchantKey/cart/recovery",async(req,res):Promise<void>=>{
 const m=await publicStore(txt(req.params.merchantKey,120));if(!m){fail(res,404,"Store not found");return;}
 const sk=visitorKey(req.body?.sessionKey),customerEmail=mail(req.body?.customerEmail),customerName=txt(req.body?.customerName,160),currency=txt(req.body?.currency,3).toUpperCase(),subtotal=Number(req.body?.subtotal);
 if(!sk||!/^[A-Z]{3}$/.test(currency)||!Number.isFinite(subtotal)||subtotal<0){fail(res,400,"Cart identity, currency and subtotal are invalid");return;}
 const items=Array.isArray(req.body?.items)?req.body.items.slice(0,50).filter((x:unknown)=>x&&typeof x==="object"):[];
 let customerId:number|null=null;if(customerEmail){const [c]=await db.select({id:customersTable.id}).from(customersTable).where(and(eq(customersTable.merchantId,m.id),eq(customersTable.email,customerEmail))).limit(1);customerId=c?.id??null;}
 const token=randomBytes(32).toString("base64url");
 const result=await db.execute(sql`INSERT INTO abandoned_carts(merchant_id,customer_id,session_key,customer_email,customer_name,cart_snapshot,currency,subtotal_minor,recovery_token_hash,recovery_token_last4,last_activity_at,updated_at)
 VALUES(${m.id},${customerId},${sk},NULLIF(${customerEmail},''),NULLIF(${customerName},''),${JSON.stringify(items)}::jsonb,${currency},${Math.round(subtotal*100)},${sha(token)},${token.slice(-4)},now(),now())
 ON CONFLICT (merchant_id,session_key) WHERE status IN ('active','abandoned') DO UPDATE SET customer_id=EXCLUDED.customer_id,customer_email=EXCLUDED.customer_email,customer_name=EXCLUDED.customer_name,cart_snapshot=EXCLUDED.cart_snapshot,currency=EXCLUDED.currency,subtotal_minor=EXCLUDED.subtotal_minor,status='active',recovery_token_hash=EXCLUDED.recovery_token_hash,recovery_token_last4=EXCLUDED.recovery_token_last4,last_activity_at=now(),abandoned_at=NULL,recovered_at=NULL,updated_at=now() RETURNING id,status`);
 const row=result.rows[0] as any;if(!row){fail(res,500,"Cart recovery state could not be saved");return;}res.setHeader("Cache-Control","no-store");res.json({cartId:row.id,status:row.status,recoveryToken:token,recoveryUrl:`/checkout/${m.publicStoreKey}?recovery=${encodeURIComponent(token)}`});
});

router.get("/public/store/:merchantKey/cart/recovery/:token",async(req,res):Promise<void>=>{
 const m=await publicStore(txt(req.params.merchantKey,120));if(!m){fail(res,404,"Store not found");return;}const token=txt(req.params.token,200);if(token.length<20){fail(res,400,"Invalid recovery token");return;}
 const result=await db.execute(sql`SELECT id,cart_snapshot,currency,subtotal_minor,status,customer_name FROM abandoned_carts WHERE merchant_id=${m.id} AND recovery_token_hash=${sha(token)} LIMIT 1`);
 const row=result.rows[0] as any;if(!row){fail(res,404,"Recovery link is invalid or expired");return;}
 const changed=await db.execute(sql`UPDATE abandoned_carts SET status='recovered',recovered_at=COALESCE(recovered_at,now()),updated_at=now() WHERE id=${row.id} AND status IN ('active','abandoned') RETURNING id`);
 if(changed.rows.length)await emitDomainEvent(db,{merchantId:m.id,eventType:"cart.recovered",aggregateType:"abandoned_cart",aggregateId:String(row.id),actorType:"customer",source:"public_checkout",idempotencyKey:`cart-recovered:${row.id}`,payload:{cartId:String(row.id)},after:{status:"recovered"}});
 res.setHeader("Cache-Control","no-store");res.json({cartId:row.id,items:row.cart_snapshot,currency:row.currency,subtotal:Number(row.subtotal_minor)/100,customerName:row.customer_name,status:"recovered"});
});

router.get("/merchant/cart-recovery",async(req,res):Promise<void>=>{
 const m=await merchantFor(req);if(!m){fail(res,401,"Authentication required");return;}const status=txt(req.query.status,20);const clause=["active","abandoned","recovered","expired"].includes(status)?sql`AND status=${status}`:sql``;
 const result=await db.execute(sql`SELECT id,customer_email,customer_name,currency,subtotal_minor,status,last_activity_at,abandoned_at,recovered_at,created_at,updated_at FROM abandoned_carts WHERE merchant_id=${m.id} ${clause} ORDER BY COALESCE(abandoned_at,last_activity_at) DESC LIMIT 200`);
 res.json({carts:result.rows.map((r:any)=>({...r,subtotal:Number(r.subtotal_minor)/100}))});
});

router.get("/merchant/customer-addresses/:customerId",async(req,res):Promise<void>=>{
 const m=await merchantFor(req);if(!m){fail(res,401,"Authentication required");return;}const customerId=Number(req.params.customerId);if(!Number.isInteger(customerId)||customerId<1){fail(res,400,"Invalid customer");return;}
 const [customer]=await db.select({id:customersTable.id}).from(customersTable).where(and(eq(customersTable.id,customerId),eq(customersTable.merchantId,m.id))).limit(1);if(!customer){fail(res,404,"Customer not found");return;}
 const result=await db.execute(sql`SELECT * FROM customer_addresses WHERE merchant_id=${m.id} AND customer_id=${customerId} ORDER BY is_default DESC,updated_at DESC`);res.json({addresses:result.rows});
});
router.post("/merchant/customer-addresses/:customerId",async(req,res):Promise<void>=>{
 const m=await merchantFor(req);if(!m){fail(res,401,"Authentication required");return;}const customerId=Number(req.params.customerId);if(!Number.isInteger(customerId)||customerId<1){fail(res,400,"Invalid customer");return;}
 const [customer]=await db.select({id:customersTable.id}).from(customersTable).where(and(eq(customersTable.id,customerId),eq(customersTable.merchantId,m.id))).limit(1);if(!customer){fail(res,404,"Customer not found");return;}
 const label=txt(req.body?.label,80)||"Address",recipient=txt(req.body?.recipientName,160),line1=txt(req.body?.addressLine1,240),line2=txt(req.body?.addressLine2,240),city=txt(req.body?.city,120),state=txt(req.body?.state,120),postal=txt(req.body?.postalCode,40),country=txt(req.body?.country,120),phone=txt(req.body?.phone,40),isDefault=req.body?.isDefault===true;
 if(!recipient||!line1||!city||!country){fail(res,400,"Recipient, address, city and country are required");return;}if(isDefault)await db.execute(sql`UPDATE customer_addresses SET is_default=false,updated_at=now() WHERE merchant_id=${m.id} AND customer_id=${customerId}`);
 const result=await db.execute(sql`INSERT INTO customer_addresses(merchant_id,customer_id,label,recipient_name,phone,address_line1,address_line2,city,state,postal_code,country,is_default) VALUES(${m.id},${customerId},${label},${recipient},NULLIF(${phone},''),${line1},NULLIF(${line2},''),${city},NULLIF(${state},''),NULLIF(${postal},''),${country},${isDefault}) ON CONFLICT(merchant_id,customer_id,label) DO UPDATE SET recipient_name=EXCLUDED.recipient_name,phone=EXCLUDED.phone,address_line1=EXCLUDED.address_line1,address_line2=EXCLUDED.address_line2,city=EXCLUDED.city,state=EXCLUDED.state,postal_code=EXCLUDED.postal_code,country=EXCLUDED.country,is_default=EXCLUDED.is_default,updated_at=now() RETURNING *`);
 await emitDomainEvent(db,{merchantId:m.id,eventType:"customer.address.updated",aggregateType:"customer_address",aggregateId:String((result.rows[0] as any)?.id??label),actorType:"merchant",actorId:getAuth(req).userId,source:"merchant_api",idempotencyKey:`customer-address:${m.id}:${customerId}:${label}:${Date.now()}`,payload:{customerId,label}});
 res.status(201).json({address:result.rows[0]});
});
router.delete("/merchant/customer-addresses/:customerId/:addressId",async(req,res):Promise<void>=>{const m=await merchantFor(req);if(!m){fail(res,401,"Authentication required");return;}const customerId=Number(req.params.customerId),addressId=txt(req.params.addressId,80);const result=await db.execute(sql`DELETE FROM customer_addresses WHERE id=${addressId} AND merchant_id=${m.id} AND customer_id=${customerId} RETURNING id`);if(!result.rows.length){fail(res,404,"Address not found");return;}res.status(204).end();});

router.get("/public/store/:merchantKey/reviews/:productId",async(req,res):Promise<void>=>{
 const m=await publicStore(txt(req.params.merchantKey,120));if(!m){fail(res,404,"Store not found");return;}const productId=Number(req.params.productId);if(!Number.isInteger(productId)||productId<1){fail(res,400,"Invalid product");return;}
 const reviews=await db.execute(sql`SELECT r.id,r.rating,r.title,r.body,r.media,r.verified_purchase,r.merchant_reply,r.merchant_reply_at,r.created_at,c.name customer_name FROM product_reviews r JOIN customers c ON c.id=r.customer_id WHERE r.merchant_id=${m.id} AND r.supplier_product_id=${productId} AND r.status='approved' ORDER BY r.created_at DESC LIMIT 100`);
 const summary=await db.execute(sql`SELECT COALESCE(AVG(rating),0) avg_rating,COUNT(*) review_count FROM product_reviews WHERE merchant_id=${m.id} AND supplier_product_id=${productId} AND status='approved'`);
 res.json({reviews:reviews.rows,summary:summary.rows[0]});
});
router.post("/public/store/:merchantKey/reviews",async(req,res):Promise<void>=>{
 const m=await publicStore(txt(req.params.merchantKey,120));if(!m){fail(res,404,"Store not found");return;}const orderNumber=txt(req.body?.orderNumber,100),customerEmail=mail(req.body?.customerEmail),body=txt(req.body?.body,4000),title=txt(req.body?.title,200),productId=Number(req.body?.productId),rating=Number(req.body?.rating);
 if(!orderNumber||!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(customerEmail)||body.length<5||!Number.isInteger(productId)||productId<1||!Number.isInteger(rating)||rating<1||rating>5){fail(res,400,"Verified order, email, product, rating and review are required");return;}
 const result=await db.execute(sql`SELECT o.id order_id,o.customer_id FROM orders o JOIN customers c ON c.id=o.customer_id WHERE o.merchant_id=${m.id} AND o.order_number=${orderNumber} AND lower(c.email)=${customerEmail} AND o.supplier_product_id=${productId} AND o.status IN ('paid','processing','completed','shipped','delivered') LIMIT 1`);
 const order=result.rows[0] as any;if(!order){fail(res,403,"This review could not be verified against a paid order");return;}
 const review=await db.execute(sql`INSERT INTO product_reviews(merchant_id,customer_id,order_id,supplier_product_id,rating,title,body,verified_purchase,status) VALUES(${m.id},${order.customer_id},${order.order_id},${productId},${rating},NULLIF(${title},''),${body},true,'pending') ON CONFLICT(merchant_id,customer_id,order_id,supplier_product_id) DO UPDATE SET rating=EXCLUDED.rating,title=EXCLUDED.title,body=EXCLUDED.body,status='pending',updated_at=now() RETURNING id`);
 await emitDomainEvent(db,{merchantId:m.id,eventType:"review.created",aggregateType:"product_review",aggregateId:String((review.rows[0] as any)?.id),actorType:"customer",actorId:String(order.customer_id),source:"public_checkout",idempotencyKey:`review-created:${order.order_id}:${productId}:${order.customer_id}`,payload:{orderId:order.order_id,productId,rating,verifiedPurchase:true}});
 res.status(201).json({status:"pending",message:"Your verified-purchase review was submitted for moderation."});
});
router.get("/merchant/reviews",async(req,res):Promise<void>=>{const m=await merchantFor(req);if(!m){fail(res,401,"Authentication required");return;}const status=txt(req.query.status,20);const clause=["pending","approved","rejected","flagged"].includes(status)?sql`AND status=${status}`:sql``;const result=await db.execute(sql`SELECT r.*,c.name customer_name,c.email customer_email FROM product_reviews r JOIN customers c ON c.id=r.customer_id WHERE r.merchant_id=${m.id} ${clause} ORDER BY r.created_at DESC LIMIT 200`);res.json({reviews:result.rows});});
router.post("/merchant/reviews/:id/moderate",async(req,res):Promise<void>=>{const m=await merchantFor(req);if(!m){fail(res,401,"Authentication required");return;}const id=txt(req.params.id,80),status=txt(req.body?.status,20);if(!["approved","rejected","flagged"].includes(status)){fail(res,400,"Invalid moderation state");return;}const result=await db.execute(sql`UPDATE product_reviews SET status=${status},updated_at=now() WHERE id=${id} AND merchant_id=${m.id} RETURNING id,status`);if(!result.rows.length){fail(res,404,"Review not found");return;}await emitDomainEvent(db,{merchantId:m.id,eventType:"review.moderated",aggregateType:"product_review",aggregateId:id,actorType:"merchant",actorId:getAuth(req).userId,source:"merchant_api",idempotencyKey:`review-moderated:${id}:${status}:${Date.now()}`,payload:{status}});res.json({review:result.rows[0]});});
router.post("/merchant/reviews/:id/reply",async(req,res):Promise<void>=>{const m=await merchantFor(req);if(!m){fail(res,401,"Authentication required");return;}const id=txt(req.params.id,80),reply=txt(req.body?.reply,2000);if(!reply){fail(res,400,"Reply cannot be empty");return;}const result=await db.execute(sql`UPDATE product_reviews SET merchant_reply=${reply},merchant_reply_at=now(),updated_at=now() WHERE id=${id} AND merchant_id=${m.id} RETURNING id,merchant_reply,merchant_reply_at`);if(!result.rows.length){fail(res,404,"Review not found");return;}res.json({review:result.rows[0]});});

router.post("/public/store/:merchantKey/saved-searches",async(req,res):Promise<void>=>{const m=await publicStore(txt(req.params.merchantKey,120));if(!m){fail(res,404,"Store not found");return;}const v=visitorKey(req.body?.visitorKey),query=txt(req.body?.query,160);if(!v||!query){fail(res,400,"Visitor key and query are required");return;}const result=await db.execute(sql`INSERT INTO customer_saved_searches(merchant_id,visitor_key,query,filters) VALUES(${m.id},${v},${query},${JSON.stringify(req.body?.filters??{})}::jsonb) ON CONFLICT(merchant_id,visitor_key,query) DO UPDATE SET filters=EXCLUDED.filters,active=true,updated_at=now() RETURNING *`);
 await emitDomainEvent(db,{merchantId:m.id,eventType:"customer.saved_search.created",aggregateType:"customer_saved_search",aggregateId:String((result.rows[0] as any)?.id),actorType:"customer",source:"public_checkout",idempotencyKey:`saved-search:${m.id}:${v}:${query}`,payload:{query}});
 res.status(201).json({search:result.rows[0]});});
router.get("/public/store/:merchantKey/saved-searches/:visitorKey",async(req,res):Promise<void>=>{const m=await publicStore(txt(req.params.merchantKey,120));if(!m){fail(res,404,"Store not found");return;}const v=visitorKey(req.params.visitorKey);if(!v){fail(res,400,"Invalid visitor key");return;}const result=await db.execute(sql`SELECT * FROM customer_saved_searches WHERE merchant_id=${m.id} AND visitor_key=${v} AND active=true ORDER BY created_at DESC LIMIT 50`);res.json({searches:result.rows});});
router.delete("/public/store/:merchantKey/saved-searches/:id/:visitorKey",async(req,res):Promise<void>=>{const m=await publicStore(txt(req.params.merchantKey,120));if(!m){fail(res,404,"Store not found");return;}const v=visitorKey(req.params.visitorKey);const id=txt(req.params.id,80);const result=await db.execute(sql`DELETE FROM customer_saved_searches WHERE id=${id} AND merchant_id=${m.id} AND visitor_key=${v} RETURNING id`);if(!result.rows.length){fail(res,404,"Saved search not found");return;}res.status(204).end();});
router.post("/public/store/:merchantKey/price-watches",async(req,res):Promise<void>=>{const m=await publicStore(txt(req.params.merchantKey,120));if(!m){fail(res,404,"Store not found");return;}const v=visitorKey(req.body?.visitorKey),productId=Number(req.body?.productId),target=Number(req.body?.targetPrice),currency=txt(req.body?.currency,3).toUpperCase();if(!v||!Number.isInteger(productId)||productId<1||!Number.isFinite(target)||target<0||!/^[A-Z]{3}$/.test(currency)){fail(res,400,"Valid watch details are required");return;}const product=await db.execute(sql`SELECT id FROM supplier_products WHERE id=${productId} AND merchant_id=${m.id} AND status='active' LIMIT 1`);if(!product.rows.length){fail(res,404,"Product not found");return;}const result=await db.execute(sql`INSERT INTO customer_price_watches(merchant_id,visitor_key,supplier_product_id,target_price,currency) VALUES(${m.id},${v},${productId},${target.toFixed(2)},${currency}) ON CONFLICT(merchant_id,visitor_key,supplier_product_id) DO UPDATE SET target_price=EXCLUDED.target_price,currency=EXCLUDED.currency,active=true,updated_at=now() RETURNING *`);await emitDomainEvent(db,{merchantId:m.id,eventType:"customer.price_watch.created",aggregateType:"price_watch",aggregateId:String((result.rows[0] as any)?.id),actorType:"customer",source:"public_checkout",idempotencyKey:`price-watch:${m.id}:${v}:${productId}`,payload:{productId,targetPrice:target,currency}});res.status(201).json({watch:result.rows[0]});});
router.get("/public/store/:merchantKey/price-watches/:visitorKey",async(req,res):Promise<void>=>{const m=await publicStore(txt(req.params.merchantKey,120));if(!m){fail(res,404,"Store not found");return;}const v=visitorKey(req.params.visitorKey);if(!v){fail(res,400,"Invalid visitor key");return;}const result=await db.execute(sql`SELECT w.*,p.title,p.selling_price,p.currency product_currency FROM customer_price_watches w JOIN supplier_products p ON p.id=w.supplier_product_id WHERE w.merchant_id=${m.id} AND w.visitor_key=${v} AND w.active=true ORDER BY w.updated_at DESC LIMIT 100`);res.json({watches:result.rows});});

router.get("/public/store/:merchantKey/notification-preferences/:visitorKey",async(req,res):Promise<void>=>{const m=await publicStore(txt(req.params.merchantKey,120));if(!m){fail(res,404,"Store not found");return;}const v=visitorKey(req.params.visitorKey);if(!v){fail(res,400,"Invalid visitor key");return;}const result=await db.execute(sql`SELECT * FROM customer_notification_preferences WHERE merchant_id=${m.id} AND visitor_key=${v} LIMIT 1`);res.json({preferences:result.rows[0]??{email_transactional:true,email_marketing:false,sms_marketing:false,push_marketing:false,product_alerts:true,review_requests:true}});});
router.put("/public/store/:merchantKey/notification-preferences/:visitorKey",async(req,res):Promise<void>=>{const m=await publicStore(txt(req.params.merchantKey,120));if(!m){fail(res,404,"Store not found");return;}const v=visitorKey(req.params.visitorKey);if(!v){fail(res,400,"Invalid visitor key");return;}const vals={emailTransactional:req.body?.emailTransactional!==false,emailMarketing:req.body?.emailMarketing===true,smsMarketing:req.body?.smsMarketing===true,pushMarketing:req.body?.pushMarketing===true,productAlerts:req.body?.productAlerts!==false,reviewRequests:req.body?.reviewRequests!==false};const result=await db.execute(sql`INSERT INTO customer_notification_preferences(merchant_id,visitor_key,email_transactional,email_marketing,sms_marketing,push_marketing,product_alerts,review_requests) VALUES(${m.id},${v},${vals.emailTransactional},${vals.emailMarketing},${vals.smsMarketing},${vals.pushMarketing},${vals.productAlerts},${vals.reviewRequests}) ON CONFLICT(merchant_id,visitor_key) DO UPDATE SET email_transactional=EXCLUDED.email_transactional,email_marketing=EXCLUDED.email_marketing,sms_marketing=EXCLUDED.sms_marketing,push_marketing=EXCLUDED.push_marketing,product_alerts=EXCLUDED.product_alerts,review_requests=EXCLUDED.review_requests,updated_at=now() RETURNING *`);await emitDomainEvent(db,{merchantId:m.id,eventType:"customer.preferences.updated",aggregateType:"notification_preferences",aggregateId:String((result.rows[0] as any)?.id),actorType:"customer",source:"public_checkout",idempotencyKey:`customer-prefs:${m.id}:${v}:${Date.now()}`,payload:vals});res.json({preferences:result.rows[0]});});

router.get("/public/store/:merchantKey/customer-notifications/:visitorKey",async(req,res):Promise<void>=>{
 const m=await publicStore(txt(req.params.merchantKey,120));if(!m){fail(res,404,"Store not found");return;}
 const v=visitorKey(req.params.visitorKey);if(!v){fail(res,400,"Invalid visitor key");return;}
 const result=await db.execute(sql`SELECT id,notification_type,entity_type,entity_id,title,body,deep_link,read_at,created_at FROM customer_notifications WHERE merchant_id=${m.id} AND visitor_key=${v} ORDER BY created_at DESC LIMIT 100`);
 res.setHeader("Cache-Control","no-store");res.json({notifications:result.rows});
});
router.post("/public/store/:merchantKey/customer-notifications/:id/read/:visitorKey",async(req,res):Promise<void>=>{
 const m=await publicStore(txt(req.params.merchantKey,120));if(!m){fail(res,404,"Store not found");return;}
 const v=visitorKey(req.params.visitorKey);if(!v){fail(res,400,"Invalid visitor key");return;}
 const id=txt(req.params.id,80);const result=await db.execute(sql`UPDATE customer_notifications SET read_at=COALESCE(read_at,now()) WHERE id=${id} AND merchant_id=${m.id} AND visitor_key=${v} RETURNING id,read_at`);
 if(!result.rows.length){fail(res,404,"Notification not found");return;}res.json({notification:result.rows[0]});
});

export default router;