import { Router, type IRouter } from "express";
import healthRouter from "./health";
import paymentBoundaryRouter from "./payment-boundary";
import flutterwaveWebhookRouter from "./flutterwave-webhook";
import adminIntegrationsRouter from "./admin-integrations";
import marketplacePlatformRouter from "./marketplace-platform";
import marketplaceLegacyGuardRouter from "./marketplace-legacy-guard";
import marketplaceAdvertisingCompatRouter from "./marketplace-advertising-compat";
import auctionIntegrityRouter from "./auction-integrity";
import auctionLifecycleRouter from "./auction-lifecycle";
import productAuctionSettlementRouter from "./product-auction-settlement";
import merchantControlPlaneRouter from "./merchant-control-plane";
import storeAuctionsRouter from "./store-auctions";
import storeAuctionPaymentRouter from "./store-auction-payment";
import auctioneerAiRouter from "./auctioneer-ai";
import auctioneerLiveAnalysisRouter from "./auctioneer-live-analysis";
import dashboardTransactionsRouter from "./dashboard-transactions";
import merchantFinancialsRouter from "./merchant-financials";
import aiAutomationRouter from "./ai-automation";
import commerceRouter from "./commerce";
import commerceGrowthRouter from "./commerce-growth";
import commerceSuiteRouter from "./commerce-suite";
import adStudioStitchRouter from "./ad-studio-stitch";
import adStudioRouter from "./ad-studio";
import dailyAiAdvertisingRouter from "./daily-ai-advertising";
import socialHubRouter from "./social-hub";
import subscriptionOptionsRouter from "./subscription-options";
import storefrontDomainsRouter from "./storefront-domains";
import storefrontPublishingRouter from "./storefront-publishing";

const router: IRouter = Router();
router.use(healthRouter);
router.use(paymentBoundaryRouter);
router.use(flutterwaveWebhookRouter);
router.use(adminIntegrationsRouter);
router.use(marketplacePlatformRouter);
router.use(marketplaceLegacyGuardRouter);
router.use(marketplaceAdvertisingCompatRouter);
router.use(auctionIntegrityRouter);
router.use(auctionLifecycleRouter);
router.use(productAuctionSettlementRouter);
router.use(merchantControlPlaneRouter);
router.use(storeAuctionsRouter);
router.use(storeAuctionPaymentRouter);
router.use(auctioneerAiRouter);
router.use(auctioneerLiveAnalysisRouter);
router.use(dashboardTransactionsRouter);
router.use(merchantFinancialsRouter);
router.use(aiAutomationRouter);
router.use(commerceRouter);
router.use(commerceGrowthRouter);
router.use(commerceSuiteRouter);
router.use(adStudioStitchRouter);
router.use(adStudioRouter);
router.use(dailyAiAdvertisingRouter);
router.use(socialHubRouter);
router.use(subscriptionOptionsRouter);
router.use(storefrontDomainsRouter);
router.use(storefrontPublishingRouter);
export default router;
