import dropshipIntelligenceRouter from "./dropship-intelligence";
import { Router, type IRouter } from "express";
import healthRouter from "./health";
import adminHealthRouter from "./admin-health";
import adminFinancialTraceRouter from "./admin-financial-trace";
import authRouter from "./auth";
import paymentBoundaryRouter from "./payment-boundary";
import flutterwaveWebhookRouter from "./flutterwave-webhook";
import adminIntegrationsRouter from "./admin-integrations";
import adminAiStoreCreatorRouter from "./admin-ai-store-creator-local";
import marketplacePlatformRouter from "./marketplace-platform";
import marketplaceLegacyGuardRouter from "./marketplace-legacy-guard";
import marketplaceAdvertisingCompatRouter from "./marketplace-advertising-compat";
import auctionIntegrityRouter from "./auction-integrity";
import auctionLifecycleRouter from "./auction-lifecycle";
import productAuctionSettlementRouter from "./product-auction-settlement";
import merchantControlPlaneRouter from "./merchant-control-plane";
import storeAuctionsRouter from "./store-auctions";
import publicStoreAuctionsRouter from "./public-store-auctions";
import storeAuctionPaymentRouter from "./store-auction-payment";
import auctioneerAiRouter from "./auctioneer-ai";
import auctioneerLiveAnalysisRouter from "./auctioneer-live-analysis";
import dashboardTransactionsRouter from "./dashboard-transactions";
import merchantFinancialsRouter from "./merchant-financials";
import aiAutomationRouter from "./ai-automation";
import aiBusinessBrainRouter from "./ai-business-brain";
import dropshippingSyncRouter from "./dropshipping-sync";
import supplierRoutingRouter from "./supplier-routing";
import supplierPerformanceRouter from "./supplier-performance";
import commerceRouter from "./commerce";
import commerceGrowthRouter from "./commerce-growth";
import commerceSuiteRouter from "./commerce-suite";
import adStudioStitchRouter from "./ad-studio-stitch";
import adStudioRouter from "./ad-studio";
import dailyAiAdvertisingRouter from "./daily-ai-advertising";
import socialHubRouter from "./social-hub";
import subscriptionOptionsRouter from "./subscription-options";
import storefrontDomainsRouter from "./storefront-domains";
import storefrontPublishingRouter from "./storefront-publishing";
import tsPayTransfersRouter from "./ts-pay-transfers";
import customerSubscriptionsRouter from "./customer-subscriptions";
import publicHostStoreRouter from "./public-host-store";
import advancedCommerceRouter from "./advanced-commerce";
import automationWorkflowsRouter from "./automation-workflows";
import customerExperienceRouter from "./customer-experience";
import selfHostedAiRuntimeRouter from "./self-hosted-ai-runtime";
import customerEngagementFrontierRouter from "./customer-engagement-frontier";
const router: IRouter = Router();
router.use(healthRouter);
router.use(adminHealthRouter);
router.use(adminFinancialTraceRouter);
router.use(authRouter);
router.use(paymentBoundaryRouter);
router.use(flutterwaveWebhookRouter);
router.use(adminIntegrationsRouter);
router.use(adminAiStoreCreatorRouter);
router.use(marketplacePlatformRouter);
router.use(marketplaceLegacyGuardRouter);
router.use(marketplaceAdvertisingCompatRouter);
router.use(auctionIntegrityRouter);
router.use(auctionLifecycleRouter);
router.use(productAuctionSettlementRouter);
router.use(merchantControlPlaneRouter);
router.use(storeAuctionsRouter);
router.use(publicStoreAuctionsRouter);
router.use(storeAuctionPaymentRouter);
router.use(auctioneerAiRouter);
router.use(auctioneerLiveAnalysisRouter);
router.use(dashboardTransactionsRouter);
router.use(merchantFinancialsRouter);
router.use(aiAutomationRouter);
router.use(aiBusinessBrainRouter);
router.use(dropshippingSyncRouter);
router.use(supplierRoutingRouter);
router.use(supplierPerformanceRouter);
router.use(publicHostStoreRouter);
router.use(advancedCommerceRouter);
router.use(automationWorkflowsRouter);
router.use(customerExperienceRouter);
router.use(selfHostedAiRuntimeRouter);
router.use(customerEngagementFrontierRouter);
router.use(commerceRouter);
router.use(commerceGrowthRouter);
router.use(commerceSuiteRouter);
router.use(adStudioStitchRouter);
router.use(adStudioRouter);
router.use(dailyAiAdvertisingRouter);
router.use(socialHubRouter);
router.use(subscriptionOptionsRouter);
router.use(dropshipIntelligenceRouter);
router.use(storefrontDomainsRouter);
router.use(storefrontPublishingRouter);
router.use(tsPayTransfersRouter);
router.use(customerSubscriptionsRouter);
export default router;
