import { Router, type Request, type Response } from "express";
import { and, desc, eq } from "drizzle-orm";
import { getAuth } from "@clerk/express";
import { createCipheriv, createDecipheriv, createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import { db, merchantsTable, socialConnectionsTable, socialPublishJobsTable } from "@workspace/db";

const router = Router();
const PROVIDERS = {
  instagram: { label: "Instagram", requiredEnv: ["SOCIAL_META_CLIENT_ID", "SOCIAL_META_CLIENT_SECRET"] },
  facebook: { label: "Facebook", requiredEnv: ["SOCIAL_META_CLIENT_ID", "SOCIAL_META_CLIENT_SECRET"] },
  tiktok: { label: "TikTok", requiredEnv: ["SOCIAL_TIKTOK_CLIENT_KEY", "SOCIAL_TIKTOK_CLIENT_SECRET"] },
  youtube: { label: "YouTube", requiredEnv: ["SOCIAL_GOOGLE_CLIENT_ID", "SOCIAL_GOOGLE_CLIENT_SECRET"] },
  linkedin: { label: "LinkedIn", requiredEnv: ["SOCIAL_LINKEDIN_CLIENT_ID", "SOCIAL_LINKEDIN_CLIENT_SECRET"] },
  pinterest: { label: "Pinterest", requiredEnv: ["SOCIAL_PINTEREST_CLIENT_ID", "SOCIAL_PINTEREST_CLIENT_SECRET"] },
  x: { label: "X", requiredEnv: ["SOCIAL_X_CLIENT_ID", "SOCIAL_X_CLIENT_SECRET"] },
} as const;
type Provider = keyof typeof PROVIDERS;

async function merchantFor(req: Request) {
  const userId = getAuth(req).userId;
  if (!userId) return null;
  return (await db.select().from(merchantsTable).where(eq(merchantsTable.clerkUserId, userId)).limit(1))[0] ?? null;
}
function fail(res: Response, status: number, error: string) { res.status(status).json({ error }); }
function validProvider(value: string): value is Provider { return Object.prototype.hasOwnProperty.call(PROVIDERS, value); }
function secret() { const value=process.env.SOCIAL_TOKEN_ENCRYPTION_KEY; if(!value) throw new Error("SOCIAL_TOKEN_ENCRYPTION_KEY is not configured"); const key=/^[a-f0-9]{64}$/i.test(value)?Buffer.from(value,"hex"):Buffer.from(value,"base64"); if(key.length!==32) throw new Error("SOCIAL_TOKEN_ENCRYPTION_KEY must decode to 32 bytes"); return key; }
function encryptToken(value:string){const key=secret(),iv=randomBytes(12),cipher=createCipheriv("aes-256-gcm",key,iv);const ciphertext=Buffer.concat([cipher.update(value,"utf8"),cipher.final()]);return `v1.${iv.toString("base64url")}.${ciphertext.toString("base64url")}.${cipher.getAuthTag().toString("base64url")}`;}
function oauthState(merchantId:number,provider:Provider){const timestamp=Date.now().toString(),nonce=randomBytes(18).toString("hex"),payload=`${merchantId}:${provider}:${timestamp}:${nonce}`,stateSecret=process.env.SOCIAL_OAUTH_STATE_SECRET;if(!stateSecret)throw new Error("SOCIAL_OAUTH_STATE_SECRET is not configured");const sig=createHmac("sha256",stateSecret).update(payload).digest("hex");return Buffer.from(`${payload}:${sig}`).toString("base64url");}
function parseState(value:string){const stateSecret=process.env.SOCIAL_OAUTH_STATE_SECRET;if(!stateSecret)return null;const decoded=Buffer.from(value,"base64url").toString("utf8"),parts=decoded.split(":");if(parts.length!==5)return null;const [merchantIdRaw,providerRaw,timestampRaw,nonce,signature]=parts;if(!merchantIdRaw||!providerRaw||!timestampRaw||!nonce||!signature||!validProvider(providerRaw))return null;const payload=`${merchantIdRaw}:${providerRaw}:${timestampRaw}:${nonce}`,expected=createHmac("sha256",stateSecret).update(payload).digest("hex");if(signature.length!==expected.length||!timingSafeEqual(Buffer.from(signature),Buffer.from(expected)))return null;const timestamp=Number(timestampRaw),merchantId=Number(merchantIdRaw);if(!Number.isFinite(timestamp)||Date.now()-timestamp>10*60*1000||Date.now()<timestamp-60*1000)return null;return Number.isInteger(merchantId)&&merchantId>0?{merchantId,provider:providerRaw,nonce}:null;}

router.get("/social/providers", async(req,res)=>{const merchant=await merchantFor(req);if(!merchant){fail(res,401,"Authentication required");return;}const connections=await db.select().from(socialConnectionsTable).where(eq(socialConnectionsTable.merchantId,merchant.id)).orderBy(desc(socialConnectionsTable.updatedAt));const connected=new Map(connections.map(c=>[c.provider,c]));res.json(Object.entries(PROVIDERS).map(([provider,meta])=>({id:connected.get(provider)?.id??null,provider,label:meta.label,configured:configured(provider as Provider),connected:connected.has(provider),accountName:connected.get(provider)?.accountName??null,status:connected.get(provider)?.status??"disconnected"})));});
function configured(provider: Provider) { return PROVIDERS[provider].requiredEnv.every((key) => Boolean(process.env[key])) && Boolean(process.env.SOCIAL_OAUTH_CALLBACK_URL) && Boolean(process.env.SOCIAL_OAUTH_STATE_SECRET); }

router.get("/social/connect/:provider", async(req,res)=>{const merchant=await merchantFor(req);if(!merchant){fail(res,401,"Authentication required");return;}const provider=req.params.provider;if(!validProvider(provider)){fail(res,400,"Unsupported social provider");return;}if(!configured(provider)){res.status(503).json({error:`${PROVIDERS[provider].label} connection is not configured on this TS Commerce deployment`});return;}const redirectUri=process.env.SOCIAL_OAUTH_CALLBACK_URL!;const state=oauthState(merchant.id,provider);let authorizeUrl="";if(provider==='tiktok')authorizeUrl=`https://www.tiktok.com/v2/auth/authorize/?client_key=${encodeURIComponent(process.env.SOCIAL_TIKTOK_CLIENT_KEY!)}&response_type=code&scope=user.info.basic,video.publish&redirect_uri=${encodeURIComponent(redirectUri)}&state=${encodeURIComponent(state)}`;else if(provider==='youtube')authorizeUrl=`https://accounts.google.com/o/oauth2/v2/auth?client_id=${encodeURIComponent(process.env.SOCIAL_GOOGLE_CLIENT_ID!)}&response_type=code&access_type=offline&prompt=consent&scope=${encodeURIComponent('https://www.googleapis.com/auth/youtube.upload')}&redirect_uri=${encodeURIComponent(redirectUri)}&state=${encodeURIComponent(state)}`;else if(provider==='linkedin')authorizeUrl=`https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id=${encodeURIComponent(process.env.SOCIAL_LINKEDIN_CLIENT_ID!)}&redirect_uri=${encodeURIComponent(redirectUri)}&scope=${encodeURIComponent('openid profile w_member_social')}&state=${encodeURIComponent(state)}`;else if(provider==='pinterest')authorizeUrl=`https://www.pinterest.com/oauth/?client_id=${encodeURIComponent(process.env.SOCIAL_PINTEREST_CLIENT_ID!)}&redirect_uri=${encodeURIComponent(redirectUri)}&response_type=code&scope=${encodeURIComponent('boards:read boards:write pins:read pins:write')}&state=${encodeURIComponent(state)}`;else if(provider==='x'){fail(res,501,"X publishing remains disabled until a true PKCE verifier/token-exchange flow is configured.");return;}else authorizeUrl=`https://www.facebook.com/v24.0/dialog/oauth?client_id=${encodeURIComponent(process.env.SOCIAL_META_CLIENT_ID!)}&redirect_uri=${encodeURIComponent(redirectUri)}&state=${encodeURIComponent(state)}&scope=${encodeURIComponent('pages_show_list,pages_read_engagement,pages_manage_posts,instagram_basic,instagram_content_publish')}`;res.json({provider,label:PROVIDERS[provider].label,authorizeUrl});});

router.get("/social/callback", async(req,res)=>{const code=typeof req.query.code==='string'?req.query.code:null,state=typeof req.query.state==='string'?req.query.state:null;if(!code||!state){res.status(400).send("Missing OAuth code or state");return;}const parsed=parseState(state);if(!parsed){res.status(400).send("Invalid or expired OAuth state");return;}const merchant=(await db.select().from(merchantsTable).where(eq(merchantsTable.id,parsed.merchantId)).limit(1))[0];if(!merchant){res.status(400).send("Merchant not found");return;}const redirectUri=process.env.SOCIAL_OAUTH_CALLBACK_URL;if(!redirectUri){res.status(503).send("Social OAuth is not configured");return;}let tokenUrl='',clientId='',clientSecret='';if(parsed.provider==='youtube'){tokenUrl='https://oauth2.googleapis.com/token';clientId=process.env.SOCIAL_GOOGLE_CLIENT_ID!;clientSecret=process.env.SOCIAL_GOOGLE_CLIENT_SECRET!;}else if(parsed.provider==='linkedin'){tokenUrl='https://www.linkedin.com/oauth/v2/accessToken';clientId=process.env.SOCIAL_LINKEDIN_CLIENT_ID!;clientSecret=process.env.SOCIAL_LINKEDIN_CLIENT_SECRET!;}else if(parsed.provider==='pinterest'){tokenUrl='https://api.pinterest.com/v5/oauth/token';clientId=process.env.SOCIAL_PINTEREST_CLIENT_ID!;clientSecret=process.env.SOCIAL_PINTEREST_CLIENT_SECRET!;}else if(parsed.provider==='tiktok'){tokenUrl='https://open.tiktokapis.com/v2/oauth/token/';clientId=process.env.SOCIAL_TIKTOK_CLIENT_KEY!;clientSecret=process.env.SOCIAL_TIKTOK_CLIENT_SECRET!;}else{tokenUrl='https://graph.facebook.com/v24.0/oauth/access_token';clientId=process.env.SOCIAL_META_CLIENT_ID!;clientSecret=process.env.SOCIAL_META_CLIENT_SECRET!;}try{const body=new URLSearchParams({client_id:clientId,client_secret:clientSecret,code,redirect_uri:redirectUri,grant_type:'authorization_code'}),response=await fetch(tokenUrl,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body}),token=await response.json() as Record<string,unknown>;if(!response.ok||typeof token.access_token!=='string')throw new Error('Provider token exchange failed');const expiresIn=Number(token.expires_in),expiresAt=Number.isFinite(expiresIn)?new Date(Date.now()+expiresIn*1000):null;await db.insert(socialConnectionsTable).values({merchantId:merchant.id,provider:parsed.provider,accountId:typeof token.open_id==='string'?token.open_id:null,accountName:typeof token.display_name==='string'?token.display_name:null,accessTokenEncrypted:encryptToken(token.access_token),refreshTokenEncrypted:typeof token.refresh_token==='string'?encryptToken(token.refresh_token):null,tokenExpiresAt:expiresAt,status:'connected',scopes:[],metadata:{}}).onConflictDoNothing();const base=process.env.APP_BASE_URL||'/';res.redirect(`${base.replace(/\/$/,'')}/social-hub?connected=${encodeURIComponent(parsed.provider)}`);}catch(error){res.status(502).send(error instanceof Error?error.message:'Social OAuth callback failed');}});

router.delete("/social/connections/:id", async(req,res)=>{const merchant=await merchantFor(req);if(!merchant){fail(res,401,"Authentication required");return;}const deleted=await db.delete(socialConnectionsTable).where(and(eq(socialConnectionsTable.id,req.params.id),eq(socialConnectionsTable.merchantId,merchant.id))).returning({id:socialConnectionsTable.id});if(!deleted.length){fail(res,404,"Social connection not found");return;}res.status(204).end();});
router.get("/social/publish-jobs", async(req,res)=>{const merchant=await merchantFor(req);if(!merchant){fail(res,401,"Authentication required");return;}const jobs=await db.select({id:socialPublishJobsTable.id,provider:socialPublishJobsTable.provider,caption:socialPublishJobsTable.caption,status:socialPublishJobsTable.status,externalPostId:socialPublishJobsTable.externalPostId,errorMessage:socialPublishJobsTable.errorMessage,createdAt:socialPublishJobsTable.createdAt,publishedAt:socialPublishJobsTable.publishedAt}).from(socialPublishJobsTable).where(eq(socialPublishJobsTable.merchantId,merchant.id)).orderBy(desc(socialPublishJobsTable.createdAt)).limit(100);res.json(jobs);});
router.post("/social/publish", async(req,res)=>{const merchant=await merchantFor(req);if(!merchant){fail(res,401,"Authentication required");return;}const providers=Array.isArray(req.body?.providers)?req.body.providers.filter((v:unknown):v is string=>typeof v==='string'&&validProvider(v)).slice(0,7):[];if(!providers.length){fail(res,400,"Choose at least one social platform");return;}const caption=typeof req.body?.caption==='string'?req.body.caption.trim().slice(0,4000):null;const creativeId=typeof req.body?.creativeId==='string'?req.body.creativeId:null;const mediaId=typeof req.body?.adMediaAssetId==='string'?req.body.adMediaAssetId:null;if(!creativeId&&!mediaId){fail(res,400,"Choose a generated creative or uploaded ad media");return;}const results=[];for(const provider of providers){const[connection]=await db.select().from(socialConnectionsTable).where(and(eq(socialConnectionsTable.merchantId,merchant.id),eq(socialConnectionsTable.provider,provider),eq(socialConnectionsTable.status,'connected'))).limit(1);if(!connection){results.push({provider,status:'not_connected'});continue;}const key=`publish:${provider}:${creativeId??mediaId??'none'}:${caption??''}`;const idempotency=createHmac('sha256',process.env.SOCIAL_OAUTH_STATE_SECRET||'').update(key).digest('hex');const[job]=await db.insert(socialPublishJobsTable).values({merchantId:merchant.id,connectionId:connection.id,creativeId,adMediaAssetId:mediaId,provider,caption,status:'queued',idempotencyKey:idempotency}).onConflictDoNothing({target:socialPublishJobsTable.idempotencyKey}).returning();results.push(job?{provider,status:'queued',jobId:job.id}:{provider,status:'duplicate'});}res.status(202).json({results,message:'Publish jobs queued for connected accounts. Publication status changes only after a real provider confirms success.'});});
export default router;
