// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/recovery-simulations/ActionHub.tsx": () => import("../components/mockups/recovery-simulations/ActionHub.tsx"),
  "./components/mockups/recovery-simulations/AuditTrail.tsx": () => import("../components/mockups/recovery-simulations/AuditTrail.tsx"),
  "./components/mockups/recovery-simulations/GuidedRecovery.tsx": () => import("../components/mockups/recovery-simulations/GuidedRecovery.tsx")
};
