ALTER TABLE subscriptions
  ADD COLUMN IF NOT EXISTS base_amount_usd NUMERIC(12, 2) NOT NULL DEFAULT 30,
  ADD COLUMN IF NOT EXISTS currency TEXT NOT NULL DEFAULT 'USD',
  ADD COLUMN IF NOT EXISTS fx_rate NUMERIC(18, 8) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS fx_source TEXT NOT NULL DEFAULT 'Identity rate',
  ADD COLUMN IF NOT EXISTS fx_as_of TIMESTAMPTZ;