CREATE TABLE IF NOT EXISTS "platform_secret_vault" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "secret_key" text NOT NULL UNIQUE,
  "encrypted_value" text NOT NULL,
  "updated_by" text,
  "updated_at" timestamptz NOT NULL DEFAULT now()
);
