import { runMigrations } from "@workspace/db/migration-runner";
import { pool } from "@workspace/db";
import app from "./app";
import { logger } from "./lib/logger";
import { startDomainEventOutbox } from "./lib/domain-events";
import { startPendingFlutterwaveReconciliation } from "./lib/flutterwave-reconciliation";
import { startDailyAiAdvertisingPlanner } from "./lib/daily-ai-advertising-worker";
import { startAdminAiStoreWorker } from "./lib/admin-ai-store-worker";
import { loadStoredFlutterwaveCredential } from "./lib/flutterwave-runtime";
import { startSocialPublishingWorker } from "./lib/social-publishing-worker";
import { startScheduledWorkflowWorker } from "./lib/automation-engine";
import { startCustomerSubscriptionWorker } from "./lib/customer-subscription-worker";
import { startCartRecoveryWorker } from "./lib/cart-recovery-worker";

await runMigrations();
const rawPort=process.env["PORT"];
if(!rawPort)throw new Error("PORT environment variable is required but was not provided.");
const port=Number(rawPort);
if(Number.isNaN(port)||port<=0)throw new Error(`Invalid PORT value: "${rawPort}"`);
await loadStoredFlutterwaveCredential();
const stopOutbox=startDomainEventOutbox();
const stopFlutterwaveReconciliation=startPendingFlutterwaveReconciliation();
const stopDailyAiAdvertising=startDailyAiAdvertisingPlanner();
const stopAdminAiStore=startAdminAiStoreWorker();
const stopSocialPublishing=startSocialPublishingWorker();
const stopScheduledWorkflows=startScheduledWorkflowWorker();
const stopCustomerSubscriptions=startCustomerSubscriptionWorker();
const stopCartRecovery=startCartRecoveryWorker();
let shuttingDown=false;
const server=app.listen(port,(err)=>{if(err){logger.error({err},"Error listening on port");process.exit(1);}logger.info({port},"Server listening");});
server.requestTimeout=120000;
server.headersTimeout=65000;
server.keepAliveTimeout=65000;
const shutdown=async(signal:string)=>{
  if(shuttingDown)return;
  shuttingDown=true;
  logger.info({signal},"Graceful shutdown started");
  stopOutbox(); stopFlutterwaveReconciliation(); stopDailyAiAdvertising(); stopAdminAiStore(); stopSocialPublishing(); stopScheduledWorkflows(); stopCustomerSubscriptions(); stopCartRecovery();
  const forceTimer=setTimeout(()=>{logger.error("Graceful shutdown timeout");process.exit(1);},10000);
  forceTimer.unref();
  await new Promise<void>(resolve=>server.close(()=>resolve()));
  await pool.end();
  clearTimeout(forceTimer);
  logger.info("Graceful shutdown complete");
  process.exit(0);
};
process.once("SIGTERM",()=>{void shutdown("SIGTERM");});
process.once("SIGINT",()=>{void shutdown("SIGINT");});
