export type FeatureStatus = "implemented" | "partial" | "planned";
export type LunavoFeature = { id:string; area:string; name:string; status:FeatureStatus; route?:string };
type FeatureTuple = readonly [string,string,FeatureStatus,string?];

// Machine-readable rebuild contract. Status is descriptive only; it never bypasses auth or financial controls.
const F = (area:string,name:string,status:FeatureStatus,route?:string):FeatureTuple => [area,name,status,route];
export const LUNAVO_FEATURES: readonly FeatureTuple[] = [
F("platform","Global multi-merchant commerce SaaS","implemented"),F("platform","Multi-vendor architecture","implemented"),F("platform","Multiple stores per merchant","implemented"),F("platform","Customer accounts","implemented"),F("platform","Master admin workspace","implemented","/admin"),F("platform","RBAC","implemented"),F("platform","Team memberships","implemented","/team"),F("platform","Location-scoped staff access","implemented","/team"),F("platform","Workspace switching","implemented"),F("platform","Clerk authentication","implemented","/sign-in"),
F("billing","$30/month core subscription","implemented","/billing"),F("billing","No free trial / promotional pricing","implemented"),F("billing","Dashboard-earnings subscription payment","implemented"),F("billing","Outstanding amount carry-forward","implemented"),F("billing","Subscription currency selection","implemented"),F("billing","15-day earning/access window","implemented"),F("billing","Billing history","implemented","/billing"),F("billing","Period-scoped referral codes","implemented"),F("billing","30% referrer discount ($9)","implemented"),
F("stores","Merchant storefront","implemented","/store"),F("stores","Public storefront","implemented","/store/:merchantKey"),F("stores","Subdomain/custom-domain architecture","partial"),F("stores","Removable Lunavo branding","partial"),F("stores","Responsive storefront","implemented"),F("stores","Store policies/SEO","partial"),
F("catalog","Physical products","implemented"),F("catalog","Digital products","implemented"),F("catalog","Courses","implemented"),F("catalog","Memberships","implemented"),F("catalog","Services","implemented"),F("catalog","Bookings","implemented"),F("catalog","Events","implemented"),F("catalog","Tickets","implemented"),F("catalog","Subscriptions","implemented"),F("catalog","Variants/SKUs/categories/media","implemented"),
F("builder","Store templates","partial"),F("builder","Drag-and-drop builder","partial"),F("builder","Custom HTML/CSS","partial"),F("builder","Preview/publish workflow","partial"),
F("checkout","Cart/public checkout","implemented","/checkout/:merchantKey"),F("checkout","Server tax/shipping/pricing snapshots","implemented"),F("checkout","Pending-order lifecycle","implemented"),F("checkout","Payment verification","implemented"),F("checkout","Refunds/partial refunds/disputes","implemented"),F("checkout","Hosted return recovery","implemented","/checkout/payment-return"),F("checkout","Invoice creation","implemented","/invoices"),
F("payments","First-party payment orchestration","implemented","/ts-pay"),F("payments","Internal double-entry ledger","implemented"),F("payments","Flutterwave adapter","implemented"),F("payments","Paystack adapter","partial"),F("payments","Stripe adapter","partial"),F("payments","PayPal adapter","partial"),F("payments","1% Lunavo transaction fee","implemented"),F("payments","Provider-fee accounting","implemented"),F("payments","Transaction/settlement currency separation","implemented"),F("payments","Webhook verification","implemented"),F("payments","Idempotency","implemented"),F("payments","Real regulated payout boundary","implemented"),F("payments","No fake payment/bank/balance state","implemented"),
F("flutterwave","Secure secret configuration","implemented"),F("flutterwave","Hosted checkout","implemented"),F("flutterwave","Provider bank-transfer destinations","implemented"),F("flutterwave","Transaction verification","implemented"),F("flutterwave","Pending reconciliation","implemented"),F("flutterwave","Provider refund flow","implemented"),
F("finance","Merchant earnings ledger","implemented","/finance"),F("finance","Withdrawals","implemented","/withdrawals"),F("finance","Manual admin withdrawal review","implemented","/admin/withdrawals"),F("finance","Two merchant payout PINs","implemented"),F("finance","Admin step-up security","implemented"),F("finance","Revenue/fees/refunds/net reporting","implemented"),
F("marketplace","Central marketplace","implemented","/marketplace"),F("marketplace","$5/month marketplace fee","implemented"),F("marketplace","$5/product listing fee","implemented"),F("marketplace","Risk-based listing review","implemented"),F("marketplace","Marketplace management","implemented","/marketplace/manage"),
F("auctions","Auction creation/management","implemented","/auctions/manage"),F("auctions","Bidding","implemented","/auctions"),F("auctions","Winner/checkout flow","implemented"),F("auctions","Anti-manipulation controls","partial"),
F("inventory","Manual stock","implemented","/inventory"),F("inventory","Checkout reservations","implemented"),F("inventory","Verified-sale stock decrement","implemented"),F("inventory","Warehouses/transfers/adjustments","implemented"),F("inventory","Source stock non-authoritative","implemented"),F("inventory","Low-stock/reconciliation","partial"),
F("sourcing","Dedicated Sourcing page","implemented","/sourcing"),F("sourcing","Supplier URL-only import","implemented"),F("sourcing","Safe public supplier fetching","implemented"),F("sourcing","AI title/description/category/pricing extraction","partial"),F("sourcing","Variant/SKU/image/spec/shipping extraction","partial"),F("sourcing","Supplier cost vs merchant selling price","implemented"),F("sourcing","Live FX feed","partial"),F("sourcing","Research citations/limitations","implemented"),
F("fulfillment","Dropshipping/fulfillment","implemented","/dropshipping"),F("fulfillment","Supplier order workflow","partial"),F("fulfillment","Tracking/status","partial"),
F("ai","Lunavo AI Control Room","implemented","/ai"),F("ai","DeepSeek-primary architecture","partial"),F("ai","Shopper AI public-context boundary","implemented"),F("ai","Gemini research integration","partial"),F("ai","Product/image understanding","partial"),F("ai","Pollinations image generation","partial"),
F("ads","Self-hosted Ad Studio","implemented","/ad-studio"),F("ads","Catalog-grounded ad planner","implemented"),F("ads","Deterministic local planner","implemented"),F("ads","Optional Gemini planner","implemented"),F("ads","Individual/store-wide generation","implemented"),F("ads","FFmpeg video rendering","implemented"),F("ads","Long-form stitching/audio bed","implemented"),F("ads","Media validation/rate limits","implemented"),F("ads","Durable generated-media persistence","partial"),
F("marketing","Marketing workspace","implemented","/marketing"),F("marketing","Campaign/promotional tooling","partial"),
F("social","Social OAuth architecture","implemented"),F("social","Instagram/Facebook/TikTok/YouTube/LinkedIn/Pinterest","partial"),F("social","X PKCE publishing","planned"),F("social","AES-256-GCM token encryption","implemented"),F("social","OAuth state/nonce protection","implemented"),F("social","Publishing queue/idempotency","implemented"),F("social","Live provider publishing adapters","partial"),
F("pos","Lunavo POS","implemented","/pos"),F("pos","Location-aware POS","implemented"),F("pos","Verified-payment accounting","implemented"),
F("customers","Customer management","implemented"),F("customers","Customer profiles/order history","implemented"),F("customers","Merchant-scoped customer data","implemented"),
F("invoices","Invoice management","implemented","/invoices"),F("invoices","Public invoice links/payment","implemented","/invoice/:token"),F("invoices","Locked/idempotent payment evidence","implemented"),F("payments","Payment links","implemented","/pay/:token"),
F("media","Merchant media library","implemented","/media"),F("media","Durable tenant ownership","implemented"),F("media","Byte/size/format validation","implemented"),
F("analytics","Sales/revenue/order analytics","implemented","/analytics"),F("analytics","Customer/product/inventory analytics","partial"),F("analytics","Marketing/ad performance","partial"),
F("admin","Master admin dashboard","implemented","/admin"),F("admin","Merchant management","implemented","/admin/merchants"),F("admin","Withdrawal oversight","implemented","/admin/withdrawals"),F("admin","Integration administration","implemented","/admin/integrations"),F("admin","Separate admin ledger anchor","implemented"),
F("security","Tenant isolation","implemented"),F("security","Server-side authorization","implemented"),F("security","CSRF/CORS/SSRF/XSS/injection controls","implemented"),F("security","Rate limiting","implemented"),F("security","Bounded in-process rate limiter","implemented"),F("security","Audit logging","implemented"),F("security","Secret isolation","implemented"),F("security","Webhook replay/idempotency protection","implemented"),F("security","Transactional domain events","implemented"),F("security","Replay-safe projections","implemented"),F("security","Production preflight","implemented"),
F("international","Multi-currency commerce","implemented"),F("international","Historical currency integrity","implemented"),F("international","Live FX architecture","partial"),
F("api","Generated API client","implemented"),F("api","Zod API contracts","implemented"),F("api","Provider adapter architecture","implemented"),F("mobile","Responsive web/mobile UI","implemented"),F("mobile","Installable PWA shell","implemented"),F("mobile","Android parity target","planned"),F("mobile","iOS parity target","planned"),F("ops","pnpm TypeScript monorepo","implemented"),F("ops","CI typecheck/security/build","implemented"),F("ops","Explicit migration runner","implemented")
] as const;

export const LUNAVO_FEATURE_REGISTRY: readonly LunavoFeature[] = LUNAVO_FEATURES.map(([area,name,status,route]) => ({ id:`${area}.${name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}`, area,name,status,...(route ? {route}:{}) }));
export function featureSummary() { return LUNAVO_FEATURE_REGISTRY.reduce((s,f)=>{s.total++;s[f.status]++;return s;},{total:0,implemented:0,partial:0,planned:0} as Record<string,number>); }
