export type FeatureStatus = "implemented" | "optional" | "partial" | "planned";
export type LunavoFeature = { id:string; area:string; name:string; status:FeatureStatus; route?:string };
type FeatureTuple = readonly [string,string,FeatureStatus,string?];

// Machine-readable rebuild contract. Status is descriptive only; it never bypasses auth or financial controls.
const F = (area:string,name:string,status:FeatureStatus,route?:string):FeatureTuple => [area,name,status,route];
export const LUNAVO_FEATURES: readonly FeatureTuple[] = [
F("platform","Global multi-merchant commerce SaaS","implemented"),F("platform","Multi-vendor architecture","implemented"),F("platform","Multiple stores per merchant","implemented"),F("platform","Customer accounts","implemented"),F("platform","Master admin workspace","implemented","/admin"),F("platform","RBAC","implemented"),F("platform","Team memberships","implemented","/team"),F("platform","Location-scoped staff access","implemented","/team"),F("platform","Workspace switching","implemented"),F("platform","Self-hosted local authentication","implemented","/sign-in"),
F("billing","$3F("ai","Self-hosted primary reasoning","implemented","/ai"),F("ai","Self-hosted multi-model reasoning and local consensus","implemented","/ai")/month core subscription","implemented","/billing"),F("billing","No free trial / promotional pricing","implemented"),F("billing","Dashboard-earnings subscription payment","implemented"),F("billing","Outstanding amount carry-forward","implemented"),F("billing","Subscription currency selection","implemented"),F("billing","F("ai","External DeepSeek accelerator","optional"),F("ai","External Gemini research accelerator","optional"),F("ai","External Pollinations image accelerator","optional"),,5-day earning/access window","implemented"),F("billing","Billing history","implemented","/billing"),F("billing","Period-scoped referral codes","implemented"),F("billing","30% referrer discount ($9)","implemented"),
F("stores","Merchant storefront","implemented","/store"),F("stores","Public storefront","implemented","/store/:merchantKey"),F("stores","Subdomain/custom-domain architecture","implemented"),F("stores","Removable Lunavo branding","implemented"),F("stores","Responsive storefront","implemented"),F("stores","Store policies/SEO","implemented"),
F("catalog","Physical products","implemented"),F("catalog","Digital products","implemented"),F("catalog","Courses","implemented"),F("catalog","Memberships","implemented"),F("catalog","Services","implemented"),F("catalog","Bookings","implemented"),F("catalog","Events","implemented"),F("catalog","Tickets","implemented"),F("catalog","Subscriptions","implemented"),F("catalog","Variants/SKUs/categories/media","implemented"),
F("builder","Store templates","implemented"),F("builder","Drag-and-drop builder","implemented"),F("builder","Custom HTML/CSS","implemented"),F("builder","Preview/publish workflow","implemented"),
F("checkout","Cart/public checkout","implemented","/checkout/:merchantKey"),F("checkout","Server tax/shipping/pricing snapshots","implemented"),F("checkout","Pending-order lifecycle","implemented"),F("checkout","Payment verification","implemented"),F("checkout","Refunds/partial refunds/disputes","implemented"),F("checkout","Hosted return recovery","implemented","/checkout/payment-return"),F("checkout","Invoice creation","implemented","/invoices"),
F("payments","First-party payment orchestration","implemented","/ts-pay"),F("identity","TS merchant admin payment code","implemented","/dashboard"),F("identity","TS store codes","implemented","/dashboard"),F("identity","TS customer payment codes","implemented","/checkout/:merchantKey"),F("identity","TS global admin code","implemented","/admin"),F("payments","Internal double-entry ledger","implemented"),F("payments","Flutterwave adapter","implemented"),F("payments","Paystack adapter","optional"),F("payments","Stripe adapter","optional"),F("payments","PayPal adapter","optional"),F("payments","1% Lunavo transaction fee","implemented"),F("payments","Provider-fee accounting","implemented"),F("payments","Transaction/settlement currency separation","implemented"),F("payments","Webhook verification","implemented"),F("payments","Idempotency","implemented"),F("payments","Real regulated payout boundary","implemented"),F("payments","No fake payment/bank/balance state","implemented"),
F("flutterwave","Secure secret configuration","implemented"),F("flutterwave","Hosted checkout","implemented"),F("flutterwave","Provider bank-transfer destinations","implemented"),F("flutterwave","Transaction verification","implemented"),F("flutterwave","Pending reconciliation","implemented"),F("flutterwave","Provider refund flow","implemented"),
F("finance","Merchant earnings ledger","implemented","/finance"),F("finance","Withdrawals","implemented","/withdrawals"),F("finance","Provider-backed admin withdrawal review","implemented","/admin/withdrawals"),F("finance","Merchant KYC before payout","implemented","/withdrawals"),F("finance","Master admin KYC review","implemented","/admin/kyc"),F("finance","Two merchant payout PINs","implemented"),F("finance","Admin step-up security","implemented"),F("finance","Revenue/fees/refunds/net reporting","implemented"),
F("marketplace","Central marketplace","implemented","/marketplace"),F("marketplace","$5/month marketplace fee","implemented"),F("marketplace","$5/product listing fee","implemented"),F("marketplace","Risk-based listing review","implemented"),F("marketplace","Marketplace management","implemented","/marketplace/manage"),
F("auctions","Auction creation/management","implemented","/auctions/manage"),F("auctions","Bidding","implemented","/auctions"),F("auctions","Winner/checkout flow","implemented"),F("auctions","Anti-manipulation controls","implemented"),
F("inventory","Manual stock","implemented","/inventory"),F("inventory","Checkout reservations","implemented"),F("inventory","Verified-sale stock decrement","implemented"),F("inventory","Warehouses/transfers/adjustments","implemented"),F("inventory","Source stock non-authoritative","implemented"),F("inventory","Low-stock/reconciliation","implemented"),
F("sourcing","Dedicated Sourcing page","implemented","/sourcing"),F("sourcing","Supplier URL-only import","implemented"),F("sourcing","Safe public supplier fetching","implemented"),F("sourcing","AI title/description/category/pricing extraction","implemented"),F("sourcing","Variant/SKU/image/spec/shipping extraction","implemented"),F("sourcing","Supplier cost vs merchant selling price","implemented"),F("sourcing","Live FX feed","implemented"),F("sourcing","Research citations/limitations","implemented"),
F("fulfillment","Dropshipping/fulfillment","implemented","/dropshipping"),F("fulfillment","Supplier order workflow","implemented"),F("fulfillment","Tracking/status","implemented","/dropshipping"),
F("ai","Lunavo AI Control Room","implemented","/ai"),F("ai","Dedicated Autopilot control centre","implemented","/autopilot"),
F("automation","Workflow automation engine","implemented","/automations"),F("automation","Event-condition-action triggers","implemented","/automations"),F("automation","Approval and dry-run modes","implemented","/automations"),F("automation","Scheduled workflows","implemented","/automations"),F("automation","Replay-safe run history","implemented","/automations"),F("ai","Self-hosted primary reasoning","implemented","/ai"),F("ai","Shopper AI public-context boundary","implemented"),F("ai","Self-hosted research/inference endpoint","implemented","/ai"),F("ai","Self-hosted product/image understanding adapter","implemented","/sourcing"),F("ai","Self-hosted image generation adapter","implemented","/media"),F("ai","External DeepSeek accelerator","optional"),F("ai","External Gemini research accelerator","optional"),F("ai","External Pollinations image accelerator","optional"),
F("ads","Self-hosted Ad Studio","implemented","/ad-studio"),F("ads","Catalog-grounded ad planner","implemented"),F("ads","Deterministic local planner","implemented"),F("ads","Self-hosted AI ad planner","implemented"),F("ads","External Gemini ad planner","optional"),F("ads","Individual/store-wide generation","implemented"),F("ads","FFmpeg video rendering","implemented"),F("ads","Long-form stitching/audio bed","implemented"),F("ads","Media validation/rate limits","implemented"),F("ads","Durable generated-media persistence","implemented","/media"),
F("marketing","Marketing workspace","implemented","/marketing"),F("marketing","Campaign/promotional tooling","implemented","/marketing"),
F("social","Social OAuth architecture","implemented"),F("social","Instagram/Facebook/TikTok/YouTube/LinkedIn/Pinterest","optional"),F("social","X OAuth F("ads","External Gemini ad planner","optional"),, PKCE text publishing","implemented"),F("social","AES-256-GCM token encryption","implemented"),F("social","OAuth state/nonce protection","implemented"),F("social","Publishing queue/idempotency","implemented"),F("social","Live provider publishing adapters","optional"),
F("pos","Lunavo POS","implemented","/pos"),F("pos","Location-aware POS","implemented"),F("pos","Verified-payment accounting","implemented"),
F("customers","Customer management","implemented","/customers"),F("customers","Customer profiles/order history","implemented"),F("customers","Merchant-scoped customer data","implemented"),
F("invoices","Invoice management","implemented","/invoices"),F("invoices","Public invoice links/payment","implemented","/invoice/:token"),F("invoices","Locked/idempotent payment evidence","implemented"),F("payments","Payment links","implemented","/pay/:token"),F("payments","Dashboard-wide financial event trail","implemented","/"),
F("media","Merchant media library","implemented","/media"),F("media","Durable tenant ownership","implemented"),F("media","Byte/size/format validation","implemented"),
F("analytics","Sales/revenue/order analytics","implemented","/analytics"),F("analytics","Customer/product/inventory analytics","implemented"),F("analytics","Marketing/ad performance","implemented"),
F("admin","Master admin dashboard","implemented","/admin"),F("admin","Operational health diagnostics","implemented","/admin"),F("admin","Financial trace investigator","implemented","/admin"),F("admin","Merchant management","implemented","/admin/merchants"),F("admin","Withdrawal oversight","implemented","/admin/withdrawals"),F("admin","Integration administration","implemented","/admin/integrations"),F("admin","Separate admin ledger anchor","implemented"),
F("security","Tenant isolation","implemented"),F("security","Server-side authorization","implemented"),F("security","CSRF/CORS/SSRF/XSS/injection controls","implemented"),F("security","Rate limiting","implemented"),F("security","Audit logging","implemented"),F("security","Secret isolation","implemented"),F("security","Webhook replay/idempotency protection","implemented"),F("security","Transactional domain events","implemented"),F("security","Replay-safe projections","implemented"),F("security","Production preflight","implemented"),
F("international","Multi-currency commerce","implemented"),F("international","Historical currency integrity","implemented"),F("international","Live FX architecture","implemented"),
F("api","Generated API client","implemented"),F("api","Zod API contracts","implemented"),F("api","Provider adapter architecture","implemented"),F("mobile","Responsive web/mobile UI","implemented"),F("mobile","Installable PWA shell","implemented"),F("mobile","API-safe offline shell caching","implemented"),F("mobile","Android parity target","optional"),F("mobile","iOS parity target","optional"),F("subscriptions","Merchant customer subscription plans","implemented","/customer-subscriptions"),F("subscriptions","Customer subscription checkout","implemented","/subscribe/:id"),F("subscriptions","Private customer subscription portal","implemented","/subscription-portal"),F("subscriptions","Verified renewal payment linkage","implemented"),F("subscriptions","Renewal dunning and grace lifecycle","implemented"),F("subscriptions","Fail-closed subscription state","implemented"),F("advanced","Returns workflow","implemented","/operations"),F("advanced","Exchange workflow","implemented","/operations"),F("advanced","Booking workflow","implemented","/operations"),F("advanced","Event workflow","implemented","/operations"),F("advanced","Ticket workflow","implemented","/operations"),F("advanced","Quote workflow","implemented","/operations"),F("advanced","Purchase-order workflow","implemented","/operations"),F("advanced","Expense workflow","implemented","/operations"),F("advanced","Lead workflow","implemented","/operations"),F("advanced","Task workflow","implemented","/operations"),F("advanced","Support-ticket workflow","implemented","/operations"),F("advanced","Internal message threads","implemented","/operations"),F("advanced","Preorder workflow","implemented","/operations"),F("advanced","Waitlist workflow","implemented","/operations"),F("advanced","Product-alert workflow","implemented","/operations"),F("advanced","Document metadata vault","implemented","/operations"),F("advanced","Customer document records","implemented","/operations"),F("advanced","Merchant API key management","implemented","/operations"),F("advanced","Merchant API-key authentication endpoint","implemented"),F("advanced","Merchant feature flags","implemented","/operations"),F("advanced","Experiment definitions","implemented","/operations"),F("advanced","Deterministic experiment assignment","implemented"),F("advanced","Accounting period lifecycle","implemented","/operations"),F("advanced","Safe rollout controls","implemented","/operations"),F("advanced","Account data export","implemented","/settings"),F("advanced","Safe account deletion","implemented","/settings"),F("advanced","Domain-event integration for advanced workflows","implemented"),F("ops","pnpm TypeScript monorepo","implemented"),F("ops","CI typecheck/security/build","implemented"),F("ops","Explicit migration runner","implemented")
] as const;

export const LUNAVO_FEATURE_REGISTRY: readonly LunavoFeature[] = LUNAVO_FEATURES.map(([area,name,status,route]) => ({ id:`${area}.${name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}`, area,name,status,...(route ? {route}:{}) }));
export function featureSummary() {
  const summary = LUNAVO_FEATURE_REGISTRY.reduce((s,f)=>{s.total++;s[f.status]++;return s;},{total:0,implemented:0,optional:0,partial:0,planned:0} as Record<string,number>);
  summary.requiredTotal = summary.total - summary.optional;
  summary.requiredImplemented = summary.implemented;
  summary.launchComplete = summary.partial === 0 && summary.planned === 0 && summary.requiredImplemented === summary.requiredTotal ? 1 : 0;
  return summary;
}
